package archgate

import (
	_ "embed"
	"go/ast"
	"go/token"
	"math"
	"strconv"
	"strings"
	"sync"

	"github.com/davidarcher/RimGovernor/go/internal/policy"
)

// defofNames lists the thing and terrain def names the game itself looks up by
// name: the static fields of RimWorld.ThingDefOf and RimWorld.TerrainDefOf, one
// per line. The other *DefOf classes (sounds, jobs, stats, thoughts, ...) are
// left out on purpose: their names are common words ("Release", "Maintain")
// that Go uses for unrelated strings, so a ratchet over them would be noise;
// widening is a filter change here. Generated, never typed in: run
// `dotnet restore --locked-mode` then `dotnet run --project <repo>/tools/defmirror
// -c Release --no-restore --no-launch-profile -- --report <file>`, keep the
// `defof` lines of those two classes, take the third column, sorted and unique.
//
//go:embed defof_names.txt
var defofNames string

// gameConstantValues lists the distinctive numeric values of the recorded
// catalog's GameConstants (see distinctiveConstant), one per line. Generated by
// TestGameConstantsListIsFresh (RG_UPDATE_GOLDEN=1 rewrites it).
//
//go:embed game_constants.txt
var gameConstantValues string

type rule6Lists struct {
	names  map[string]bool
	values map[float64]bool
}

var rule6Sets = sync.OnceValue(func() rule6Lists {
	sets := rule6Lists{names: map[string]bool{}, values: map[float64]bool{}}
	for _, l := range strings.Fields(defofNames) {
		sets.names[l] = true
	}
	for _, l := range strings.Fields(gameConstantValues) {
		if x, err := strconv.ParseFloat(l, 64); err == nil {
			sets.values[x] = true
		}
	}
	return sets
})

// distinctiveConstant says whether a mirrored numeric value is specific enough
// that a literal equal to it is a retyped game constant rather than a
// coincidence: an integer of at least 1000 that is not a power of ten or of two
// (1000, 10000 and 1024 are round numbers anyone writes). Smaller values and fractions (2, 15,
// 0.5, colour channels) match too many unrelated literals to ratchet.
func distinctiveConstant(x float64) bool {
	if math.IsNaN(x) || math.IsInf(x, 0) || x != math.Trunc(x) || x < 1000 {
		return false
	}
	if math.Pow(10, math.Round(math.Log10(x))) == x {
		return false
	}
	return x != math.Pow(2, math.Round(math.Log2(x)))
}

// rule6Tables is the set of table names policy registers in DefTables. A
// package-level var of one is an allowed owner of def names: the dangling
// reference gate checks every name in it against the recorded catalog.
func rule6Tables() map[string]bool {
	out := map[string]bool{}
	for _, t := range policy.DefTables() {
		out[t.Table] = true
	}
	return out
}

// Rule6 returns "file|func|\"DefName\"" for a quoted game def name (a static
// field of a game *DefOf class) and "file|func|number" for a retyped game
// constant (a distinctive GameConstants value) in non-test Go. Acceptance cases
// under internal/nativeaccept, domain/game_time.go (the calendar, guarded at
// decode time against the catalog) and the package-level vars that
// policy.DefTables registers are the allowed owners.
func Rule6(root string) []string {
	sets := rule6Sets()
	tables := rule6Tables()
	bad := map[string]bool{}
	for _, f := range load(root, []string{"internal", "cmd"}, true) {
		if strings.HasPrefix(f.rel, "internal/nativeaccept/") || f.rel == "internal/domain/game_time.go" {
			continue
		}
		for _, d := range f.node.Decls {
			name := funcName(d)
			ast.Inspect(d, func(n ast.Node) bool {
				switch v := n.(type) {
				case *ast.ImportSpec:
					return false
				case *ast.ValueSpec:
					if f.pkg == "policy" && name == "-" {
						for _, id := range v.Names {
							if tables[id.Name] {
								return false
							}
						}
					}
				case *ast.BasicLit:
					switch v.Kind {
					case token.STRING:
						if s, err := strconv.Unquote(v.Value); err == nil && sets.names[s] {
							bad[f.rel+"|"+name+"|"+strconv.Quote(s)] = true
						}
					case token.INT, token.FLOAT:
						if x, ok := literalNumber(v); ok && sets.values[x] {
							bad[f.rel+"|"+name+"|"+strconv.FormatFloat(x, 'g', -1, 64)] = true
						}
					}
				}
				return true
			})
		}
	}
	return sorted(bad)
}
