package policy

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/davidarcher/RimGovernor/go/internal/domain"
)

// Excavation site selection for B06f: a 1-wide corridor driven into a
// visible natural rock face from a walkable access cell, ending in a room
// interior. Targets are ordered cell sets: the interior is a rectangle or,
// since #64, an ellipse generated by the same integer formula as the B06e
// hut templates, and the frontier/stage machinery never looks at the shape.
//
// Fogged cells are unknown, never assumed empty or safe: a target may run
// through fogged space (that is the whole point of a mountain base), but
// any known cell inside or around it must be rock. Native
// ReadExcavationSite remains the authority for roof support and per-cell
// mining legality; this file only proposes geometry.

// Natural rock roofs. Only these mark a cell as part of a mountain, so a
// constructed wall under a built roof is never mistaken for a rock face.
var rockRoofs = map[string]bool{"RoofRockThin": true, "RoofRockThick": true}

// excavationSupportDistance is RimWorld's roof support radius: every target
// cell must lie within it of some non-target cell, so the rock left standing
// holds the roof over the whole dig. A rectangle up to excavationSupportSpan
// on a side satisfies it by construction; every shape is also checked cell
// by cell (excavationSupported).
const excavationSupportDistance = 6

// excavationSupportSpan is the widest rectangle whose centre is still within
// excavationSupportDistance of the rock around it.
const excavationSupportSpan = 2*excavationSupportDistance - 1

// excavationMaxRadius bounds ellipse radii so a round room also fits the
// support radius and the site read.
const excavationMaxRadius = 5

// excavationSunkWorkWeight is the score credit per already-open target cell,
// larger than any squared distance within the observed window so a target
// with sunk work always ranks first.
const excavationSunkWorkWeight = 4096

// excavationMaxCells matches NativeExcavationSite.MaxCells so a whole target
// fits in one site read.
const excavationMaxCells = 64

type ExcavationSiteRequest struct {
	Bounds Bounds
	// Region is the observed window: a cell absent from Cells inside it is
	// fogged (unknown); outside it nothing was read, so no target may touch it.
	Region    Rectangle
	Anchor    domain.Cell
	Cells     []SiteCell
	Protected []domain.Cell
	// Interior is the rectangular room size in cells (walls are the
	// surrounding rock), used when Shapes is empty.
	Interior Bounds
	// Shapes, when set, are the interiors tried at each face in preference
	// order; the first legal one at the shortest legal corridor is proposed.
	Shapes []ExcavationShape
	// MinCorridor..MaxCorridor bound the corridor length tried per face.
	MinCorridor, MaxCorridor int32
}

// ExcavationShapeKind names how an interior is generated.
type ExcavationShapeKind string

const (
	// ExcavationRectangle is a Width×Height room.
	ExcavationRectangle ExcavationShapeKind = "rectangle"
	// ExcavationEllipse is a round room from domain.EllipseInterior.
	ExcavationEllipse ExcavationShapeKind = "ellipse"
)

// ExcavationShape is one deterministic interior generator. The shape is
// reproduced from its parameters and the door, so a target key carries the
// parameters, never the cells.
type ExcavationShape struct {
	Kind ExcavationShapeKind
	// Width and Height size a rectangle.
	Width, Height int32
	// RadiusX, RadiusZ and Orientation size an ellipse (radii 1..5).
	RadiusX, RadiusZ int32
	Orientation      domain.EllipseOrientation
}

// RectangleShape and EllipseShape are the two constructors.
func RectangleShape(width, height int32) ExcavationShape {
	return ExcavationShape{Kind: ExcavationRectangle, Width: width, Height: height}
}

func EllipseShape(radiusX, radiusZ int32, orientation domain.EllipseOrientation) ExcavationShape {
	return ExcavationShape{Kind: ExcavationEllipse, RadiusX: radiusX, RadiusZ: radiusZ, Orientation: orientation}
}

func (s ExcavationShape) Validate() error {
	switch s.Kind {
	case ExcavationRectangle:
		if s.Width <= 0 || s.Height <= 0 || s.Width > excavationSupportSpan || s.Height > excavationSupportSpan {
			return errors.New("invalid excavation interior")
		}
	case ExcavationEllipse:
		if s.RadiusX < 1 || s.RadiusZ < 1 || s.RadiusX > excavationMaxRadius || s.RadiusZ > excavationMaxRadius || s.Orientation.Validate() != nil {
			return errors.New("invalid excavation ellipse")
		}
	default:
		return errors.New("unknown excavation shape")
	}
	return nil
}

// offsets returns the interior cells relative to the shape's centre and the
// rectangle bounding them.
func (s ExcavationShape) offsets() ([]domain.Cell, Rectangle) {
	var cells []domain.Cell
	switch s.Kind {
	case ExcavationRectangle:
		cells = rectCells(Rectangle{X: -s.Width / 2, Z: -s.Height / 2, Width: s.Width, Height: s.Height})
	case ExcavationEllipse:
		cells = domain.EllipseInterior(domain.Cell{}, s.RadiusX, s.RadiusZ, s.Orientation)
	}
	if len(cells) == 0 {
		return nil, Rectangle{}
	}
	lo, hi := cells[0], cells[0]
	for _, c := range cells {
		lo.X, lo.Z = min(lo.X, c.X), min(lo.Z, c.Z)
		hi.X, hi.Z = max(hi.X, c.X), max(hi.Z, c.Z)
	}
	return cells, Rectangle{X: lo.X, Z: lo.Z, Width: hi.X - lo.X + 1, Height: hi.Z - lo.Z + 1}
}

// place sites the shape just past the door along the corridor direction:
// its bounding rectangle is positioned exactly as a rectangular interior
// would be, and the cells are translated with it. It reports false when the
// cell past the door is not interior, since the corridor must open into the
// room.
func (s ExcavationShape) place(door, direction domain.Cell) (Rectangle, []domain.Cell, bool) {
	offsets, box := s.offsets()
	if len(offsets) == 0 {
		return Rectangle{}, nil, false
	}
	bounds := excavationInterior(door, direction, Bounds{Width: box.Width, Height: box.Height})
	shift := domain.Cell{X: bounds.X - box.X, Z: bounds.Z - box.Z}
	next := domain.Cell{X: door.X + direction.X, Z: door.Z + direction.Z}
	cells := make([]domain.Cell, 0, len(offsets))
	opens := false
	for _, c := range offsets {
		p := domain.Cell{X: c.X + shift.X, Z: c.Z + shift.Z}
		opens = opens || p == next
		cells = append(cells, p)
	}
	return bounds, cells, opens
}

// keySuffix is the shape's part of ExcavationTarget.Key: nothing for a
// rectangle (the interior rectangle already says it), the ellipse
// parameters otherwise.
func (s ExcavationShape) keySuffix() string {
	if s.Kind != ExcavationEllipse {
		return ""
	}
	return fmt.Sprintf(".e.%d.%d.%s", s.RadiusX, s.RadiusZ, s.Orientation)
}

// ExcavationTarget is one proposed dig: Access is the walkable cell the
// corridor starts from, Corridor runs inward from the face (Corridor[0] is
// the face cell), Door is the last corridor cell, Shape generates the room
// and Interior is the rectangle bounding it (the room itself for a
// rectangle). A zero Shape means the rectangle Interior describes.
type ExcavationTarget struct {
	Access    domain.Cell
	Direction domain.Cell
	Corridor  []domain.Cell
	Shape     ExcavationShape
	Interior  Rectangle
	Door      domain.Cell
	Score     int64
}

// InteriorCells returns the room cells in z-outer, x-inner order.
func (t ExcavationTarget) InteriorCells() []domain.Cell {
	if t.Shape.Kind != ExcavationEllipse {
		return rectCells(t.Interior)
	}
	_, cells, _ := t.Shape.place(t.Door, t.Direction)
	return cells
}

// Cells returns the ordered target: corridor first, then interior cells from
// the door outward, so a frontier walk digs the way a miner would.
func (t ExcavationTarget) Cells() []domain.Cell {
	out := append([]domain.Cell(nil), t.Corridor...)
	interior := t.InteriorCells()
	sort.Slice(interior, func(i, j int) bool {
		a, b := squaredDistance(interior[i], t.Door), squaredDistance(interior[j], t.Door)
		if a != b {
			return a < b
		}
		return cellLess(interior[i], interior[j])
	})
	return append(out, interior...)
}

// Center is the interior centre used for anchor distance comparisons; for
// every supported shape it is an interior cell.
func (t ExcavationTarget) Center() domain.Cell {
	return domain.Cell{X: t.Interior.X + t.Interior.Width/2, Z: t.Interior.Z + t.Interior.Height/2}
}

// Key is a compact, reversible identity for the target so per-stage plan
// identities survive restarts and cleared cells without any extra table.
// A rectangle's key is the nine legacy fields; an ellipse appends
// ".e.<radiusX>.<radiusZ>.<orientation>" after its bounding rectangle.
func (t ExcavationTarget) Key() string {
	return fmt.Sprintf("%d.%d.%d.%d.%d.%d.%d.%d.%d", t.Access.X, t.Access.Z, t.Direction.X, t.Direction.Z, len(t.Corridor), t.Interior.X, t.Interior.Z, t.Interior.Width, t.Interior.Height) + t.Shape.keySuffix()
}

// ParseExcavationKey rebuilds a target from Key. It validates shape only;
// the caller re-reads the site before trusting it.
func ParseExcavationKey(key string) (ExcavationTarget, error) {
	invalid := errors.New("invalid excavation key")
	parts := strings.Split(key, ".")
	if len(parts) != 9 && len(parts) != 13 {
		return ExcavationTarget{}, invalid
	}
	var v [9]int32
	for i, p := range parts[:9] {
		if _, err := fmt.Sscanf(p, "%d", &v[i]); err != nil || fmt.Sprint(v[i]) != p {
			return ExcavationTarget{}, invalid
		}
	}
	t := ExcavationTarget{Access: domain.Cell{X: v[0], Z: v[1]}, Direction: domain.Cell{X: v[2], Z: v[3]}, Interior: Rectangle{v[5], v[6], v[7], v[8]}}
	t.Shape = RectangleShape(t.Interior.Width, t.Interior.Height)
	if len(parts) == 13 {
		if parts[9] != "e" {
			return ExcavationTarget{}, invalid
		}
		var radii [2]int32
		for i, p := range parts[10:12] {
			if _, err := fmt.Sscanf(p, "%d", &radii[i]); err != nil || fmt.Sprint(radii[i]) != p {
				return ExcavationTarget{}, invalid
			}
		}
		t.Shape = EllipseShape(radii[0], radii[1], domain.EllipseOrientation(parts[12]))
	}
	length := v[4]
	if (t.Direction.X == 0) == (t.Direction.Z == 0) || t.Direction.X < -1 || t.Direction.X > 1 || t.Direction.Z < -1 || t.Direction.Z > 1 || length <= 0 || length > excavationMaxCells || t.Shape.Validate() != nil || t.Access.X < 0 || t.Access.Z < 0 || t.Interior.X < 0 || t.Interior.Z < 0 {
		return ExcavationTarget{}, invalid
	}
	for i := int32(1); i <= length; i++ {
		t.Corridor = append(t.Corridor, domain.Cell{X: t.Access.X + t.Direction.X*i, Z: t.Access.Z + t.Direction.Z*i})
	}
	t.Door = t.Corridor[len(t.Corridor)-1]
	expected, _, opens := t.Shape.place(t.Door, t.Direction)
	if !opens || expected != t.Interior || t.Corridor[0].X < 0 || t.Corridor[0].Z < 0 {
		return ExcavationTarget{}, invalid
	}
	cells := t.Cells()
	if len(cells) > excavationMaxCells || !excavationSupported(cells) {
		return ExcavationTarget{}, invalid
	}
	return t, nil
}

// excavationSupported reports whether every target cell lies within
// RimWorld's roof support radius of some cell outside the target, so the
// rock left standing supports the roof over the whole dig. It is the
// irregular-shape form of the rectangle span bound.
func excavationSupported(cells []domain.Cell) bool {
	inside := make(map[domain.Cell]bool, len(cells))
	for _, c := range cells {
		inside[c] = true
	}
	const r = excavationSupportDistance
	for _, c := range cells {
		held := false
		for dz := int32(-r); dz <= r && !held; dz++ {
			for dx := int32(-r); dx <= r; dx++ {
				if dx*dx+dz*dz <= r*r && !inside[domain.Cell{X: c.X + dx, Z: c.Z + dz}] {
					held = true
					break
				}
			}
		}
		if !held {
			return false
		}
	}
	return true
}

// excavationInterior centres a size-by-size room just past the door along
// the corridor direction.
func excavationInterior(door, direction domain.Cell, size Bounds) Rectangle {
	next := domain.Cell{X: door.X + direction.X, Z: door.Z + direction.Z}
	switch {
	case direction.Z > 0:
		return Rectangle{next.X - size.Width/2, next.Z, size.Width, size.Height}
	case direction.Z < 0:
		return Rectangle{next.X - size.Width/2, next.Z - size.Height + 1, size.Width, size.Height}
	case direction.X > 0:
		return Rectangle{next.X, next.Z - size.Height/2, size.Width, size.Height}
	default:
		return Rectangle{next.X - size.Width + 1, next.Z - size.Height/2, size.Width, size.Height}
	}
}

// rockCell is a visible natural rock cell: solid, impassable, under a rock roof.
func rockCell(c SiteCell) bool {
	occupied, ok := c.Occupied.Value()
	walkable, wk := c.Walkable.Value()
	roof, rk := c.Roof.Value()
	return ok && occupied && wk && !walkable && rk && rockRoofs[roof]
}

// excavatedCell is open ground still under a natural rock roof that is not
// part of a proper room: rock that has already been dug (or a natural
// pocket). A project whose goal was invalidated mid-way is re-planned over
// the same cells instead of abandoning the half-dug room.
func excavatedCell(c SiteCell) bool {
	occupied, ok := c.Occupied.Value()
	walkable, wk := c.Walkable.Value()
	roof, rk := c.Roof.Value()
	indoors, ik := c.Indoors.Value()
	return ok && !occupied && wk && walkable && rk && rockRoofs[roof] && (!ik || !indoors)
}

// ExcavationSites proposes corridor+room targets for every visible rock face
// reachable from a free access cell, best first. A target is rejected when
// any known cell inside it is not rock, when any known cell bordering it
// (other than the access cell) is passable, or when it touches the map edge.
func ExcavationSites(r ExcavationSiteRequest) ([]ExcavationTarget, error) {
	if r.Bounds.Width <= 0 || r.Bounds.Height <= 0 || r.Bounds.Width > 4096 || r.Bounds.Height > 4096 || len(r.Cells) > 65536 || len(r.Protected) > 65536 {
		return nil, errors.New("invalid excavation site bounds")
	}
	shapes := r.Shapes
	if len(shapes) == 0 {
		shapes = []ExcavationShape{RectangleShape(r.Interior.Width, r.Interior.Height)}
	}
	if r.MinCorridor <= 0 || r.MaxCorridor < r.MinCorridor || len(shapes) > 8 {
		return nil, errors.New("invalid excavation interior")
	}
	for _, shape := range shapes {
		if err := shape.Validate(); err != nil {
			return nil, err
		}
		if offsets, _ := shape.offsets(); len(offsets)+int(r.MaxCorridor) > excavationMaxCells || !excavationSupported(offsets) {
			return nil, errors.New("invalid excavation interior")
		}
	}
	inBounds := func(c domain.Cell) bool { return c.X >= 0 && c.Z >= 0 && c.X < r.Bounds.Width && c.Z < r.Bounds.Height }
	if r.Region.Width <= 0 || r.Region.Height <= 0 || !inBounds(domain.Cell{X: r.Region.X, Z: r.Region.Z}) || !inBounds(domain.Cell{X: r.Region.X + r.Region.Width - 1, Z: r.Region.Z + r.Region.Height - 1}) {
		return nil, errors.New("invalid observed region")
	}
	observed := func(c domain.Cell) bool {
		return c.X >= r.Region.X && c.Z >= r.Region.Z && c.X < r.Region.X+r.Region.Width && c.Z < r.Region.Z+r.Region.Height
	}
	// Digging against the map edge would open the room to the outside and
	// leaves no rock to hold the roof there.
	interior := func(c domain.Cell) bool {
		return observed(c) && c.X >= 1 && c.Z >= 1 && c.X < r.Bounds.Width-1 && c.Z < r.Bounds.Height-1
	}
	if !inBounds(r.Anchor) {
		return nil, errors.New("invalid colony anchor")
	}
	cells := make(map[domain.Cell]SiteCell, len(r.Cells))
	ordered := make([]domain.Cell, 0, len(r.Cells))
	for _, c := range r.Cells {
		if !inBounds(c.Cell) {
			return nil, errors.New("site cell out of bounds")
		}
		if _, exists := cells[c.Cell]; exists {
			return nil, errors.New("duplicate site cell")
		}
		cells[c.Cell] = c
		ordered = append(ordered, c.Cell)
	}
	sort.Slice(ordered, func(i, j int) bool { return cellLess(ordered[i], ordered[j]) })
	protected := map[domain.Cell]bool{}
	for _, c := range r.Protected {
		if !inBounds(c) {
			return nil, errors.New("protected cell out of bounds")
		}
		protected[c] = true
	}
	free := func(p domain.Cell) bool {
		c, exists := cells[p]
		return exists && !protected[p] && positive(c.Walkable) && positive(measured(c.Occupied, func(v bool) bool { return !v }))
	}
	// diggable: unknown (fogged), visible rock or already excavated, never
	// protected.
	diggable := func(p domain.Cell) bool {
		if !interior(p) || protected[p] {
			return false
		}
		c, exists := cells[p]
		return !exists || rockCell(c) || excavatedCell(c)
	}
	// sealed: a bordering cell that is unknown or known impassable keeps the
	// room enclosed once dug.
	sealed := func(p domain.Cell) bool {
		if !inBounds(p) || !observed(p) {
			return false
		}
		c, exists := cells[p]
		if !exists {
			return true
		}
		walkable, wk := c.Walkable.Value()
		return wk && !walkable
	}
	// judge accepts one placed target when every cell is diggable, at
	// least one is rock, and the room is sealed; it returns the score.
	judge := func(t ExcavationTarget, room []domain.Cell) (int64, bool) {
		target := append(append([]domain.Cell(nil), t.Corridor...), room...)
		access, length := t.Access, int32(len(t.Corridor))
		inside := make(map[domain.Cell]bool, len(target))
		legal, work, done := true, false, int64(0)
		for _, p := range target {
			if !diggable(p) {
				legal = false
				break
			}
			inside[p] = true
			if c, exists := cells[p]; !exists || rockCell(c) {
				work = true
			} else {
				done++
			}
		}
		// An already-open target is not an excavation.
		if !legal || !work {
			return 0, false
		}
		// The room must be sealed on all eight sides (its door is
		// the corridor); corridor cells only need their cardinal
		// neighbours sealed, since the mouth diagonals face open
		// ground by construction.
		for i, p := range target {
			corridor := i < len(t.Corridor)
			for dx := int32(-1); dx <= 1 && legal; dx++ {
				for dz := int32(-1); dz <= 1; dz++ {
					n := domain.Cell{X: p.X + dx, Z: p.Z + dz}
					if inside[n] || n == access || corridor && dx != 0 && dz != 0 {
						continue
					}
					if !sealed(n) {
						legal = false
						break
					}
				}
			}
		}
		if !legal {
			return 0, false
		}
		// Work already done outweighs distance: the colony anchor
		// drifts with the pawns, and a half-dug room must win over
		// a fresh face a cell nearer.
		return squaredDistance(t.Center(), r.Anchor) + 4*int64(length) - done*excavationSunkWorkWeight, true
	}
	directions := []domain.Cell{{X: 0, Z: 1}, {X: 1, Z: 0}, {X: 0, Z: -1}, {X: -1, Z: 0}}
	var targets []ExcavationTarget
	seen := map[string]bool{}
	for _, access := range ordered {
		if !free(access) {
			continue
		}
		for _, d := range directions {
			face := domain.Cell{X: access.X + d.X, Z: access.Z + d.Z}
			c, exists := cells[face]
			if !exists || !(rockCell(c) || excavatedCell(c)) {
				continue
			}
			for length := r.MinCorridor; length <= r.MaxCorridor; length++ {
				corridor := make([]domain.Cell, 0, length)
				for i := int32(1); i <= length; i++ {
					corridor = append(corridor, domain.Cell{X: access.X + d.X*i, Z: access.Z + d.Z*i})
				}
				legal := false
				for _, shape := range shapes {
					t := ExcavationTarget{Access: access, Direction: d, Corridor: corridor, Shape: shape, Door: corridor[len(corridor)-1]}
					var cells []domain.Cell
					var opens bool
					if t.Interior, cells, opens = shape.place(t.Door, d); !opens {
						continue
					}
					if seen[t.Key()] {
						continue
					}
					seen[t.Key()] = true
					if score, ok := judge(t, cells); ok {
						t.Score = score
						targets = append(targets, t)
						legal = true
						break
					}
				}
				// A longer corridor from the same face, or a lesser shape,
				// only helps when the preferred one was illegal.
				if legal {
					break
				}
			}
		}
	}
	sort.Slice(targets, func(i, j int) bool {
		if targets[i].Score != targets[j].Score {
			return targets[i].Score < targets[j].Score
		}
		if targets[i].Access != targets[j].Access {
			return cellLess(targets[i].Access, targets[j].Access)
		}
		return cellLess(targets[i].Direction, targets[j].Direction)
	})
	if len(targets) > 12 {
		targets = targets[:12]
	}
	return targets, nil
}

// excavationReach bounds how far from the colony anchor an excavated room
// may sit before the open-site shell is preferred; it matches the native
// planning window so every candidate the policy can see is also reachable
// without a long trek.
const excavationReach = 22

// ChooseExcavation decides between the open-site starter shell and digging
// in, deterministically and without a tuning knob. A rock room needs no wall
// material and holds its own roof, so a verified site within reach of the
// anchor wins outright; farther sites win only when no clean shell exists,
// and a shell nearer the anchor than a far site keeps the shell.
func ChooseExcavation(anchor domain.Cell, shell *StarterLayout, site *ExcavationTarget) bool {
	if site == nil {
		return false
	}
	if shell == nil || squaredDistance(site.Center(), anchor) <= excavationReach*excavationReach {
		return true
	}
	shellCenter := domain.Cell{X: shell.Room.X + shell.Room.Width/2, Z: shell.Room.Z + shell.Room.Height/2}
	return squaredDistance(site.Center(), anchor) < squaredDistance(shellCenter, anchor)
}
