// Code generated by contractgen format 1; DO NOT EDIT.
// Source: contracts/schemas/colony-identity.v1.schema.json
// SHA256: c36f63bb3040b1e5c1d633754fd534ba07de96720595db6649538491efdf1af0
package wire

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"unicode/utf8"
)

type ColonyIdentity struct {
	ColonyId                     string `json:"colonyId"`
	LoadToken                    string `json:"loadToken"`
	MapId                        int32  `json:"mapId"`
	ObservationBatchVersion      int32  `json:"observationBatchVersion"`
	PlacementPreviewBatchVersion int32  `json:"placementPreviewBatchVersion"`
	Success                      bool   `json:"success"`
	Tick                         int32  `json:"tick"`
}

// DecodeColonyIdentity rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeColonyIdentity(data []byte) (ColonyIdentity, error) {
	var zero ColonyIdentity
	d, err := colonyIdentityNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := colonyIdentityDecodeValue0(d)
	if err != nil {
		return zero, err
	}
	if err = colonyIdentityEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

func colonyIdentityDecodeValue0(d *json.Decoder) (ColonyIdentity, error) {
	var result ColonyIdentity
	if err := colonyIdentityExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "colonyId":
			value, err := colonyIdentityDecodeValue1(d)
			if err != nil {
				return result, fmt.Errorf("colonyId: %w", err)
			}
			result.ColonyId = value
		case "loadToken":
			value, err := colonyIdentityDecodeValue2(d)
			if err != nil {
				return result, fmt.Errorf("loadToken: %w", err)
			}
			result.LoadToken = value
		case "mapId":
			value, err := colonyIdentityDecodeValue3(d)
			if err != nil {
				return result, fmt.Errorf("mapId: %w", err)
			}
			result.MapId = value
		case "observationBatchVersion":
			value, err := colonyIdentityDecodeValue4(d)
			if err != nil {
				return result, fmt.Errorf("observationBatchVersion: %w", err)
			}
			result.ObservationBatchVersion = value
		case "placementPreviewBatchVersion":
			value, err := colonyIdentityDecodeValue5(d)
			if err != nil {
				return result, fmt.Errorf("placementPreviewBatchVersion: %w", err)
			}
			result.PlacementPreviewBatchVersion = value
		case "success":
			value, err := colonyIdentityDecodeValue6(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		case "tick":
			value, err := colonyIdentityDecodeValue7(d)
			if err != nil {
				return result, fmt.Errorf("tick: %w", err)
			}
			result.Tick = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := colonyIdentityExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["colonyId"] {
		return result, fmt.Errorf("missing required field: colonyId")
	}
	if !seen["loadToken"] {
		return result, fmt.Errorf("missing required field: loadToken")
	}
	if !seen["mapId"] {
		return result, fmt.Errorf("missing required field: mapId")
	}
	if !seen["observationBatchVersion"] {
		return result, fmt.Errorf("missing required field: observationBatchVersion")
	}
	if !seen["placementPreviewBatchVersion"] {
		return result, fmt.Errorf("missing required field: placementPreviewBatchVersion")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	if !seen["tick"] {
		return result, fmt.Errorf("missing required field: tick")
	}
	return result, nil
}

func colonyIdentityDecodeValue1(d *json.Decoder) (string, error) {
	value, err := colonyIdentityReadString(d, 256, true)
	return string(value), err
}

func colonyIdentityDecodeValue2(d *json.Decoder) (string, error) {
	value, err := colonyIdentityReadString(d, 256, true)
	return string(value), err
}

func colonyIdentityDecodeValue3(d *json.Decoder) (int32, error) {
	value, err := colonyIdentityReadInteger(d, 0, 2147483647)
	return int32(value), err
}

func colonyIdentityDecodeValue4(d *json.Decoder) (int32, error) {
	value, err := colonyIdentityReadInteger(d, 0, 2147483647)
	return int32(value), err
}

func colonyIdentityDecodeValue5(d *json.Decoder) (int32, error) {
	value, err := colonyIdentityReadInteger(d, 0, 2147483647)
	return int32(value), err
}

func colonyIdentityDecodeValue6(d *json.Decoder) (bool, error) {
	value, err := colonyIdentityReadBoolean(d)
	return bool(value), err
}

func colonyIdentityDecodeValue7(d *json.Decoder) (int32, error) {
	value, err := colonyIdentityReadInteger(d, 0, 2147483647)
	return int32(value), err
}

// Decoder input is bounded independently of schema field limits. Readers are not
// accepted: callers retain ownership of transport limits and cancellation.
const colonyIdentityMaxContractBytes = 1 << 20

func colonyIdentityNewContractDecoder(data []byte) (*json.Decoder, error) {
	if len(data) > colonyIdentityMaxContractBytes {
		return nil, fmt.Errorf("contract JSON exceeds %d bytes", colonyIdentityMaxContractBytes)
	}
	if err := colonyIdentityValidJSONText(data); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decoder, nil
}

func colonyIdentityEndContract(decoder *json.Decoder) error {
	if _, err := decoder.Token(); err != io.EOF {
		return fmt.Errorf("trailing or malformed JSON data")
	}
	return nil
}

// encoding/json replaces invalid UTF-8 and unpaired surrogate escapes. Reject
// those before decoding so contracts cannot silently change caller-provided text.
func colonyIdentityValidJSONText(data []byte) error {
	if !utf8.Valid(data) {
		return fmt.Errorf("invalid UTF-8")
	}
	inString := false
	depth := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '"' {
			inString = !inString
			continue
		}
		if !inString {
			switch data[i] {
			case '{', '[':
				depth++
				if depth > 64 {
					return fmt.Errorf("JSON exceeds 64 containers")
				}
			case '}', ']':
				depth--
			}
		}
		if !inString || data[i] != '\\' {
			continue
		}
		i++
		if i >= len(data) {
			return fmt.Errorf("incomplete string escape")
		}
		if data[i] != 'u' {
			continue
		}
		if i+4 >= len(data) {
			return fmt.Errorf("incomplete Unicode escape")
		}
		unit, err := strconv.ParseUint(string(data[i+1:i+5]), 16, 16)
		if err != nil {
			return fmt.Errorf("invalid Unicode escape")
		}
		i += 4
		if unit >= 0xDC00 && unit <= 0xDFFF {
			return fmt.Errorf("unpaired low surrogate")
		}
		if unit < 0xD800 || unit > 0xDBFF {
			continue
		}
		if i+6 >= len(data) || data[i+1] != '\\' || data[i+2] != 'u' {
			return fmt.Errorf("unpaired high surrogate")
		}
		low, err := strconv.ParseUint(string(data[i+3:i+7]), 16, 16)
		if err != nil || low < 0xDC00 || low > 0xDFFF {
			return fmt.Errorf("unpaired high surrogate")
		}
		i += 6
	}
	return nil
}

func colonyIdentityReadString(decoder *json.Decoder, maximum int, nonblank bool) (string, error) {
	value, err := decoder.Token()
	if err != nil {
		return "", err
	}
	text, ok := value.(string)
	if !ok {
		return "", fmt.Errorf("expected non-null string")
	}
	units, hasContent := 0, false
	for _, r := range text {
		units++
		if r > 0xFFFF {
			units++
		}
		if !colonyIdentityDotNetWhitespace(r) {
			hasContent = true
		}
	}
	if units > maximum || nonblank && !hasContent {
		return "", fmt.Errorf("string violates UTF-16 length or nonblank constraint")
	}
	return text, nil
}

// Explicit Char.IsWhiteSpace set used by the net472 placement request contract.
func colonyIdentityDotNetWhitespace(r rune) bool {
	return r >= '\t' && r <= '\r' || r == ' ' || r == 0x85 || r == 0xA0 ||
		r == 0x1680 || r >= 0x2000 && r <= 0x200A || r == 0x2028 || r == 0x2029 ||
		r == 0x202F || r == 0x205F || r == 0x3000
}

func colonyIdentityReadInteger(decoder *json.Decoder, minimum, maximum int64) (int32, error) {
	value, err := decoder.Token()
	if err != nil {
		return 0, err
	}
	number, ok := value.(json.Number)
	if !ok {
		return 0, fmt.Errorf("expected non-null integer token")
	}
	parsed, err := strconv.ParseInt(string(number), 10, 32)
	if err != nil || parsed < minimum || parsed > maximum {
		return 0, fmt.Errorf("expected integer token within [%d,%d]", minimum, maximum)
	}
	return int32(parsed), nil
}

func colonyIdentityReadBoolean(decoder *json.Decoder) (bool, error) {
	value, err := decoder.Token()
	if err != nil {
		return false, err
	}
	result, ok := value.(bool)
	if !ok {
		return false, fmt.Errorf("expected non-null boolean")
	}
	return result, nil
}

func colonyIdentityExpectDelimiter(decoder *json.Decoder, want json.Delim) error {
	value, err := decoder.Token()
	if err != nil {
		return err
	}
	if value != want {
		return fmt.Errorf("expected %c", want)
	}
	return nil
}
