// Code generated by contractgen format 1; DO NOT EDIT.
// Source: contracts/schemas/status-clock-projection.v1.schema.json
// SHA256: 8f6ff13382b1097ca721e75f8eb19cf109b31c3a214143dd82127aad82df767b
package wire

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"unicode/utf8"
)

type StatusClock struct {
	ForcePaused *bool   `json:"forcePaused,omitempty"`
	Paused      *bool   `json:"paused,omitempty"`
	Status      string  `json:"status"`
	TimeSpeed   *string `json:"timeSpeed,omitempty"`
}

// DecodeStatusClock rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeStatusClock(data []byte) (StatusClock, error) {
	var zero StatusClock
	d, err := statusClockNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := statusClockDecodeValue0(d)
	if err != nil {
		return zero, err
	}
	if err = statusClockEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

func statusClockDecodeValue0(d *json.Decoder) (StatusClock, error) {
	var result StatusClock
	if err := statusClockExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "forcePaused":
			value, err := statusClockDecodeValue1(d)
			if err != nil {
				return result, fmt.Errorf("forcePaused: %w", err)
			}
			result.ForcePaused = &value
		case "paused":
			value, err := statusClockDecodeValue2(d)
			if err != nil {
				return result, fmt.Errorf("paused: %w", err)
			}
			result.Paused = &value
		case "status":
			value, err := statusClockDecodeValue3(d)
			if err != nil {
				return result, fmt.Errorf("status: %w", err)
			}
			result.Status = value
		case "timeSpeed":
			value, err := statusClockDecodeValue4(d)
			if err != nil {
				return result, fmt.Errorf("timeSpeed: %w", err)
			}
			result.TimeSpeed = &value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := statusClockExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["status"] {
		return result, fmt.Errorf("missing required field: status")
	}
	return result, nil
}

func statusClockDecodeValue1(d *json.Decoder) (bool, error) {
	value, err := statusClockReadBoolean(d)
	return bool(value), err
}

func statusClockDecodeValue2(d *json.Decoder) (bool, error) {
	value, err := statusClockReadBoolean(d)
	return bool(value), err
}

func statusClockDecodeValue3(d *json.Decoder) (string, error) {
	value, err := statusClockReadString(d, 32, true)
	return string(value), err
}

func statusClockDecodeValue4(d *json.Decoder) (string, error) {
	value, err := statusClockReadString(d, 32, true)
	return string(value), err
}

// Decoder input is bounded independently of schema field limits. Readers are not
// accepted: callers retain ownership of transport limits and cancellation.
const statusClockMaxContractBytes = 1 << 20

func statusClockNewContractDecoder(data []byte) (*json.Decoder, error) {
	if len(data) > statusClockMaxContractBytes {
		return nil, fmt.Errorf("contract JSON exceeds %d bytes", statusClockMaxContractBytes)
	}
	if err := statusClockValidJSONText(data); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decoder, nil
}

func statusClockEndContract(decoder *json.Decoder) error {
	if _, err := decoder.Token(); err != io.EOF {
		return fmt.Errorf("trailing or malformed JSON data")
	}
	return nil
}

// encoding/json replaces invalid UTF-8 and unpaired surrogate escapes. Reject
// those before decoding so contracts cannot silently change caller-provided text.
func statusClockValidJSONText(data []byte) error {
	if !utf8.Valid(data) {
		return fmt.Errorf("invalid UTF-8")
	}
	inString := false
	depth := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '"' {
			inString = !inString
			continue
		}
		if !inString {
			switch data[i] {
			case '{', '[':
				depth++
				if depth > 64 {
					return fmt.Errorf("JSON exceeds 64 containers")
				}
			case '}', ']':
				depth--
			}
		}
		if !inString || data[i] != '\\' {
			continue
		}
		i++
		if i >= len(data) {
			return fmt.Errorf("incomplete string escape")
		}
		if data[i] != 'u' {
			continue
		}
		if i+4 >= len(data) {
			return fmt.Errorf("incomplete Unicode escape")
		}
		unit, err := strconv.ParseUint(string(data[i+1:i+5]), 16, 16)
		if err != nil {
			return fmt.Errorf("invalid Unicode escape")
		}
		i += 4
		if unit >= 0xDC00 && unit <= 0xDFFF {
			return fmt.Errorf("unpaired low surrogate")
		}
		if unit < 0xD800 || unit > 0xDBFF {
			continue
		}
		if i+6 >= len(data) || data[i+1] != '\\' || data[i+2] != 'u' {
			return fmt.Errorf("unpaired high surrogate")
		}
		low, err := strconv.ParseUint(string(data[i+3:i+7]), 16, 16)
		if err != nil || low < 0xDC00 || low > 0xDFFF {
			return fmt.Errorf("unpaired high surrogate")
		}
		i += 6
	}
	return nil
}

func statusClockReadString(decoder *json.Decoder, maximum int, nonblank bool) (string, error) {
	value, err := decoder.Token()
	if err != nil {
		return "", err
	}
	text, ok := value.(string)
	if !ok {
		return "", fmt.Errorf("expected non-null string")
	}
	units, hasContent := 0, false
	for _, r := range text {
		units++
		if r > 0xFFFF {
			units++
		}
		if !statusClockDotNetWhitespace(r) {
			hasContent = true
		}
	}
	if units > maximum || nonblank && !hasContent {
		return "", fmt.Errorf("string violates UTF-16 length or nonblank constraint")
	}
	return text, nil
}

// Explicit Char.IsWhiteSpace set used by the net472 placement request contract.
func statusClockDotNetWhitespace(r rune) bool {
	return r >= '\t' && r <= '\r' || r == ' ' || r == 0x85 || r == 0xA0 ||
		r == 0x1680 || r >= 0x2000 && r <= 0x200A || r == 0x2028 || r == 0x2029 ||
		r == 0x202F || r == 0x205F || r == 0x3000
}

func statusClockReadInteger(decoder *json.Decoder, minimum, maximum int64) (int32, error) {
	value, err := decoder.Token()
	if err != nil {
		return 0, err
	}
	number, ok := value.(json.Number)
	if !ok {
		return 0, fmt.Errorf("expected non-null integer token")
	}
	parsed, err := strconv.ParseInt(string(number), 10, 32)
	if err != nil || parsed < minimum || parsed > maximum {
		return 0, fmt.Errorf("expected integer token within [%d,%d]", minimum, maximum)
	}
	return int32(parsed), nil
}

func statusClockReadBoolean(decoder *json.Decoder) (bool, error) {
	value, err := decoder.Token()
	if err != nil {
		return false, err
	}
	result, ok := value.(bool)
	if !ok {
		return false, fmt.Errorf("expected non-null boolean")
	}
	return result, nil
}

func statusClockExpectDelimiter(decoder *json.Decoder, want json.Delim) error {
	value, err := decoder.Token()
	if err != nil {
		return err
	}
	if value != want {
		return fmt.Errorf("expected %c", want)
	}
	return nil
}
