<?xml version='1.0' encoding='utf-8'?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RimBot.Tests</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <OutputPath>bin\Release\</OutputPath>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\RimBot\Libs\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="DecisionChecks.cs" />
    <Compile Include="TaskDismissChecks.cs" />
    <Compile Include="ManagementChecks.cs" />
    <Compile Include="..\RimBot\Colony\ManagementContracts.cs" />
    <Compile Include="..\RimBot\Colony\ManagementCoordinator.cs" />
    <Compile Include="..\RimBot\Colony\DecisionMemory.cs" />
    <Compile Include="StateTransferChecks.cs" />
    <Compile Include="..\RimBot\Colony\TaskLedger.cs" />
    <Compile Include="..\RimBot\Colony\StateTransfer.cs" />
    <Compile Include="..\RimBot\Colony\OrderMemory.cs" />
    <Compile Include="..\RimBot\Colony\ObservedIdentifiers.cs" />
    <Compile Include="..\RimBot\Colony\ToolNames.cs" />
    <Compile Include="..\RimBot\Colony\NotificationFeed.cs" />
    <Compile Include="..\RimBot\Colony\DailyPlanning.cs" />
    <Compile Include="..\RimBot\Colony\ToolSession.cs" />
    <Compile Include="..\RimBot\Colony\StrategicPlan.cs" />
    <Compile Include="..\RimBot\Colony\ItemQuery.cs" />
    <Compile Include="..\RimBot\Colony\ColonyObjectives.cs" />
    <Compile Include="..\RimBot\Colony\ActivitySummary.cs" />
    <Compile Include="..\RimBot\Colony\ReviewBudget.cs" />
    <Compile Include="..\RimBot\Colony\ManagerPrompt.cs" />
    <Compile Include="..\RimBot\Colony\ToolCatalog.cs" />
    <Compile Include="..\RimBot\Colony\Contracts.cs" />
    <Compile Include="..\RimBot\Models\LocalModel.cs" />
    <Compile Include="..\RimBot\Models\LLMProviderType.cs" />
    <Compile Include="..\RimBot\Models\ThinkingLevel.cs" />
    <Compile Include="..\RimBot\Models\ILanguageModel.cs" />
    <Compile Include="..\RimBot\Models\ChatMessage.cs" />
    <Compile Include="..\RimBot\Models\ContentPart.cs" />
    <Compile Include="..\RimBot\Models\ModelResponse.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>