#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Google.Protobuf;
using Google.Protobuf.Reflection;
using Defs = RimGovernor.Protocol.Defs;

namespace HomeBridge.BridgeTools
{
    // Fills the messages of defs.proto (generated by tools/defmirror) from the
    // game's def objects by protobuf reflection, with no per-class code. The
    // mapping is the generator's contract (contracts/schema-generation.md):
    //   * a message mirrors the CLR class named by its clr_type option, and a
    //     field's name is the CLR field's name, public or not, except a derived field
    //     (clr_path option) that is the value of a member path (modPackageId);
    //   * a def reference is the def's defName, a System.Type its full name, an
    //     enum its numeric value, a Nullable<T> an optional field, a SlateRef<T>
    //     its XML text;
    //   * a List, array or HashSet is a repeated field, a Dictionary repeated
    //     "entry" messages (key, value), a nested collection a "list" message
    //     (items), and a class element an "optional" message (value) that stays
    //     unset for a null element, because the game uses null entries positionally;
    //   * a class with subclasses is a "<Class>Any" message whose oneof arm is
    //     chosen by the value's exact type.
    // A value the mirror cannot hold (a null string, def or Type element, a null dictionary key or scalar value, a type without
    // an arm such as a mod's CompProperties subclass, a missing CLR field) throws
    // naming Class.field; nothing is skipped. A null reference leaves its field
    // unset. One instance serves one read on one thread: it caches per descriptor.
    internal sealed class DefMirrorFill
    {
        private sealed class Plan
        {
            internal string Clr = "";
            internal Type Type = typeof(object);
            internal FieldDescriptor[] Fields = Array.Empty<FieldDescriptor>();
            // Reads field i of a source: a CLR field, or the member path of a derived field.
            internal Func<object, object?>[] Readers = Array.Empty<Func<object, object?>>();
        }

        private const BindingFlags AnyInstance = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;

        private readonly Dictionary<MessageDescriptor, Plan> plans = new Dictionary<MessageDescriptor, Plan>();
        // The classes of the System.Type values the fill wrote; the classes of the
        // filled objects are the plans' types.
        private readonly HashSet<Type> typeValues = new HashSet<Type>();
        // The objects being filled, outermost first: a def field that reaches an
        // object already being filled would recurse forever.
        private readonly HashSet<object> active = new HashSet<object>(new IdentityComparer());

        private sealed class IdentityComparer : IEqualityComparer<object>
        {
            bool IEqualityComparer<object>.Equals(object x, object y) => ReferenceEquals(x, y);
            int IEqualityComparer<object>.GetHashCode(object value) => System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(value);
        }
        private readonly Dictionary<MessageDescriptor, Dictionary<string, FieldDescriptor>> arms = new Dictionary<MessageDescriptor, Dictionary<string, FieldDescriptor>>();

        // The static members of the game classes: GameConstants (root) with one
        // <Class>Constants message per class, each field read from the static field
        // of the same name in the loaded assembly (never the reference one: a public
        // const is inlined there). A const is read with GetRawConstantValue, a
        // static readonly from the live field. Static data of the build: the read
        // touches no world state except what a class initializer itself reads.
        // A class or member the game no longer has throws naming Class.field.
        internal T BuildStatics<T>() where T : IMessage, new()
        {
            var root = new T();
            foreach (var holder in root.Descriptor.Fields.InFieldNumberOrder())
            {
                var clr = Clr(holder.MessageType) ?? throw Fail(root.Descriptor.Name, holder.Name, $"{holder.MessageType.Name} has no clr_type option");
                var type = AppDomain.CurrentDomain.GetAssemblies().Select(a => a.GetType(clr, false)).FirstOrDefault(t => t != null)
                    ?? throw Fail(clr, "(class)", "the game has no such class");
                var message = Create(holder.MessageType);
                foreach (var fd in holder.MessageType.Fields.InFieldNumberOrder())
                {
                    var info = type.GetField(fd.Name, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                        ?? throw Fail(clr, fd.Name, "no such static field");
                    object? value;
                    try { value = info.IsLiteral ? info.GetRawConstantValue() : info.GetValue(null); }
                    catch (Exception ex) when (ex is TargetInvocationException || ex is TypeInitializationException)
                    {
                        throw Fail(clr, fd.Name, "the class initializer failed: " + (ex.InnerException ?? ex).Message);
                    }
                    if (value == null) continue;
                    if (fd.IsRepeated) AddAll((IList)fd.Accessor.GetValue(message), fd, value, clr, fd.Name);
                    else fd.Accessor.SetValue(message, Value(fd, value, clr, fd.Name));
                }
                holder.Accessor.SetValue(root, message);
            }
            return root;
        }

        // The message mirroring source, filled.
        internal T Build<T>(object source) where T : IMessage, new()
        {
            var message = new T();
            Fill(message, source, message.Descriptor.Name, "(root)");
            return message;
        }

        // The message of descriptor mirroring source.
        internal IMessage Build(MessageDescriptor descriptor, object source)
        {
            var message = Create(descriptor);
            Fill(message, source, descriptor.Name, "(root)");
            return message;
        }

        // The CLR class a message mirrors, null for a wrapper or synthetic message.
        internal string? ClrName(MessageDescriptor descriptor) => Clr(descriptor);

        private readonly Dictionary<MessageDescriptor, (string? Clr, string? Synthetic)> options = new Dictionary<MessageDescriptor, (string?, string?)>();

        private (string? Clr, string? Synthetic) OptionsOf(MessageDescriptor descriptor)
        {
            if (options.TryGetValue(descriptor, out var found)) return found;
            var raw = descriptor.GetOptions();
            return options[descriptor] = (
                raw != null && raw.HasExtension(Defs.DefsExtensions.ClrType) ? raw.GetExtension(Defs.DefsExtensions.ClrType) : null,
                raw != null && raw.HasExtension(Defs.DefsExtensions.ClrSynthetic) ? raw.GetExtension(Defs.DefsExtensions.ClrSynthetic) : null);
        }

        private string? Clr(MessageDescriptor descriptor) => OptionsOf(descriptor).Clr;

        private string? Synthetic(MessageDescriptor descriptor) => OptionsOf(descriptor).Synthetic;

        private static Exception Fail(string owner, string field, string reason) => new InvalidOperationException($"{owner}.{field}: {reason}");

        private static IMessage Create(MessageDescriptor descriptor) => (IMessage)Activator.CreateInstance(descriptor.ClrType)!;

        private Plan PlanOf(MessageDescriptor descriptor, object source, string owner, string field)
        {
            if (plans.TryGetValue(descriptor, out var plan))
            {
                if (plan.Type != source.GetType() && !(plan.Fields.Length == 0 && plan.Type.IsInstanceOfType(source)))
                    throw Fail(owner, field, $"{source.GetType().FullName} is not the mirrored class {plan.Clr} of {descriptor.Name}");
                return plan;
            }
            var clr = Clr(descriptor);
            if (clr == null) throw Fail(owner, field, $"{descriptor.Name} has no clr_type option");
            var type = source.GetType();
            var fields = descriptor.Fields.InFieldNumberOrder().ToArray();
            if (type.FullName != clr)
            {
                // A fieldless extension point (DefModExtension) has no data to mirror, so a
                // mod's own subclass of it (TrainingTier) mirrors as the empty base message.
                var baseType = fields.Length == 0 ? BaseChain(type).FirstOrDefault(t => t.FullName == clr) : null;
                if (baseType == null) throw Fail(owner, field, $"{type.FullName} is not the mirrored class {clr} of {descriptor.Name}");
                return plans[descriptor] = new Plan { Clr = clr, Type = baseType };
            }
            var readers = new Func<object, object?>[fields.Length];
            for (var i = 0; i < fields.Length; i++)
            {
                // A derived field (clr_path) is read through its member path, a
                // mirrored field from the CLR field of that name, of any visibility
                // (the game's XML loader fills private fields too).
                var raw = fields[i].GetOptions();
                if (raw != null && raw.HasExtension(Defs.DefsExtensions.ClrPath))
                {
                    var steps = raw.GetExtension(Defs.DefsExtensions.ClrPath).Split('.');
                    var derived = fields[i].Name;
                    readers[i] = source => ReadPath(source, steps, clr, derived);
                    continue;
                }
                FieldInfo? found = null;
                for (var t = type; t != null && found == null; t = t.BaseType)
                    found = t.GetField(fields[i].Name, AnyInstance);
                var info = found ?? throw Fail(clr, fields[i].Name, "no such instance field");
                readers[i] = info.GetValue;
            }
            return plans[descriptor] = new Plan { Clr = clr, Type = type, Fields = fields, Readers = readers };
        }

        private static IEnumerable<Type> BaseChain(Type type)
        {
            for (var t = type.BaseType; t != null; t = t.BaseType) yield return t;
        }

        // The value of a dot-separated member path (fields or properties, any
        // visibility) from source; null when a step is null.
        private static object? ReadPath(object source, string[] steps, string owner, string field)
        {
            object? current = source;
            foreach (var step in steps)
            {
                if (current == null) return null;
                var type = current.GetType();
                object? next = null;
                var found = false;
                for (var t = type; t != null && !found; t = t.BaseType)
                {
                    if (t.GetField(step, AnyInstance) is { } info) { next = info.GetValue(current); found = true; }
                    else if (t.GetProperty(step, AnyInstance) is { } property) { next = property.GetValue(current); found = true; }
                }
                if (!found) throw Fail(owner, field, $"{type.FullName} has no member {step} of the path");
                current = next;
            }
            return current;
        }

        private void Fill(IMessage message, object source, string owner, string field)
        {
            var plan = PlanOf(message.Descriptor, source, owner, field);
            // A def's object graph is a tree; an object that holds itself again (a
            // runtime back pointer) fails the read here instead of overflowing the stack.
            var tracked = !source.GetType().IsValueType;
            if (tracked && !active.Add(source)) throw Fail(owner, field, $"{plan.Clr} object reaches itself again");
            for (var i = 0; i < plan.Fields.Length; i++)
            {
                var fd = plan.Fields[i];
                var value = plan.Readers[i](source);
                if (value == null) continue;
                if (fd.IsRepeated) AddAll((IList)fd.Accessor.GetValue(message), fd, value, plan.Clr, fd.Name);
                else fd.Accessor.SetValue(message, Value(fd, value, plan.Clr, fd.Name));
            }
            if (tracked) active.Remove(source);
        }

        // Every class the fill touched with its base classes, nearest first, up
        // to but not including System.Object: the class of each filled object
        // (the def classes among them) and each System.Type value written
        // (worker, condition and thing classes), sorted by full name.
        internal List<KeyValuePair<string, List<string>>> ClassChains()
        {
            var classes = new HashSet<Type>(typeValues);
            foreach (var plan in plans.Values) classes.Add(plan.Type);
            var chains = new List<KeyValuePair<string, List<string>>>();
            foreach (var type in classes)
            {
                var bases = new List<string>();
                for (var b = type.BaseType; b != null && b != typeof(object); b = b.BaseType)
                    bases.Add(b.FullName ?? throw new InvalidOperationException($"{type.FullName}: base class {b} has no full name"));
                chains.Add(new KeyValuePair<string, List<string>>(type.FullName ?? throw new InvalidOperationException($"type {type} has no full name"), bases));
            }
            chains.Sort((a, b) => string.CompareOrdinal(a.Key, b.Key));
            return chains;
        }

        private void AddAll(IList target, FieldDescriptor fd, object collection, string owner, string field)
        {
            var entry = fd.FieldType == FieldType.Message && Synthetic(fd.MessageType) == "entry";
            if (collection is IDictionary dictionary)
            {
                if (!entry) throw Fail(owner, field, $"a dictionary {collection.GetType().FullName} in a field that is not a key/value entry list");
                var keyField = fd.MessageType.FindFieldByNumber(1);
                var valueField = fd.MessageType.FindFieldByNumber(2);
                foreach (DictionaryEntry pair in dictionary)
                {
                    if (pair.Key == null) throw Fail(owner, field, "a dictionary entry has a null key");
                    var item = Create(fd.MessageType);
                    keyField.Accessor.SetValue(item, Value(keyField, pair.Key, owner, field));
                    // A null message value is the entry's unset value field.
                    if (pair.Value != null) valueField.Accessor.SetValue(item, Value(valueField, pair.Value, owner, field));
                    else if (valueField.FieldType != FieldType.Message) throw Fail(owner, field, "a dictionary entry has a null scalar value");
                    target.Add(item);
                }
                return;
            }
            if (entry || collection is string || !(collection is IEnumerable items))
                throw Fail(owner, field, $"{collection.GetType().FullName} is not a collection of the repeated field");
            var optional = fd.FieldType == FieldType.Message && Synthetic(fd.MessageType) == "optional";
            foreach (var item in items)
            {
                if (item == null && !optional) throw Fail(owner, field, "a collection element is null");
                // A null class element keeps its index (ThoughtDef.stages leaves a null
                // for a stage no thought uses): its wrapper's value stays unset.
                target.Add(item == null ? Create(fd.MessageType) : Value(fd, item, owner, field));
            }
        }

        // value as the CLR-side value fd's accessor takes.
        private object Value(FieldDescriptor fd, object value, string owner, string field)
        {
            switch (fd.FieldType)
            {
                case FieldType.Bool: return (bool)value;
                case FieldType.Int32: case FieldType.SInt32: case FieldType.SFixed32: return Convert.ToInt32(value);
                case FieldType.UInt32: case FieldType.Fixed32: return Convert.ToUInt32(value);
                case FieldType.Int64: case FieldType.SInt64: case FieldType.SFixed64: return Convert.ToInt64(value);
                case FieldType.UInt64: case FieldType.Fixed64: return Convert.ToUInt64(value);
                case FieldType.Float: return Convert.ToSingle(value);
                case FieldType.Double: return Convert.ToDouble(value);
                case FieldType.String:
                    if (value is string text) return text;
                    if (value is Type type)
                    {
                        typeValues.Add(type);
                        return type.FullName ?? throw Fail(owner, field, $"type {type} has no full name");
                    }
                    if (value is Verse.Def def) return def.defName ?? "";
                    // SlateRef<T> is the XML text of the field: its one private string.
                    if (value.GetType() is { IsGenericType: true } generic && generic.GetGenericTypeDefinition() == typeof(RimWorld.QuestGen.SlateRef<>))
                        return (generic.GetField("slateRef", BindingFlags.Instance | BindingFlags.NonPublic)
                            ?? throw Fail(owner, field, $"{generic.FullName} has no slateRef field")).GetValue(value) as string ?? "";
                    throw Fail(owner, field, $"{value.GetType().FullName} is not a string, Type or def");
                // A uint enum member above int32 max is its two's-complement int32 (defs.proto).
                case FieldType.Enum: return Enum.ToObject(fd.EnumType.ClrType, unchecked((int)Convert.ToInt64(value)));
                case FieldType.Message: return MessageOf(fd.MessageType, value, owner, field);
                default: throw Fail(owner, field, $"field type {fd.FieldType} is not mapped");
            }
        }

        private IMessage MessageOf(MessageDescriptor descriptor, object value, string owner, string field)
        {
            var synthetic = Synthetic(descriptor);
            if (synthetic == "list")
            {
                var wrapper = Create(descriptor);
                var items = descriptor.FindFieldByName("items");
                AddAll((IList)items.Accessor.GetValue(wrapper), items, value, owner, field);
                return wrapper;
            }
            if (synthetic == "optional")
            {
                var wrapper = Create(descriptor);
                var slot = descriptor.FindFieldByName("value");
                slot.Accessor.SetValue(wrapper, Value(slot, value, owner, field));
                return wrapper;
            }
            if (synthetic != null) throw Fail(owner, field, $"synthetic {synthetic} message {descriptor.Name} outside a dictionary");
            if (Clr(descriptor) == null)
            {
                var armsByClr = ArmsOf(descriptor, owner, field);
                var actual = value.GetType().FullName ?? "";
                if (!armsByClr.TryGetValue(actual, out var arm)) throw Fail(owner, field, $"{actual} is not a class mirrored by {descriptor.Name}");
                var any = Create(descriptor);
                var inner = Create(arm.MessageType);
                Fill(inner, value, owner, field);
                arm.Accessor.SetValue(any, inner);
                return any;
            }
            var message = Create(descriptor);
            Fill(message, value, owner, field);
            return message;
        }

        // A "<Class>Any" wrapper's oneof arms by the CLR class each mirrors.
        private Dictionary<string, FieldDescriptor> ArmsOf(MessageDescriptor descriptor, string owner, string field)
        {
            if (arms.TryGetValue(descriptor, out var found)) return found;
            if (descriptor.Fields.InDeclarationOrder().Any(f => f.ContainingOneof == null || f.FieldType != FieldType.Message))
                throw Fail(owner, field, $"{descriptor.Name} is neither a mirrored class nor a oneof wrapper");
            var byClr = new Dictionary<string, FieldDescriptor>(StringComparer.Ordinal);
            foreach (var arm in descriptor.Fields.InDeclarationOrder())
                byClr[Clr(arm.MessageType) ?? throw Fail(owner, field, $"arm {arm.MessageType.Name} has no clr_type option")] = arm;
            return arms[descriptor] = byClr;
        }
    }
}
