#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Google.Protobuf;
using Google.Protobuf.Reflection;
using Defs = RimGovernor.Protocol.Defs;

namespace HomeBridge.BridgeTools
{
    // Fills the messages of defs.proto (generated by tools/defmirror) from the
    // game's def objects by protobuf reflection, with no per-class code. The
    // mapping is the generator's contract (contracts/schema-generation.md):
    //   * a message mirrors the CLR class named by its clr_type option, and a
    //     field's name is the CLR field's name;
    //   * a def reference is the def's defName, a System.Type its full name, an
    //     enum its numeric value, a Nullable<T> an optional field, a SlateRef<T>
    //     its XML text;
    //   * a List, array or HashSet is a repeated field, a Dictionary repeated
    //     "entry" messages (key, value), a nested collection a "list" message
    //     (items);
    //   * a class with subclasses is a "<Class>Any" message whose oneof arm is
    //     chosen by the value's exact type.
    // A value the mirror cannot hold (a null collection element, a type without
    // an arm such as a mod's CompProperties subclass, a missing CLR field) throws
    // naming Class.field; nothing is skipped. A null reference leaves its field
    // unset. One instance serves one read on one thread: it caches per descriptor.
    internal sealed class DefMirrorFill
    {
        private sealed class Plan
        {
            internal string Clr = "";
            internal Type Type = typeof(object);
            internal FieldDescriptor[] Fields = Array.Empty<FieldDescriptor>();
            internal FieldInfo[] Infos = Array.Empty<FieldInfo>();
        }

        private readonly Dictionary<MessageDescriptor, Plan> plans = new Dictionary<MessageDescriptor, Plan>();
        private readonly Dictionary<MessageDescriptor, Dictionary<string, FieldDescriptor>> arms = new Dictionary<MessageDescriptor, Dictionary<string, FieldDescriptor>>();

        // The message mirroring source, filled.
        internal T Build<T>(object source) where T : IMessage, new()
        {
            var message = new T();
            Fill(message, source, message.Descriptor.Name, "(root)");
            return message;
        }

        // The message of descriptor mirroring source.
        internal IMessage Build(MessageDescriptor descriptor, object source)
        {
            var message = Create(descriptor);
            Fill(message, source, descriptor.Name, "(root)");
            return message;
        }

        // The CLR class a message mirrors, null for a wrapper or synthetic message.
        internal string? ClrName(MessageDescriptor descriptor) => Clr(descriptor);

        private readonly Dictionary<MessageDescriptor, (string? Clr, string? Synthetic)> options = new Dictionary<MessageDescriptor, (string?, string?)>();

        private (string? Clr, string? Synthetic) OptionsOf(MessageDescriptor descriptor)
        {
            if (options.TryGetValue(descriptor, out var found)) return found;
            var raw = descriptor.GetOptions();
            return options[descriptor] = (
                raw != null && raw.HasExtension(Defs.DefsExtensions.ClrType) ? raw.GetExtension(Defs.DefsExtensions.ClrType) : null,
                raw != null && raw.HasExtension(Defs.DefsExtensions.ClrSynthetic) ? raw.GetExtension(Defs.DefsExtensions.ClrSynthetic) : null);
        }

        private string? Clr(MessageDescriptor descriptor) => OptionsOf(descriptor).Clr;

        private string? Synthetic(MessageDescriptor descriptor) => OptionsOf(descriptor).Synthetic;

        private static Exception Fail(string owner, string field, string reason) => new InvalidOperationException($"{owner}.{field}: {reason}");

        private static IMessage Create(MessageDescriptor descriptor) => (IMessage)Activator.CreateInstance(descriptor.ClrType)!;

        private Plan PlanOf(MessageDescriptor descriptor, object source, string owner, string field)
        {
            if (plans.TryGetValue(descriptor, out var plan))
            {
                if (plan.Type != source.GetType())
                    throw Fail(owner, field, $"{source.GetType().FullName} is not the mirrored class {plan.Clr} of {descriptor.Name}");
                return plan;
            }
            var clr = Clr(descriptor);
            if (clr == null) throw Fail(owner, field, $"{descriptor.Name} has no clr_type option");
            var type = source.GetType();
            if (type.FullName != clr) throw Fail(owner, field, $"{type.FullName} is not the mirrored class {clr} of {descriptor.Name}");
            var fields = descriptor.Fields.InFieldNumberOrder().ToArray();
            var infos = new FieldInfo[fields.Length];
            for (var i = 0; i < fields.Length; i++)
            {
                FieldInfo? found = null;
                for (var t = type; t != null && found == null; t = t.BaseType)
                    found = t.GetField(fields[i].Name, BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
                infos[i] = found ?? throw Fail(clr, fields[i].Name, "no such public instance field");
            }
            return plans[descriptor] = new Plan { Clr = clr, Type = type, Fields = fields, Infos = infos };
        }

        private void Fill(IMessage message, object source, string owner, string field)
        {
            var plan = PlanOf(message.Descriptor, source, owner, field);
            for (var i = 0; i < plan.Fields.Length; i++)
            {
                var fd = plan.Fields[i];
                var value = plan.Infos[i].GetValue(source);
                if (value == null) continue;
                if (fd.IsRepeated) AddAll((IList)fd.Accessor.GetValue(message), fd, value, plan.Clr, fd.Name);
                else fd.Accessor.SetValue(message, Value(fd, value, plan.Clr, fd.Name));
            }
        }

        private void AddAll(IList target, FieldDescriptor fd, object collection, string owner, string field)
        {
            var entry = fd.FieldType == FieldType.Message && Synthetic(fd.MessageType) == "entry";
            if (collection is IDictionary dictionary)
            {
                if (!entry) throw Fail(owner, field, $"a dictionary {collection.GetType().FullName} in a field that is not a key/value entry list");
                var keyField = fd.MessageType.FindFieldByNumber(1);
                var valueField = fd.MessageType.FindFieldByNumber(2);
                foreach (DictionaryEntry pair in dictionary)
                {
                    if (pair.Key == null || pair.Value == null) throw Fail(owner, field, "a dictionary entry has a null key or value");
                    var item = Create(fd.MessageType);
                    keyField.Accessor.SetValue(item, Value(keyField, pair.Key, owner, field));
                    valueField.Accessor.SetValue(item, Value(valueField, pair.Value, owner, field));
                    target.Add(item);
                }
                return;
            }
            if (entry || collection is string || !(collection is IEnumerable items))
                throw Fail(owner, field, $"{collection.GetType().FullName} is not a collection of the repeated field");
            foreach (var item in items)
            {
                // A null message element holds its index (ThoughtDef.stages leaves a
                // null for a stage no thought uses), so it mirrors as an empty message.
                if (item == null)
                {
                    if (fd.FieldType != FieldType.Message) throw Fail(owner, field, "a collection element is null");
                    target.Add(Create(fd.MessageType));
                    continue;
                }
                target.Add(Value(fd, item, owner, field));
            }
        }

        // value as the CLR-side value fd's accessor takes.
        private object Value(FieldDescriptor fd, object value, string owner, string field)
        {
            switch (fd.FieldType)
            {
                case FieldType.Bool: return (bool)value;
                case FieldType.Int32: case FieldType.SInt32: case FieldType.SFixed32: return Convert.ToInt32(value);
                case FieldType.UInt32: case FieldType.Fixed32: return Convert.ToUInt32(value);
                case FieldType.Int64: case FieldType.SInt64: case FieldType.SFixed64: return Convert.ToInt64(value);
                case FieldType.UInt64: case FieldType.Fixed64: return Convert.ToUInt64(value);
                case FieldType.Float: return Convert.ToSingle(value);
                case FieldType.Double: return Convert.ToDouble(value);
                case FieldType.String:
                    if (value is string text) return text;
                    if (value is Type type) return type.FullName ?? throw Fail(owner, field, $"type {type} has no full name");
                    if (value is Verse.Def def) return def.defName ?? "";
                    // SlateRef<T> is the XML text of the field: its one private string.
                    if (value.GetType() is { IsGenericType: true } generic && generic.GetGenericTypeDefinition() == typeof(RimWorld.QuestGen.SlateRef<>))
                        return (generic.GetField("slateRef", BindingFlags.Instance | BindingFlags.NonPublic)
                            ?? throw Fail(owner, field, $"{generic.FullName} has no slateRef field")).GetValue(value) as string ?? "";
                    throw Fail(owner, field, $"{value.GetType().FullName} is not a string, Type or def");
                case FieldType.Enum: return Enum.ToObject(fd.EnumType.ClrType, Convert.ToInt32(value));
                case FieldType.Message: return MessageOf(fd.MessageType, value, owner, field);
                default: throw Fail(owner, field, $"field type {fd.FieldType} is not mapped");
            }
        }

        private IMessage MessageOf(MessageDescriptor descriptor, object value, string owner, string field)
        {
            var synthetic = Synthetic(descriptor);
            if (synthetic == "list")
            {
                var wrapper = Create(descriptor);
                var items = descriptor.FindFieldByName("items");
                AddAll((IList)items.Accessor.GetValue(wrapper), items, value, owner, field);
                return wrapper;
            }
            if (synthetic != null) throw Fail(owner, field, $"synthetic {synthetic} message {descriptor.Name} outside a dictionary");
            if (Clr(descriptor) == null)
            {
                var armsByClr = ArmsOf(descriptor, owner, field);
                var actual = value.GetType().FullName ?? "";
                if (!armsByClr.TryGetValue(actual, out var arm)) throw Fail(owner, field, $"{actual} is not a class mirrored by {descriptor.Name}");
                var any = Create(descriptor);
                var inner = Create(arm.MessageType);
                Fill(inner, value, owner, field);
                arm.Accessor.SetValue(any, inner);
                return any;
            }
            var message = Create(descriptor);
            Fill(message, value, owner, field);
            return message;
        }

        // A "<Class>Any" wrapper's oneof arms by the CLR class each mirrors.
        private Dictionary<string, FieldDescriptor> ArmsOf(MessageDescriptor descriptor, string owner, string field)
        {
            if (arms.TryGetValue(descriptor, out var found)) return found;
            if (descriptor.Fields.InDeclarationOrder().Any(f => f.ContainingOneof == null || f.FieldType != FieldType.Message))
                throw Fail(owner, field, $"{descriptor.Name} is neither a mirrored class nor a oneof wrapper");
            var byClr = new Dictionary<string, FieldDescriptor>(StringComparer.Ordinal);
            foreach (var arm in descriptor.Fields.InDeclarationOrder())
                byClr[Clr(arm.MessageType) ?? throw Fail(owner, field, $"arm {arm.MessageType.Name} has no clr_type option")] = arm;
            return arms[descriptor] = byClr;
        }
    }
}
