// Code generated by contractgen format 1; DO NOT EDIT.
// Source: contracts/schemas/guarded-placement.v1.schema.json
// SHA256: 0e36cbafef94d36a91aa56dbb2bc066c3c6ac749608f8e2a474a3bc48874836d
package guardedplacement

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"unicode/utf8"
)

type GuardTransportArguments struct {
	Request string `json:"request"`
}

// DecodeGuardTransportArguments rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardTransportArguments(data []byte) (GuardTransportArguments, error) {
	var zero GuardTransportArguments
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue0(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardAcquireRequest struct {
	ControllerSessionId string        `json:"controllerSessionId"`
	ExpectedGeneration  string        `json:"expectedGeneration"`
	Identity            GuardIdentity `json:"identity"`
	LeaseMs             int32         `json:"leaseMs"`
	Operation           string        `json:"operation"`
	PlayerDirection     string        `json:"playerDirection"`
}

// DecodeGuardAcquireRequest rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardAcquireRequest(data []byte) (GuardAcquireRequest, error) {
	var zero GuardAcquireRequest
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue2(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardAttemptReply struct {
	GuardAttemptSuccess *GuardAttemptSuccess `json:"-"`
	GuardFailure        *GuardFailure        `json:"-"`
}

func (v GuardAttemptReply) MarshalJSON() ([]byte, error) {
	var data []byte
	var err error
	count := 0
	if v.GuardAttemptSuccess != nil {
		count++
		data, err = json.Marshal(v.GuardAttemptSuccess)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardAttemptSuccess(data); err != nil {
			return nil, err
		}
	}
	if v.GuardFailure != nil {
		count++
		data, err = json.Marshal(v.GuardFailure)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardFailure(data); err != nil {
			return nil, err
		}
	}
	if count != 1 {
		return nil, fmt.Errorf("exactly one variant branch required")
	}
	return data, nil
}

// DecodeGuardAttemptReply rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardAttemptReply(data []byte) (GuardAttemptReply, error) {
	var zero GuardAttemptReply
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue13(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardAttemptRequest struct {
	ActionId            string        `json:"actionId"`
	AttemptId           string        `json:"attemptId"`
	ControllerSessionId string        `json:"controllerSessionId"`
	Identity            GuardIdentity `json:"identity"`
}

// DecodeGuardAttemptRequest rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardAttemptRequest(data []byte) (GuardAttemptRequest, error) {
	var zero GuardAttemptRequest
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue54(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardAttemptSuccess struct {
	Identity GuardIdentity  `json:"identity"`
	Records  []GuardReceipt `json:"records"`
	Success  bool           `json:"success"`
}

// DecodeGuardAttemptSuccess rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardAttemptSuccess(data []byte) (GuardAttemptSuccess, error) {
	var zero GuardAttemptSuccess
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue15(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardAuthorityGranted struct {
	Active           bool          `json:"active"`
	Available        bool          `json:"available"`
	Identity         GuardIdentity `json:"identity"`
	LeaseId          string        `json:"leaseId"`
	NativeGeneration string        `json:"nativeGeneration"`
	Owners           []GuardOwner  `json:"owners"`
	RemainingLeaseMs int32         `json:"remainingLeaseMs"`
	RevocationReason string        `json:"revocationReason"`
	Success          bool          `json:"success"`
}

// DecodeGuardAuthorityGranted rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardAuthorityGranted(data []byte) (GuardAuthorityGranted, error) {
	var zero GuardAuthorityGranted
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue59(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardAuthorityStatus struct {
	Active           bool          `json:"active"`
	Available        bool          `json:"available"`
	Identity         GuardIdentity `json:"identity"`
	NativeGeneration string        `json:"nativeGeneration"`
	Owners           []GuardOwner  `json:"owners"`
	RemainingLeaseMs int32         `json:"remainingLeaseMs"`
	RevocationReason string        `json:"revocationReason"`
	Success          bool          `json:"success"`
}

// DecodeGuardAuthorityStatus rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardAuthorityStatus(data []byte) (GuardAuthorityStatus, error) {
	var zero GuardAuthorityStatus
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue73(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardEffect struct {
	ConstructionOrigin string `json:"constructionOrigin"`
	DefName            string `json:"defName"`
	Rotation           string `json:"rotation"`
	Stage              string `json:"stage"`
	Stuff              string `json:"stuff"`
	ThingId            string `json:"thingId"`
	X                  int32  `json:"x"`
	Z                  int32  `json:"z"`
}

// DecodeGuardEffect rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardEffect(data []byte) (GuardEffect, error) {
	var zero GuardEffect
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue26(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardFailure struct {
	Detail    string `json:"detail"`
	ErrorCode string `json:"errorCode"`
	Success   bool   `json:"success"`
}

// DecodeGuardFailure rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardFailure(data []byte) (GuardFailure, error) {
	var zero GuardFailure
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue50(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardGrantedReply struct {
	GuardAuthorityGranted *GuardAuthorityGranted `json:"-"`
	GuardFailure          *GuardFailure          `json:"-"`
}

func (v GuardGrantedReply) MarshalJSON() ([]byte, error) {
	var data []byte
	var err error
	count := 0
	if v.GuardAuthorityGranted != nil {
		count++
		data, err = json.Marshal(v.GuardAuthorityGranted)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardAuthorityGranted(data); err != nil {
			return nil, err
		}
	}
	if v.GuardFailure != nil {
		count++
		data, err = json.Marshal(v.GuardFailure)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardFailure(data); err != nil {
			return nil, err
		}
	}
	if count != 1 {
		return nil, fmt.Errorf("exactly one variant branch required")
	}
	return data, nil
}

// DecodeGuardGrantedReply rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardGrantedReply(data []byte) (GuardGrantedReply, error) {
	var zero GuardGrantedReply
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue83(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardIdentity struct {
	ColonyId  string `json:"colonyId"`
	LoadToken string `json:"loadToken"`
	MapId     int32  `json:"mapId"`
}

// DecodeGuardIdentity rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardIdentity(data []byte) (GuardIdentity, error) {
	var zero GuardIdentity
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue6(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardOwner struct {
	ControllerSessionId string `json:"controllerSessionId"`
	PlayerDirection     string `json:"playerDirection"`
}

// DecodeGuardOwner rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardOwner(data []byte) (GuardOwner, error) {
	var zero GuardOwner
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue67(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardPlacement struct {
	DefName  string `json:"defName"`
	Rotation string `json:"rotation"`
	Stuff    string `json:"stuff"`
	X        int32  `json:"x"`
	Z        int32  `json:"z"`
}

// DecodeGuardPlacement rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardPlacement(data []byte) (GuardPlacement, error) {
	var zero GuardPlacement
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue39(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardPlacementReply struct {
	GuardPlacementSuccess *GuardPlacementSuccess `json:"-"`
	GuardFailure          *GuardFailure          `json:"-"`
}

func (v GuardPlacementReply) MarshalJSON() ([]byte, error) {
	var data []byte
	var err error
	count := 0
	if v.GuardPlacementSuccess != nil {
		count++
		data, err = json.Marshal(v.GuardPlacementSuccess)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardPlacementSuccess(data); err != nil {
			return nil, err
		}
	}
	if v.GuardFailure != nil {
		count++
		data, err = json.Marshal(v.GuardFailure)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardFailure(data); err != nil {
			return nil, err
		}
	}
	if count != 1 {
		return nil, fmt.Errorf("exactly one variant branch required")
	}
	return data, nil
}

// DecodeGuardPlacementReply rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardPlacementReply(data []byte) (GuardPlacementReply, error) {
	var zero GuardPlacementReply
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue86(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardPlacementRequest struct {
	ActionId            string         `json:"actionId"`
	AttemptId           string         `json:"attemptId"`
	ControllerSessionId string         `json:"controllerSessionId"`
	ExpectedGeneration  string         `json:"expectedGeneration"`
	Identity            GuardIdentity  `json:"identity"`
	LeaseId             string         `json:"leaseId"`
	Placement           GuardPlacement `json:"placement"`
}

// DecodeGuardPlacementRequest rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardPlacementRequest(data []byte) (GuardPlacementRequest, error) {
	var zero GuardPlacementRequest
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue93(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardPlacementSuccess struct {
	Receipt  GuardReceipt `json:"receipt"`
	Replayed bool         `json:"replayed"`
	Success  bool         `json:"success"`
}

// DecodeGuardPlacementSuccess rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardPlacementSuccess(data []byte) (GuardPlacementSuccess, error) {
	var zero GuardPlacementSuccess
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue88(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardReceipt struct {
	ActionId            string         `json:"actionId"`
	AttemptId           string         `json:"attemptId"`
	ControllerSessionId string         `json:"controllerSessionId"`
	Detail              string         `json:"detail"`
	Effects             []GuardEffect  `json:"effects"`
	Identity            GuardIdentity  `json:"identity"`
	NativeGeneration    string         `json:"nativeGeneration"`
	Outcome             string         `json:"outcome"`
	Placement           GuardPlacement `json:"placement"`
	PlayerDirection     string         `json:"playerDirection"`
	ReasonCode          string         `json:"reasonCode"`
	Tick                int32          `json:"tick"`
}

// DecodeGuardReceipt rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardReceipt(data []byte) (GuardReceipt, error) {
	var zero GuardReceipt
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue19(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardRenewRequest struct {
	ControllerSessionId string        `json:"controllerSessionId"`
	ExpectedGeneration  string        `json:"expectedGeneration"`
	Identity            GuardIdentity `json:"identity"`
	LeaseId             string        `json:"leaseId"`
	LeaseMs             int32         `json:"leaseMs"`
	Operation           string        `json:"operation"`
}

// DecodeGuardRenewRequest rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardRenewRequest(data []byte) (GuardRenewRequest, error) {
	var zero GuardRenewRequest
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue101(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardRevokeRequest struct {
	ExpectedGeneration string        `json:"expectedGeneration"`
	Identity           GuardIdentity `json:"identity"`
	Operation          string        `json:"operation"`
	Reason             string        `json:"reason"`
}

// DecodeGuardRevokeRequest rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardRevokeRequest(data []byte) (GuardRevokeRequest, error) {
	var zero GuardRevokeRequest
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue108(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardStatusReply struct {
	GuardAuthorityStatus *GuardAuthorityStatus `json:"-"`
	GuardFailure         *GuardFailure         `json:"-"`
}

func (v GuardStatusReply) MarshalJSON() ([]byte, error) {
	var data []byte
	var err error
	count := 0
	if v.GuardAuthorityStatus != nil {
		count++
		data, err = json.Marshal(v.GuardAuthorityStatus)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardAuthorityStatus(data); err != nil {
			return nil, err
		}
	}
	if v.GuardFailure != nil {
		count++
		data, err = json.Marshal(v.GuardFailure)
		if err != nil {
			return nil, err
		}
		if _, err = DecodeGuardFailure(data); err != nil {
			return nil, err
		}
	}
	if count != 1 {
		return nil, fmt.Errorf("exactly one variant branch required")
	}
	return data, nil
}

// DecodeGuardStatusReply rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardStatusReply(data []byte) (GuardStatusReply, error) {
	var zero GuardStatusReply
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue113(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type GuardStatusRequest struct {
	Identity GuardIdentity `json:"identity"`
}

// DecodeGuardStatusRequest rejects missing/null/unknown/duplicate fields and malformed values.
func DecodeGuardStatusRequest(data []byte) (GuardStatusRequest, error) {
	var zero GuardStatusRequest
	d, err := guardTransportArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := guardTransportArgumentsDecodeValue116(d)
	if err != nil {
		return zero, err
	}
	if err = guardTransportArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

func guardTransportArgumentsDecodeValue0(d *json.Decoder) (GuardTransportArguments, error) {
	var result GuardTransportArguments
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "request":
			value, err := guardTransportArgumentsDecodeValue1(d)
			if err != nil {
				return result, fmt.Errorf("request: %w", err)
			}
			result.Request = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["request"] {
		return result, fmt.Errorf("missing required field: request")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue1(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 16384, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue2(d *json.Decoder) (GuardAcquireRequest, error) {
	var result GuardAcquireRequest
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "controllerSessionId":
			value, err := guardTransportArgumentsDecodeValue3(d)
			if err != nil {
				return result, fmt.Errorf("controllerSessionId: %w", err)
			}
			result.ControllerSessionId = value
		case "expectedGeneration":
			value, err := guardTransportArgumentsDecodeValue4(d)
			if err != nil {
				return result, fmt.Errorf("expectedGeneration: %w", err)
			}
			result.ExpectedGeneration = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue5(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "leaseMs":
			value, err := guardTransportArgumentsDecodeValue10(d)
			if err != nil {
				return result, fmt.Errorf("leaseMs: %w", err)
			}
			result.LeaseMs = value
		case "operation":
			value, err := guardTransportArgumentsDecodeValue11(d)
			if err != nil {
				return result, fmt.Errorf("operation: %w", err)
			}
			result.Operation = value
		case "playerDirection":
			value, err := guardTransportArgumentsDecodeValue12(d)
			if err != nil {
				return result, fmt.Errorf("playerDirection: %w", err)
			}
			result.PlayerDirection = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["controllerSessionId"] {
		return result, fmt.Errorf("missing required field: controllerSessionId")
	}
	if !seen["expectedGeneration"] {
		return result, fmt.Errorf("missing required field: expectedGeneration")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["leaseMs"] {
		return result, fmt.Errorf("missing required field: leaseMs")
	}
	if !seen["operation"] {
		return result, fmt.Errorf("missing required field: operation")
	}
	if !seen["playerDirection"] {
		return result, fmt.Errorf("missing required field: playerDirection")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue3(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue4(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue5(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue6(d *json.Decoder) (GuardIdentity, error) {
	var result GuardIdentity
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "colonyId":
			value, err := guardTransportArgumentsDecodeValue7(d)
			if err != nil {
				return result, fmt.Errorf("colonyId: %w", err)
			}
			result.ColonyId = value
		case "loadToken":
			value, err := guardTransportArgumentsDecodeValue8(d)
			if err != nil {
				return result, fmt.Errorf("loadToken: %w", err)
			}
			result.LoadToken = value
		case "mapId":
			value, err := guardTransportArgumentsDecodeValue9(d)
			if err != nil {
				return result, fmt.Errorf("mapId: %w", err)
			}
			result.MapId = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["colonyId"] {
		return result, fmt.Errorf("missing required field: colonyId")
	}
	if !seen["loadToken"] {
		return result, fmt.Errorf("missing required field: loadToken")
	}
	if !seen["mapId"] {
		return result, fmt.Errorf("missing required field: mapId")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue7(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue8(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue9(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, 0, 2147483647)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue10(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, 1000, 30000)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue11(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 7, false)
	if err == nil {
		switch value {
		case "acquire":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue12(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue13(d *json.Decoder) (GuardAttemptReply, error) {
	var zero GuardAttemptReply
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return zero, err
	}
	if v, err := DecodeGuardAttemptSuccess(raw); err == nil {
		return GuardAttemptReply{GuardAttemptSuccess: &v}, nil
	}
	if v, err := DecodeGuardFailure(raw); err == nil {
		return GuardAttemptReply{GuardFailure: &v}, nil
	}
	return zero, fmt.Errorf("no matching success variant")
}
func guardTransportArgumentsDecodeValue14(d *json.Decoder) (GuardAttemptSuccess, error) {
	v, err := guardTransportArgumentsDecodeValue15(d)
	return GuardAttemptSuccess(v), err
}
func guardTransportArgumentsDecodeValue15(d *json.Decoder) (GuardAttemptSuccess, error) {
	var result GuardAttemptSuccess
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "identity":
			value, err := guardTransportArgumentsDecodeValue16(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "records":
			value, err := guardTransportArgumentsDecodeValue17(d)
			if err != nil {
				return result, fmt.Errorf("records: %w", err)
			}
			result.Records = value
		case "success":
			value, err := guardTransportArgumentsDecodeValue48(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["records"] {
		return result, fmt.Errorf("missing required field: records")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue16(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue17(d *json.Decoder) ([]GuardReceipt, error) {
	result := make([]GuardReceipt, 0)
	if err := guardTransportArgumentsExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 1 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := guardTransportArgumentsDecodeValue18(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := guardTransportArgumentsExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue18(d *json.Decoder) (GuardReceipt, error) {
	v, err := guardTransportArgumentsDecodeValue19(d)
	return GuardReceipt(v), err
}
func guardTransportArgumentsDecodeValue19(d *json.Decoder) (GuardReceipt, error) {
	var result GuardReceipt
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "actionId":
			value, err := guardTransportArgumentsDecodeValue20(d)
			if err != nil {
				return result, fmt.Errorf("actionId: %w", err)
			}
			result.ActionId = value
		case "attemptId":
			value, err := guardTransportArgumentsDecodeValue21(d)
			if err != nil {
				return result, fmt.Errorf("attemptId: %w", err)
			}
			result.AttemptId = value
		case "controllerSessionId":
			value, err := guardTransportArgumentsDecodeValue22(d)
			if err != nil {
				return result, fmt.Errorf("controllerSessionId: %w", err)
			}
			result.ControllerSessionId = value
		case "detail":
			value, err := guardTransportArgumentsDecodeValue23(d)
			if err != nil {
				return result, fmt.Errorf("detail: %w", err)
			}
			result.Detail = value
		case "effects":
			value, err := guardTransportArgumentsDecodeValue24(d)
			if err != nil {
				return result, fmt.Errorf("effects: %w", err)
			}
			result.Effects = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue35(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "nativeGeneration":
			value, err := guardTransportArgumentsDecodeValue36(d)
			if err != nil {
				return result, fmt.Errorf("nativeGeneration: %w", err)
			}
			result.NativeGeneration = value
		case "outcome":
			value, err := guardTransportArgumentsDecodeValue37(d)
			if err != nil {
				return result, fmt.Errorf("outcome: %w", err)
			}
			result.Outcome = value
		case "placement":
			value, err := guardTransportArgumentsDecodeValue38(d)
			if err != nil {
				return result, fmt.Errorf("placement: %w", err)
			}
			result.Placement = value
		case "playerDirection":
			value, err := guardTransportArgumentsDecodeValue45(d)
			if err != nil {
				return result, fmt.Errorf("playerDirection: %w", err)
			}
			result.PlayerDirection = value
		case "reasonCode":
			value, err := guardTransportArgumentsDecodeValue46(d)
			if err != nil {
				return result, fmt.Errorf("reasonCode: %w", err)
			}
			result.ReasonCode = value
		case "tick":
			value, err := guardTransportArgumentsDecodeValue47(d)
			if err != nil {
				return result, fmt.Errorf("tick: %w", err)
			}
			result.Tick = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["actionId"] {
		return result, fmt.Errorf("missing required field: actionId")
	}
	if !seen["attemptId"] {
		return result, fmt.Errorf("missing required field: attemptId")
	}
	if !seen["controllerSessionId"] {
		return result, fmt.Errorf("missing required field: controllerSessionId")
	}
	if !seen["detail"] {
		return result, fmt.Errorf("missing required field: detail")
	}
	if !seen["effects"] {
		return result, fmt.Errorf("missing required field: effects")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["nativeGeneration"] {
		return result, fmt.Errorf("missing required field: nativeGeneration")
	}
	if !seen["outcome"] {
		return result, fmt.Errorf("missing required field: outcome")
	}
	if !seen["placement"] {
		return result, fmt.Errorf("missing required field: placement")
	}
	if !seen["playerDirection"] {
		return result, fmt.Errorf("missing required field: playerDirection")
	}
	if !seen["reasonCode"] {
		return result, fmt.Errorf("missing required field: reasonCode")
	}
	if !seen["tick"] {
		return result, fmt.Errorf("missing required field: tick")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue20(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue21(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue22(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue23(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 4096, false)
	return string(value), err
}

func guardTransportArgumentsDecodeValue24(d *json.Decoder) ([]GuardEffect, error) {
	result := make([]GuardEffect, 0)
	if err := guardTransportArgumentsExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 1 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := guardTransportArgumentsDecodeValue25(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := guardTransportArgumentsExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue25(d *json.Decoder) (GuardEffect, error) {
	v, err := guardTransportArgumentsDecodeValue26(d)
	return GuardEffect(v), err
}
func guardTransportArgumentsDecodeValue26(d *json.Decoder) (GuardEffect, error) {
	var result GuardEffect
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "constructionOrigin":
			value, err := guardTransportArgumentsDecodeValue27(d)
			if err != nil {
				return result, fmt.Errorf("constructionOrigin: %w", err)
			}
			result.ConstructionOrigin = value
		case "defName":
			value, err := guardTransportArgumentsDecodeValue28(d)
			if err != nil {
				return result, fmt.Errorf("defName: %w", err)
			}
			result.DefName = value
		case "rotation":
			value, err := guardTransportArgumentsDecodeValue29(d)
			if err != nil {
				return result, fmt.Errorf("rotation: %w", err)
			}
			result.Rotation = value
		case "stage":
			value, err := guardTransportArgumentsDecodeValue30(d)
			if err != nil {
				return result, fmt.Errorf("stage: %w", err)
			}
			result.Stage = value
		case "stuff":
			value, err := guardTransportArgumentsDecodeValue31(d)
			if err != nil {
				return result, fmt.Errorf("stuff: %w", err)
			}
			result.Stuff = value
		case "thingId":
			value, err := guardTransportArgumentsDecodeValue32(d)
			if err != nil {
				return result, fmt.Errorf("thingId: %w", err)
			}
			result.ThingId = value
		case "x":
			value, err := guardTransportArgumentsDecodeValue33(d)
			if err != nil {
				return result, fmt.Errorf("x: %w", err)
			}
			result.X = value
		case "z":
			value, err := guardTransportArgumentsDecodeValue34(d)
			if err != nil {
				return result, fmt.Errorf("z: %w", err)
			}
			result.Z = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["constructionOrigin"] {
		return result, fmt.Errorf("missing required field: constructionOrigin")
	}
	if !seen["defName"] {
		return result, fmt.Errorf("missing required field: defName")
	}
	if !seen["rotation"] {
		return result, fmt.Errorf("missing required field: rotation")
	}
	if !seen["stage"] {
		return result, fmt.Errorf("missing required field: stage")
	}
	if !seen["stuff"] {
		return result, fmt.Errorf("missing required field: stuff")
	}
	if !seen["thingId"] {
		return result, fmt.Errorf("missing required field: thingId")
	}
	if !seen["x"] {
		return result, fmt.Errorf("missing required field: x")
	}
	if !seen["z"] {
		return result, fmt.Errorf("missing required field: z")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue27(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue28(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 200, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue29(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 5, false)
	if err == nil {
		switch value {
		case "north", "east", "south", "west":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue30(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 9, false)
	if err == nil {
		switch value {
		case "blueprint":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue31(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 200, false)
	return string(value), err
}

func guardTransportArgumentsDecodeValue32(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue33(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue34(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue35(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue36(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue37(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 7, false)
	if err == nil {
		switch value {
		case "applied", "refused", "unknown":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue38(d *json.Decoder) (GuardPlacement, error) {
	v, err := guardTransportArgumentsDecodeValue39(d)
	return GuardPlacement(v), err
}
func guardTransportArgumentsDecodeValue39(d *json.Decoder) (GuardPlacement, error) {
	var result GuardPlacement
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "defName":
			value, err := guardTransportArgumentsDecodeValue40(d)
			if err != nil {
				return result, fmt.Errorf("defName: %w", err)
			}
			result.DefName = value
		case "rotation":
			value, err := guardTransportArgumentsDecodeValue41(d)
			if err != nil {
				return result, fmt.Errorf("rotation: %w", err)
			}
			result.Rotation = value
		case "stuff":
			value, err := guardTransportArgumentsDecodeValue42(d)
			if err != nil {
				return result, fmt.Errorf("stuff: %w", err)
			}
			result.Stuff = value
		case "x":
			value, err := guardTransportArgumentsDecodeValue43(d)
			if err != nil {
				return result, fmt.Errorf("x: %w", err)
			}
			result.X = value
		case "z":
			value, err := guardTransportArgumentsDecodeValue44(d)
			if err != nil {
				return result, fmt.Errorf("z: %w", err)
			}
			result.Z = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["defName"] {
		return result, fmt.Errorf("missing required field: defName")
	}
	if !seen["rotation"] {
		return result, fmt.Errorf("missing required field: rotation")
	}
	if !seen["stuff"] {
		return result, fmt.Errorf("missing required field: stuff")
	}
	if !seen["x"] {
		return result, fmt.Errorf("missing required field: x")
	}
	if !seen["z"] {
		return result, fmt.Errorf("missing required field: z")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue40(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 200, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue41(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 5, false)
	if err == nil {
		switch value {
		case "north", "east", "south", "west":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue42(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 200, false)
	return string(value), err
}

func guardTransportArgumentsDecodeValue43(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue44(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue45(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue46(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 22, false)
	if err == nil {
		switch value {
		case "none", "invalid_definition", "invalid_material", "research_required", "site_refused", "existing_structure", "destructive_change", "facts_unavailable", "native_outcome_unknown":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue47(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, 0, 2147483647)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue48(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	if err == nil && value != true {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func guardTransportArgumentsDecodeValue49(d *json.Decoder) (GuardFailure, error) {
	v, err := guardTransportArgumentsDecodeValue50(d)
	return GuardFailure(v), err
}
func guardTransportArgumentsDecodeValue50(d *json.Decoder) (GuardFailure, error) {
	var result GuardFailure
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "detail":
			value, err := guardTransportArgumentsDecodeValue51(d)
			if err != nil {
				return result, fmt.Errorf("detail: %w", err)
			}
			result.Detail = value
		case "errorCode":
			value, err := guardTransportArgumentsDecodeValue52(d)
			if err != nil {
				return result, fmt.Errorf("errorCode: %w", err)
			}
			result.ErrorCode = value
		case "success":
			value, err := guardTransportArgumentsDecodeValue53(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["detail"] {
		return result, fmt.Errorf("missing required field: detail")
	}
	if !seen["errorCode"] {
		return result, fmt.Errorf("missing required field: errorCode")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue51(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 4096, false)
	return string(value), err
}

func guardTransportArgumentsDecodeValue52(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 18, false)
	if err == nil {
		switch value {
		case "invalid_request", "native_unavailable", "stale_identity", "stale_generation", "authority_required", "lease_expired", "owner_conflict", "attempt_conflict", "capacity_exhausted", "native_failure":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue53(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	if err == nil && value != false {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func guardTransportArgumentsDecodeValue54(d *json.Decoder) (GuardAttemptRequest, error) {
	var result GuardAttemptRequest
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "actionId":
			value, err := guardTransportArgumentsDecodeValue55(d)
			if err != nil {
				return result, fmt.Errorf("actionId: %w", err)
			}
			result.ActionId = value
		case "attemptId":
			value, err := guardTransportArgumentsDecodeValue56(d)
			if err != nil {
				return result, fmt.Errorf("attemptId: %w", err)
			}
			result.AttemptId = value
		case "controllerSessionId":
			value, err := guardTransportArgumentsDecodeValue57(d)
			if err != nil {
				return result, fmt.Errorf("controllerSessionId: %w", err)
			}
			result.ControllerSessionId = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue58(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["actionId"] {
		return result, fmt.Errorf("missing required field: actionId")
	}
	if !seen["attemptId"] {
		return result, fmt.Errorf("missing required field: attemptId")
	}
	if !seen["controllerSessionId"] {
		return result, fmt.Errorf("missing required field: controllerSessionId")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue55(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue56(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue57(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue58(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue59(d *json.Decoder) (GuardAuthorityGranted, error) {
	var result GuardAuthorityGranted
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "active":
			value, err := guardTransportArgumentsDecodeValue60(d)
			if err != nil {
				return result, fmt.Errorf("active: %w", err)
			}
			result.Active = value
		case "available":
			value, err := guardTransportArgumentsDecodeValue61(d)
			if err != nil {
				return result, fmt.Errorf("available: %w", err)
			}
			result.Available = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue62(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "leaseId":
			value, err := guardTransportArgumentsDecodeValue63(d)
			if err != nil {
				return result, fmt.Errorf("leaseId: %w", err)
			}
			result.LeaseId = value
		case "nativeGeneration":
			value, err := guardTransportArgumentsDecodeValue64(d)
			if err != nil {
				return result, fmt.Errorf("nativeGeneration: %w", err)
			}
			result.NativeGeneration = value
		case "owners":
			value, err := guardTransportArgumentsDecodeValue65(d)
			if err != nil {
				return result, fmt.Errorf("owners: %w", err)
			}
			result.Owners = value
		case "remainingLeaseMs":
			value, err := guardTransportArgumentsDecodeValue70(d)
			if err != nil {
				return result, fmt.Errorf("remainingLeaseMs: %w", err)
			}
			result.RemainingLeaseMs = value
		case "revocationReason":
			value, err := guardTransportArgumentsDecodeValue71(d)
			if err != nil {
				return result, fmt.Errorf("revocationReason: %w", err)
			}
			result.RevocationReason = value
		case "success":
			value, err := guardTransportArgumentsDecodeValue72(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["active"] {
		return result, fmt.Errorf("missing required field: active")
	}
	if !seen["available"] {
		return result, fmt.Errorf("missing required field: available")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["leaseId"] {
		return result, fmt.Errorf("missing required field: leaseId")
	}
	if !seen["nativeGeneration"] {
		return result, fmt.Errorf("missing required field: nativeGeneration")
	}
	if !seen["owners"] {
		return result, fmt.Errorf("missing required field: owners")
	}
	if !seen["remainingLeaseMs"] {
		return result, fmt.Errorf("missing required field: remainingLeaseMs")
	}
	if !seen["revocationReason"] {
		return result, fmt.Errorf("missing required field: revocationReason")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue60(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	return bool(value), err
}

func guardTransportArgumentsDecodeValue61(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	return bool(value), err
}

func guardTransportArgumentsDecodeValue62(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue63(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue64(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue65(d *json.Decoder) ([]GuardOwner, error) {
	result := make([]GuardOwner, 0)
	if err := guardTransportArgumentsExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 1 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := guardTransportArgumentsDecodeValue66(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := guardTransportArgumentsExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue66(d *json.Decoder) (GuardOwner, error) {
	v, err := guardTransportArgumentsDecodeValue67(d)
	return GuardOwner(v), err
}
func guardTransportArgumentsDecodeValue67(d *json.Decoder) (GuardOwner, error) {
	var result GuardOwner
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "controllerSessionId":
			value, err := guardTransportArgumentsDecodeValue68(d)
			if err != nil {
				return result, fmt.Errorf("controllerSessionId: %w", err)
			}
			result.ControllerSessionId = value
		case "playerDirection":
			value, err := guardTransportArgumentsDecodeValue69(d)
			if err != nil {
				return result, fmt.Errorf("playerDirection: %w", err)
			}
			result.PlayerDirection = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["controllerSessionId"] {
		return result, fmt.Errorf("missing required field: controllerSessionId")
	}
	if !seen["playerDirection"] {
		return result, fmt.Errorf("missing required field: playerDirection")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue68(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue69(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue70(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, 0, 30000)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue71(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, false)
	if err == nil {
		switch value {
		case "none", "manual", "player_direction", "external_order", "player_control", "lease_expired", "identity_changed", "disconnect", "shutdown", "hooks_unavailable", "generation_exhausted":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue72(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	if err == nil && value != true {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func guardTransportArgumentsDecodeValue73(d *json.Decoder) (GuardAuthorityStatus, error) {
	var result GuardAuthorityStatus
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "active":
			value, err := guardTransportArgumentsDecodeValue74(d)
			if err != nil {
				return result, fmt.Errorf("active: %w", err)
			}
			result.Active = value
		case "available":
			value, err := guardTransportArgumentsDecodeValue75(d)
			if err != nil {
				return result, fmt.Errorf("available: %w", err)
			}
			result.Available = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue76(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "nativeGeneration":
			value, err := guardTransportArgumentsDecodeValue77(d)
			if err != nil {
				return result, fmt.Errorf("nativeGeneration: %w", err)
			}
			result.NativeGeneration = value
		case "owners":
			value, err := guardTransportArgumentsDecodeValue78(d)
			if err != nil {
				return result, fmt.Errorf("owners: %w", err)
			}
			result.Owners = value
		case "remainingLeaseMs":
			value, err := guardTransportArgumentsDecodeValue80(d)
			if err != nil {
				return result, fmt.Errorf("remainingLeaseMs: %w", err)
			}
			result.RemainingLeaseMs = value
		case "revocationReason":
			value, err := guardTransportArgumentsDecodeValue81(d)
			if err != nil {
				return result, fmt.Errorf("revocationReason: %w", err)
			}
			result.RevocationReason = value
		case "success":
			value, err := guardTransportArgumentsDecodeValue82(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["active"] {
		return result, fmt.Errorf("missing required field: active")
	}
	if !seen["available"] {
		return result, fmt.Errorf("missing required field: available")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["nativeGeneration"] {
		return result, fmt.Errorf("missing required field: nativeGeneration")
	}
	if !seen["owners"] {
		return result, fmt.Errorf("missing required field: owners")
	}
	if !seen["remainingLeaseMs"] {
		return result, fmt.Errorf("missing required field: remainingLeaseMs")
	}
	if !seen["revocationReason"] {
		return result, fmt.Errorf("missing required field: revocationReason")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue74(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	return bool(value), err
}

func guardTransportArgumentsDecodeValue75(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	return bool(value), err
}

func guardTransportArgumentsDecodeValue76(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue77(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue78(d *json.Decoder) ([]GuardOwner, error) {
	result := make([]GuardOwner, 0)
	if err := guardTransportArgumentsExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 1 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := guardTransportArgumentsDecodeValue79(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := guardTransportArgumentsExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue79(d *json.Decoder) (GuardOwner, error) {
	v, err := guardTransportArgumentsDecodeValue67(d)
	return GuardOwner(v), err
}
func guardTransportArgumentsDecodeValue80(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, 0, 30000)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue81(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, false)
	if err == nil {
		switch value {
		case "none", "manual", "player_direction", "external_order", "player_control", "lease_expired", "identity_changed", "disconnect", "shutdown", "hooks_unavailable", "generation_exhausted":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue82(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	if err == nil && value != true {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func guardTransportArgumentsDecodeValue83(d *json.Decoder) (GuardGrantedReply, error) {
	var zero GuardGrantedReply
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return zero, err
	}
	if v, err := DecodeGuardAuthorityGranted(raw); err == nil {
		return GuardGrantedReply{GuardAuthorityGranted: &v}, nil
	}
	if v, err := DecodeGuardFailure(raw); err == nil {
		return GuardGrantedReply{GuardFailure: &v}, nil
	}
	return zero, fmt.Errorf("no matching success variant")
}
func guardTransportArgumentsDecodeValue84(d *json.Decoder) (GuardAuthorityGranted, error) {
	v, err := guardTransportArgumentsDecodeValue59(d)
	return GuardAuthorityGranted(v), err
}
func guardTransportArgumentsDecodeValue85(d *json.Decoder) (GuardFailure, error) {
	v, err := guardTransportArgumentsDecodeValue50(d)
	return GuardFailure(v), err
}
func guardTransportArgumentsDecodeValue86(d *json.Decoder) (GuardPlacementReply, error) {
	var zero GuardPlacementReply
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return zero, err
	}
	if v, err := DecodeGuardPlacementSuccess(raw); err == nil {
		return GuardPlacementReply{GuardPlacementSuccess: &v}, nil
	}
	if v, err := DecodeGuardFailure(raw); err == nil {
		return GuardPlacementReply{GuardFailure: &v}, nil
	}
	return zero, fmt.Errorf("no matching success variant")
}
func guardTransportArgumentsDecodeValue87(d *json.Decoder) (GuardPlacementSuccess, error) {
	v, err := guardTransportArgumentsDecodeValue88(d)
	return GuardPlacementSuccess(v), err
}
func guardTransportArgumentsDecodeValue88(d *json.Decoder) (GuardPlacementSuccess, error) {
	var result GuardPlacementSuccess
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "receipt":
			value, err := guardTransportArgumentsDecodeValue89(d)
			if err != nil {
				return result, fmt.Errorf("receipt: %w", err)
			}
			result.Receipt = value
		case "replayed":
			value, err := guardTransportArgumentsDecodeValue90(d)
			if err != nil {
				return result, fmt.Errorf("replayed: %w", err)
			}
			result.Replayed = value
		case "success":
			value, err := guardTransportArgumentsDecodeValue91(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["receipt"] {
		return result, fmt.Errorf("missing required field: receipt")
	}
	if !seen["replayed"] {
		return result, fmt.Errorf("missing required field: replayed")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue89(d *json.Decoder) (GuardReceipt, error) {
	v, err := guardTransportArgumentsDecodeValue19(d)
	return GuardReceipt(v), err
}
func guardTransportArgumentsDecodeValue90(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	return bool(value), err
}

func guardTransportArgumentsDecodeValue91(d *json.Decoder) (bool, error) {
	value, err := guardTransportArgumentsReadBoolean(d)
	if err == nil && value != true {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func guardTransportArgumentsDecodeValue92(d *json.Decoder) (GuardFailure, error) {
	v, err := guardTransportArgumentsDecodeValue50(d)
	return GuardFailure(v), err
}
func guardTransportArgumentsDecodeValue93(d *json.Decoder) (GuardPlacementRequest, error) {
	var result GuardPlacementRequest
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "actionId":
			value, err := guardTransportArgumentsDecodeValue94(d)
			if err != nil {
				return result, fmt.Errorf("actionId: %w", err)
			}
			result.ActionId = value
		case "attemptId":
			value, err := guardTransportArgumentsDecodeValue95(d)
			if err != nil {
				return result, fmt.Errorf("attemptId: %w", err)
			}
			result.AttemptId = value
		case "controllerSessionId":
			value, err := guardTransportArgumentsDecodeValue96(d)
			if err != nil {
				return result, fmt.Errorf("controllerSessionId: %w", err)
			}
			result.ControllerSessionId = value
		case "expectedGeneration":
			value, err := guardTransportArgumentsDecodeValue97(d)
			if err != nil {
				return result, fmt.Errorf("expectedGeneration: %w", err)
			}
			result.ExpectedGeneration = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue98(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "leaseId":
			value, err := guardTransportArgumentsDecodeValue99(d)
			if err != nil {
				return result, fmt.Errorf("leaseId: %w", err)
			}
			result.LeaseId = value
		case "placement":
			value, err := guardTransportArgumentsDecodeValue100(d)
			if err != nil {
				return result, fmt.Errorf("placement: %w", err)
			}
			result.Placement = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["actionId"] {
		return result, fmt.Errorf("missing required field: actionId")
	}
	if !seen["attemptId"] {
		return result, fmt.Errorf("missing required field: attemptId")
	}
	if !seen["controllerSessionId"] {
		return result, fmt.Errorf("missing required field: controllerSessionId")
	}
	if !seen["expectedGeneration"] {
		return result, fmt.Errorf("missing required field: expectedGeneration")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["leaseId"] {
		return result, fmt.Errorf("missing required field: leaseId")
	}
	if !seen["placement"] {
		return result, fmt.Errorf("missing required field: placement")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue94(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue95(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue96(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue97(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue98(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue99(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue100(d *json.Decoder) (GuardPlacement, error) {
	v, err := guardTransportArgumentsDecodeValue39(d)
	return GuardPlacement(v), err
}
func guardTransportArgumentsDecodeValue101(d *json.Decoder) (GuardRenewRequest, error) {
	var result GuardRenewRequest
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "controllerSessionId":
			value, err := guardTransportArgumentsDecodeValue102(d)
			if err != nil {
				return result, fmt.Errorf("controllerSessionId: %w", err)
			}
			result.ControllerSessionId = value
		case "expectedGeneration":
			value, err := guardTransportArgumentsDecodeValue103(d)
			if err != nil {
				return result, fmt.Errorf("expectedGeneration: %w", err)
			}
			result.ExpectedGeneration = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue104(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "leaseId":
			value, err := guardTransportArgumentsDecodeValue105(d)
			if err != nil {
				return result, fmt.Errorf("leaseId: %w", err)
			}
			result.LeaseId = value
		case "leaseMs":
			value, err := guardTransportArgumentsDecodeValue106(d)
			if err != nil {
				return result, fmt.Errorf("leaseMs: %w", err)
			}
			result.LeaseMs = value
		case "operation":
			value, err := guardTransportArgumentsDecodeValue107(d)
			if err != nil {
				return result, fmt.Errorf("operation: %w", err)
			}
			result.Operation = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["controllerSessionId"] {
		return result, fmt.Errorf("missing required field: controllerSessionId")
	}
	if !seen["expectedGeneration"] {
		return result, fmt.Errorf("missing required field: expectedGeneration")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["leaseId"] {
		return result, fmt.Errorf("missing required field: leaseId")
	}
	if !seen["leaseMs"] {
		return result, fmt.Errorf("missing required field: leaseMs")
	}
	if !seen["operation"] {
		return result, fmt.Errorf("missing required field: operation")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue102(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue103(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue104(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue105(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 256, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue106(d *json.Decoder) (int32, error) {
	value, err := guardTransportArgumentsReadInteger(d, 1000, 30000)
	return int32(value), err
}

func guardTransportArgumentsDecodeValue107(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 5, false)
	if err == nil {
		switch value {
		case "renew":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue108(d *json.Decoder) (GuardRevokeRequest, error) {
	var result GuardRevokeRequest
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "expectedGeneration":
			value, err := guardTransportArgumentsDecodeValue109(d)
			if err != nil {
				return result, fmt.Errorf("expectedGeneration: %w", err)
			}
			result.ExpectedGeneration = value
		case "identity":
			value, err := guardTransportArgumentsDecodeValue110(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		case "operation":
			value, err := guardTransportArgumentsDecodeValue111(d)
			if err != nil {
				return result, fmt.Errorf("operation: %w", err)
			}
			result.Operation = value
		case "reason":
			value, err := guardTransportArgumentsDecodeValue112(d)
			if err != nil {
				return result, fmt.Errorf("reason: %w", err)
			}
			result.Reason = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["expectedGeneration"] {
		return result, fmt.Errorf("missing required field: expectedGeneration")
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	if !seen["operation"] {
		return result, fmt.Errorf("missing required field: operation")
	}
	if !seen["reason"] {
		return result, fmt.Errorf("missing required field: reason")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue109(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 20, true)
	return string(value), err
}

func guardTransportArgumentsDecodeValue110(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}
func guardTransportArgumentsDecodeValue111(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 6, false)
	if err == nil {
		switch value {
		case "revoke":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue112(d *json.Decoder) (string, error) {
	value, err := guardTransportArgumentsReadString(d, 16, false)
	if err == nil {
		switch value {
		case "manual", "player_direction", "disconnect", "shutdown":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func guardTransportArgumentsDecodeValue113(d *json.Decoder) (GuardStatusReply, error) {
	var zero GuardStatusReply
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return zero, err
	}
	if v, err := DecodeGuardAuthorityStatus(raw); err == nil {
		return GuardStatusReply{GuardAuthorityStatus: &v}, nil
	}
	if v, err := DecodeGuardFailure(raw); err == nil {
		return GuardStatusReply{GuardFailure: &v}, nil
	}
	return zero, fmt.Errorf("no matching success variant")
}
func guardTransportArgumentsDecodeValue114(d *json.Decoder) (GuardAuthorityStatus, error) {
	v, err := guardTransportArgumentsDecodeValue73(d)
	return GuardAuthorityStatus(v), err
}
func guardTransportArgumentsDecodeValue115(d *json.Decoder) (GuardFailure, error) {
	v, err := guardTransportArgumentsDecodeValue50(d)
	return GuardFailure(v), err
}
func guardTransportArgumentsDecodeValue116(d *json.Decoder) (GuardStatusRequest, error) {
	var result GuardStatusRequest
	if err := guardTransportArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "identity":
			value, err := guardTransportArgumentsDecodeValue117(d)
			if err != nil {
				return result, fmt.Errorf("identity: %w", err)
			}
			result.Identity = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := guardTransportArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["identity"] {
		return result, fmt.Errorf("missing required field: identity")
	}
	return result, nil
}

func guardTransportArgumentsDecodeValue117(d *json.Decoder) (GuardIdentity, error) {
	v, err := guardTransportArgumentsDecodeValue6(d)
	return GuardIdentity(v), err
}

// Decoder input is bounded independently of schema field limits. Readers are not
// accepted: callers retain ownership of transport limits and cancellation.
const guardTransportArgumentsMaxContractBytes = 1 << 20

func guardTransportArgumentsNewContractDecoder(data []byte) (*json.Decoder, error) {
	if len(data) > guardTransportArgumentsMaxContractBytes {
		return nil, fmt.Errorf("contract JSON exceeds %d bytes", guardTransportArgumentsMaxContractBytes)
	}
	if err := guardTransportArgumentsValidJSONText(data); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decoder, nil
}

func guardTransportArgumentsEndContract(decoder *json.Decoder) error {
	if _, err := decoder.Token(); err != io.EOF {
		return fmt.Errorf("trailing or malformed JSON data")
	}
	return nil
}

// encoding/json replaces invalid UTF-8 and unpaired surrogate escapes. Reject
// those before decoding so contracts cannot silently change caller-provided text.
func guardTransportArgumentsValidJSONText(data []byte) error {
	if !utf8.Valid(data) {
		return fmt.Errorf("invalid UTF-8")
	}
	inString := false
	depth := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '"' {
			inString = !inString
			continue
		}
		if !inString {
			switch data[i] {
			case '{', '[':
				depth++
				if depth > 64 {
					return fmt.Errorf("JSON exceeds 64 containers")
				}
			case '}', ']':
				depth--
			}
		}
		if !inString || data[i] != '\\' {
			continue
		}
		i++
		if i >= len(data) {
			return fmt.Errorf("incomplete string escape")
		}
		if data[i] != 'u' {
			continue
		}
		if i+4 >= len(data) {
			return fmt.Errorf("incomplete Unicode escape")
		}
		unit, err := strconv.ParseUint(string(data[i+1:i+5]), 16, 16)
		if err != nil {
			return fmt.Errorf("invalid Unicode escape")
		}
		i += 4
		if unit >= 0xDC00 && unit <= 0xDFFF {
			return fmt.Errorf("unpaired low surrogate")
		}
		if unit < 0xD800 || unit > 0xDBFF {
			continue
		}
		if i+6 >= len(data) || data[i+1] != '\\' || data[i+2] != 'u' {
			return fmt.Errorf("unpaired high surrogate")
		}
		low, err := strconv.ParseUint(string(data[i+3:i+7]), 16, 16)
		if err != nil || low < 0xDC00 || low > 0xDFFF {
			return fmt.Errorf("unpaired high surrogate")
		}
		i += 6
	}
	return nil
}

func guardTransportArgumentsReadString(decoder *json.Decoder, maximum int, nonblank bool) (string, error) {
	value, err := decoder.Token()
	if err != nil {
		return "", err
	}
	text, ok := value.(string)
	if !ok {
		return "", fmt.Errorf("expected non-null string")
	}
	units, hasContent := 0, false
	for _, r := range text {
		units++
		if r > 0xFFFF {
			units++
		}
		if !guardTransportArgumentsDotNetWhitespace(r) {
			hasContent = true
		}
	}
	if units > maximum || nonblank && !hasContent {
		return "", fmt.Errorf("string violates UTF-16 length or nonblank constraint")
	}
	return text, nil
}

// Explicit Char.IsWhiteSpace set used by the net472 placement request contract.
func guardTransportArgumentsDotNetWhitespace(r rune) bool {
	return r >= '\t' && r <= '\r' || r == ' ' || r == 0x85 || r == 0xA0 ||
		r == 0x1680 || r >= 0x2000 && r <= 0x200A || r == 0x2028 || r == 0x2029 ||
		r == 0x202F || r == 0x205F || r == 0x3000
}

func guardTransportArgumentsReadInteger(decoder *json.Decoder, minimum, maximum int64) (int32, error) {
	value, err := decoder.Token()
	if err != nil {
		return 0, err
	}
	number, ok := value.(json.Number)
	if !ok {
		return 0, fmt.Errorf("expected non-null integer token")
	}
	parsed, err := strconv.ParseInt(string(number), 10, 32)
	if err != nil || parsed < minimum || parsed > maximum {
		return 0, fmt.Errorf("expected integer token within [%d,%d]", minimum, maximum)
	}
	return int32(parsed), nil
}

func guardTransportArgumentsReadBoolean(decoder *json.Decoder) (bool, error) {
	value, err := decoder.Token()
	if err != nil {
		return false, err
	}
	result, ok := value.(bool)
	if !ok {
		return false, fmt.Errorf("expected non-null boolean")
	}
	return result, nil
}

func guardTransportArgumentsExpectDelimiter(decoder *json.Decoder, want json.Delim) error {
	value, err := decoder.Token()
	if err != nil {
		return err
	}
	if value != want {
		return fmt.Errorf("expected %c", want)
	}
	return nil
}
