package contractgen

import (
	"bytes"
	"fmt"
	"strings"
)

type CSharpOptions struct {
	Namespace  string
	SchemaPath string
}

// GenerateCSharp emits immutable wire DTOs and strict JSON boundary decoders.
// Newtonsoft provides token conversion after a strict grammar/scalar scan.
func GenerateCSharp(schema *Schema, options CSharpOptions) ([]byte, error) {
	if err := ValidateSchema(schema); err != nil {
		return nil, err
	}
	if !relativePath(options.SchemaPath) || options.Namespace == "" {
		return nil, fmt.Errorf("invalid C# namespace or schema path")
	}
	for _, part := range strings.Split(options.Namespace, ".") {
		if !namePattern.MatchString(part) || csharpKeyword(part) {
			return nil, fmt.Errorf("invalid C# namespace")
		}
	}
	g := csharpGenerator{schema: schema, names: map[*Schema]string{}, functions: map[*Schema]string{}, boundary: schema.Title + "JsonBoundary"}
	g.names[schema] = schema.Title
	named := []*Schema{schema}
	for _, name := range sortedKeys(schema.Definitions) {
		node := schema.Definitions[name]
		if _, exists := g.names[node]; exists {
			return nil, fmt.Errorf("shared named schema pointer")
		}
		g.names[node] = name
		named = append(named, node)
	}
	occupied := map[string]bool{g.boundary: true}
	for _, node := range named {
		name := g.names[node]
		if occupied[name] || csharpReservedType(name) || name == "Decode" ||
			(node.Type != "object" && node.Type != "array" && name == "Value") ||
			(node.Type == "array" && (name == "Values" || name == "Count" || name == "GetEnumerator" || name == "Item")) {
			return nil, fmt.Errorf("C# generated type collision: %s", name)
		}
		occupied[name] = true
	}
	for _, node := range named {
		name := g.names[node]
		if node.Type != "object" && node.Type != "array" {
			converter := name + "WireConverter"
			if occupied[converter] {
				return nil, fmt.Errorf("C# converter name collision: %s", converter)
			}
			occupied[converter] = true
		}
		for key := range node.Properties {
			property := fieldName(key)
			if property == name || property == "Decode" || property == "GetType" || property == "GetHashCode" || property == "ToString" || property == "Equals" || property == "ReferenceEquals" || property == "MemberwiseClone" || property == "Finalize" {
				return nil, fmt.Errorf("C# property collision: %s", property)
			}
		}
		g.register(node)
	}
	fmt.Fprintf(&g.out, "// Code generated by contractgen format %d; DO NOT EDIT.\n// Source: %s\n// SHA256: %s\n#nullable enable\nusing System;\nusing System.Collections;\nusing System.Collections.Generic;\nusing System.Linq;\nusing Newtonsoft.Json;\nusing Newtonsoft.Json.Linq;\n\nnamespace %s\n{\n", FormatVersion, options.SchemaPath, schema.SourceSHA256, options.Namespace)
	for _, node := range named {
		g.model(node)
	}
	g.out.WriteString(strings.ReplaceAll(csharpBoundary, "__BOUNDARY__", g.boundary))
	for _, node := range g.nodes {
		g.decoder(node)
	}
	g.out.WriteString("    }\n}\n")
	return g.out.Bytes(), nil
}

type csharpGenerator struct {
	schema    *Schema
	names     map[*Schema]string
	functions map[*Schema]string
	nodes     []*Schema
	boundary  string
	out       bytes.Buffer
}

func csharpKeyword(name string) bool {
	for _, word := range strings.Fields("abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while") {
		if word == name {
			return true
		}
	}
	return false
}

func csharpReservedType(name string) bool {
	for _, word := range strings.Fields("System Type List DateParseHandling FloatParseHandling DuplicatePropertyNameHandling LineInfoHandling NullValueHandling MemberSerialization JsonSerializationException NotSupportedException JToken JObject JArray JTokenType JsonConverter JsonReader JsonWriter JsonSerializer JsonTextReader JsonLoadSettings JsonException JsonObject JsonArray JsonProperty JsonIgnore JsonConverterAttribute FormatException StringComparison Array IReadOnlyList IEnumerator IEnumerable") {
		if word == name {
			return true
		}
	}
	return false
}

func (g *csharpGenerator) register(node *Schema) {
	if _, exists := g.functions[node]; exists {
		return
	}
	g.functions[node] = fmt.Sprintf("ReadValue%d", len(g.nodes))
	g.nodes = append(g.nodes, node)
	if node.Ref != "" {
		g.register(g.schema.Definitions[strings.TrimPrefix(node.Ref, "#/$defs/")])
		return
	}
	for _, key := range sortedKeys(node.Properties) {
		g.register(node.Properties[key])
	}
	if node.Items != nil {
		g.register(node.Items)
	}
}
func (g *csharpGenerator) typ(node *Schema) string {
	if name, exists := g.names[node]; exists {
		return name
	}
	return g.underlying(node)
}
func (g *csharpGenerator) underlying(node *Schema) string {
	if node.Ref != "" {
		return strings.TrimPrefix(node.Ref, "#/$defs/")
	}
	switch node.Type {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	case "array":
		return "IReadOnlyList<" + g.typ(node.Items) + ">"
	default:
		panic("validated object is unnamed")
	}
}
func (g *csharpGenerator) propertyType(node *Schema, key string) string {
	typ := g.typ(node.Properties[key])
	if !required(node, key) {
		typ += "?"
	}
	return typ
}
func (g *csharpGenerator) model(node *Schema) {
	name := g.names[node]
	switch node.Type {
	case "object":
		fmt.Fprintf(&g.out, "    [JsonObject(MemberSerialization.OptIn)]\n    public sealed class %s\n    {\n", name)
		for _, key := range sortedKeys(node.Properties) {
			fmt.Fprintf(&g.out, "        [JsonProperty(%q, NullValueHandling = NullValueHandling.Ignore)]\n        public %s %s { get; }\n", key, g.propertyType(node, key), fieldName(key))
		}
		fmt.Fprintf(&g.out, "        internal %s(", name)
		for i, key := range sortedKeys(node.Properties) {
			if i > 0 {
				g.out.WriteString(", ")
			}
			fmt.Fprintf(&g.out, "%s value%d", g.propertyType(node, key), i)
		}
		g.out.WriteString(")\n        {\n")
		for i, key := range sortedKeys(node.Properties) {
			fmt.Fprintf(&g.out, "            %s = value%d;\n", fieldName(key), i)
		}
		g.out.WriteString("        }\n")
	case "array":
		item := g.typ(node.Items)
		fmt.Fprintf(&g.out, "    [JsonArray]\n    public sealed class %s : IReadOnlyList<%s>\n    {\n        public IReadOnlyList<%s> Values { get; }\n        internal %s(IReadOnlyList<%s> values) { Values = Array.AsReadOnly(values.ToArray()); }\n        public int Count { get { return Values.Count; } }\n        public %s this[int index] { get { return Values[index]; } }\n        public IEnumerator<%s> GetEnumerator() { return Values.GetEnumerator(); }\n        IEnumerator IEnumerable.GetEnumerator() { return GetEnumerator(); }\n", name, item, item, name, item, item, item)
	default:
		fmt.Fprintf(&g.out, "    [JsonConverter(typeof(%sWireConverter))]\n    public sealed class %s\n    {\n        public %s Value { get; }\n        internal %s(%s value) { Value = value; }\n", name, name, g.underlying(node), name, g.underlying(node))
	}
	fmt.Fprintf(&g.out, "        public static %s Decode(string json) { return %s.%s(%s.Parse(json)); }\n    }\n\n", name, g.boundary, g.functions[node], g.boundary)
	if node.Type != "object" && node.Type != "array" {
		fmt.Fprintf(&g.out, "    internal sealed class %sWireConverter : JsonConverter\n    {\n        public override bool CanRead { get { return false; } }\n        public override bool CanConvert(Type type) { return type == typeof(%s); }\n        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)\n        {\n            if (!(value is %s typed)) throw new JsonSerializationException(\"Unexpected wire value\");\n            serializer.Serialize(writer, typed.Value);\n        }\n        public override object ReadJson(JsonReader reader, Type type, object? existingValue, JsonSerializer serializer)\n        { throw new NotSupportedException(\"Use the strict Decode method\"); }\n    }\n\n", name, name, name)
	}
}
func (g *csharpGenerator) decoder(node *Schema) {
	typ := g.typ(node)
	fmt.Fprintf(&g.out, "        internal static %s %s(JToken token)\n        {\n", typ, g.functions[node])
	if node.Ref != "" {
		target := g.schema.Definitions[strings.TrimPrefix(node.Ref, "#/$defs/")]
		expression := g.functions[target] + "(token)"
		if _, named := g.names[node]; named {
			expression = "new " + typ + "(" + expression + ")"
		}
		fmt.Fprintf(&g.out, "            return %s;\n        }\n", expression)
		return
	}
	switch node.Type {
	case "object":
		g.out.WriteString("            if (!(token is JObject value)) throw new FormatException(\"Expected object\");\n            foreach (var property in value.Properties())\n            {\n                switch (property.Name)\n                {\n")
		for _, key := range sortedKeys(node.Properties) {
			fmt.Fprintf(&g.out, "                    case %q: break;\n", key)
		}
		g.out.WriteString("                    default: throw new FormatException(\"Unknown object field: \" + property.Name);\n                }\n            }\n")
		for i, key := range sortedKeys(node.Properties) {
			fmt.Fprintf(&g.out, "            %s field%d;\n            JToken? item%d;\n            if (value.TryGetValue(%q, StringComparison.Ordinal, out item%d)) field%d = %s(item%d!);\n", g.propertyType(node, key), i, i, key, i, i, g.functions[node.Properties[key]], i)
			if required(node, key) {
				fmt.Fprintf(&g.out, "            else throw new FormatException(%q);\n", "Missing required field: "+key)
			} else {
				fmt.Fprintf(&g.out, "            else field%d = null;\n", i)
			}
		}
		fmt.Fprintf(&g.out, "            return new %s(", typ)
		for i := range sortedKeys(node.Properties) {
			if i > 0 {
				g.out.WriteString(", ")
			}
			fmt.Fprintf(&g.out, "field%d", i)
		}
		g.out.WriteString(");\n")
	case "array":
		fmt.Fprintf(&g.out, "            if (!(token is JArray array) || array.Count < %d || array.Count > %d) throw new FormatException(\"Expected bounded array\");\n            var values = new List<%s>(array.Count);\n            foreach (var item in array) values.Add(%s(item));\n", *node.MinItems, *node.MaxItems, g.typ(node.Items), g.functions[node.Items])
		expression := "values.AsReadOnly()"
		if _, named := g.names[node]; named {
			expression = "new " + typ + "(" + expression + ")"
		}
		fmt.Fprintf(&g.out, "            return %s;\n", expression)
	default:
		var expression string
		switch node.Type {
		case "string":
			expression = fmt.Sprintf("ReadString(token, %d, %t)", *node.MaxUTF16Length, node.NonBlankDotNet != nil && *node.NonBlankDotNet)
		case "integer":
			expression = fmt.Sprintf("ReadInteger(token, %d, %d)", *node.Minimum, *node.Maximum)
		case "boolean":
			expression = "ReadBoolean(token)"
		}
		if _, named := g.names[node]; named {
			expression = "new " + typ + "(" + expression + ")"
		}
		fmt.Fprintf(&g.out, "            return %s;\n", expression)
	}
	g.out.WriteString("        }\n\n")
}
