package contractgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strings"
)

//go:embed runtime_support.go
var runtimeSource string

type GoOptions struct {
	Package    string
	SchemaPath string
}

// GenerateGo emits concrete models and strict boundary decoders. It does no I/O.
func GenerateGo(schema *Schema, options GoOptions) ([]byte, error) {
	if err := ValidateSchema(schema); err != nil {
		return nil, err
	}
	if !identifier(options.Package, false) || !relativePath(options.SchemaPath) {
		return nil, fmt.Errorf("invalid Go package or schema path")
	}
	g := goGenerator{names: map[*Schema]string{}, functions: map[*Schema]string{}, schema: schema}
	g.names[schema] = schema.Title
	named := []*Schema{schema}
	for _, name := range sortedKeys(schema.Definitions) {
		node := schema.Definitions[name]
		if _, exists := g.names[node]; exists {
			return nil, fmt.Errorf("shared named schema pointer")
		}
		g.names[node] = name
		named = append(named, node)
	}
	for _, node := range named {
		g.register(node)
	}
	fmt.Fprintf(&g.out, "// Code generated by contractgen format %d; DO NOT EDIT.\n// Source: %s\n// SHA256: %s\npackage %s\n\n", FormatVersion, options.SchemaPath, schema.SourceSHA256, options.Package)
	g.out.WriteString("import (\"bytes\"; \"encoding/json\"; \"fmt\"; \"io\"; \"strconv\"; \"unicode/utf8\")\n\n")
	for _, node := range named {
		name := g.names[node]
		fmt.Fprintf(&g.out, "type %s ", name)
		if node.OneOf != nil {
			g.out.WriteString("struct {\n")
			for _, branch := range node.OneOf {
				name := g.goType(branch)
				fmt.Fprintf(&g.out, "%s *%s `json:\"-\"`\n", name, name)
			}
			g.out.WriteString("}\n\n")
			fmt.Fprintf(&g.out, "func (v %s) MarshalJSON()([]byte,error){ var data []byte; var err error; count:=0;", name)
			for _, branch := range node.OneOf {
				branchName := g.goType(branch)
				fmt.Fprintf(&g.out, "if v.%s!=nil {count++;data,err=json.Marshal(v.%s);if err!=nil{return nil,err};if _,err=Decode%s(data);err!=nil{return nil,err}};", branchName, branchName, branchName)
			}
			g.out.WriteString("if count!=1{return nil,fmt.Errorf(\"exactly one variant branch required\")};return data,nil}\n")
		} else if node.Type == "object" {
			g.out.WriteString("struct {\n")
			for _, key := range sortedKeys(node.Properties) {
				typ, tag := g.goType(node.Properties[key]), key
				if !required(node, key) {
					typ, tag = "*"+typ, tag+",omitempty"
				}
				fmt.Fprintf(&g.out, "%s %s `json:%q`\n", fieldName(key), typ, tag)
			}
			g.out.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&g.out, "%s\n\n", g.underlyingType(node))
		}
		fmt.Fprintf(&g.out, "// Decode%s rejects missing/null/unknown/duplicate fields and malformed values.\nfunc Decode%s(data []byte) (%s,error) { var zero %s; d,err:=newContractDecoder(data); if err!=nil{return zero,err}; value,err:=%s(d); if err!=nil{return zero,err}; if err=endContract(d);err!=nil{return zero,err}; return value,nil }\n\n", name, name, name, name, g.functions[node])
	}
	for _, node := range g.nodes {
		g.decoder(node)
	}
	_, helpers, ok := strings.Cut(runtimeSource, "// BEGIN GENERATED HELPERS")
	if !ok {
		return nil, fmt.Errorf("generator runtime marker missing")
	}
	g.out.WriteString(helpers)
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, "generated.go", g.out.Bytes(), parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("generated Go is invalid: %w", err)
	}
	// Private helper names are scoped by root type so reply generation can share
	// a package without duplicating request decoder helpers.
	prefix := strings.ToLower(schema.Title[:1]) + schema.Title[1:]
	renamed := map[string]string{"maxContractBytes": prefix + "MaxContractBytes"}
	for _, declaration := range file.Decls {
		if function, ok := declaration.(*ast.FuncDecl); ok && !ast.IsExported(function.Name.Name) {
			renamed[function.Name.Name] = prefix + fieldName(function.Name.Name)
		}
	}
	ast.Inspect(file, func(node ast.Node) bool {
		if name, ok := node.(*ast.Ident); ok {
			if replacement, exists := renamed[name.Name]; exists {
				name.Name = replacement
			}
		}
		return true
	})
	var output bytes.Buffer
	if err := format.Node(&output, fileSet, file); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

type goGenerator struct {
	schema    *Schema
	names     map[*Schema]string
	functions map[*Schema]string
	nodes     []*Schema
	out       bytes.Buffer
}

func required(node *Schema, key string) bool {
	for _, name := range node.Required {
		if name == key {
			return true
		}
	}
	return false
}

func (g *goGenerator) register(node *Schema) {
	if _, exists := g.functions[node]; exists {
		return
	}
	g.functions[node] = fmt.Sprintf("decodeValue%d", len(g.nodes))
	g.nodes = append(g.nodes, node)
	if node.Ref != "" {
		g.register(g.schema.Definitions[strings.TrimPrefix(node.Ref, "#/$defs/")])
		return
	}
	for _, key := range sortedKeys(node.Properties) {
		g.register(node.Properties[key])
	}
	if node.Items != nil {
		g.register(node.Items)
	}
	for _, branch := range node.OneOf {
		g.register(branch)
	}
}

func (g *goGenerator) goType(node *Schema) string {
	if name, ok := g.names[node]; ok {
		return name
	}
	return g.underlyingType(node)
}

func (g *goGenerator) underlyingType(node *Schema) string {
	if node.Ref != "" {
		return strings.TrimPrefix(node.Ref, "#/$defs/")
	}
	switch node.Type {
	case "array":
		return "[]" + g.goType(node.Items)
	case "integer":
		if node.Nullable {
			return "*int32"
		}
		return "int32"
	case "boolean":
		return "bool"
	case "string":
		return "string"
	default:
		panic("validated object type is unnamed")
	}
}

func (g *goGenerator) decoder(node *Schema) {
	typ := g.goType(node)
	fmt.Fprintf(&g.out, "func %s(d *json.Decoder)(%s,error){\n", g.functions[node], typ)
	if node.Ref != "" {
		target := g.schema.Definitions[strings.TrimPrefix(node.Ref, "#/$defs/")]
		fmt.Fprintf(&g.out, "v,err:=%s(d); return %s(v),err\n}\n", g.functions[target], typ)
		return
	}
	if node.OneOf != nil {
		fmt.Fprintf(&g.out, "var zero %s;var raw json.RawMessage;if err:=d.Decode(&raw);err!=nil{return zero,err};", typ)
		for _, branch := range node.OneOf {
			name := g.goType(branch)
			fmt.Fprintf(&g.out, "if v,err:=Decode%s(raw);err==nil{return %s{%s:&v},nil};", name, typ, name)
		}
		g.out.WriteString("return zero,fmt.Errorf(\"no matching success variant\")}\n")
		return
	}
	if node.Nullable {
		fmt.Fprintf(&g.out, "var raw json.RawMessage;if err:=d.Decode(&raw);err!=nil{return nil,err};if bytes.Equal(bytes.TrimSpace(raw),[]byte(\"null\")){return nil,nil};nested,err:=newContractDecoder(raw);if err!=nil{return nil,err};v,err:=readInteger(nested,%d,%d);if err!=nil{return nil,err};return (%s)(&v),nil}\n", *node.Minimum, *node.Maximum, typ)
		return
	}
	switch node.Type {
	case "object":
		fmt.Fprintf(&g.out, "var result %s; if err:=expectDelimiter(d,'{');err!=nil{return result,err}; seen:=map[string]bool{}; for d.More(){ key,err:=d.Token(); if err!=nil{return result,err}; name,ok:=key.(string); if !ok||seen[name]{return result,fmt.Errorf(\"duplicate or invalid object field\")}; seen[name]=true; switch name {\n", typ)
		for _, key := range sortedKeys(node.Properties) {
			fmt.Fprintf(&g.out, "case %q: value,err:=%s(d); if err!=nil{return result,fmt.Errorf(%q,err)}; result.%s=", key, g.functions[node.Properties[key]], key+": %w", fieldName(key))
			if !required(node, key) {
				g.out.WriteString("&")
			}
			g.out.WriteString("value\n")
		}
		g.out.WriteString("default: return result,fmt.Errorf(\"unknown object field\")\n} }; if err:=expectDelimiter(d,'}');err!=nil{return result,err}\n")
		keys := append([]string(nil), node.Required...)
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(&g.out, "if !seen[%q]{return result,fmt.Errorf(%q)}\n", key, "missing required field: "+key)
		}
		g.out.WriteString("return result,nil\n")
	case "array":
		fmt.Fprintf(&g.out, "result:=make(%s,0); if err:=expectDelimiter(d,'[');err!=nil{return nil,err}; for d.More(){ if len(result)>=%d{return nil,fmt.Errorf(\"too many array items\")}; value,err:=%s(d);if err!=nil{return nil,err};result=append(result,value) }; if err:=expectDelimiter(d,']');err!=nil{return nil,err}; if len(result)<%d{return nil,fmt.Errorf(\"too few array items\")}; return result,nil\n", typ, *node.MaxItems, g.functions[node.Items], *node.MinItems)
	case "string":
		nonblank := node.NonBlankDotNet != nil && *node.NonBlankDotNet
		fmt.Fprintf(&g.out, "value,err:=readString(d,%d,%t);", *node.MaxUTF16Length, nonblank)
		if node.Enum != nil {
			g.out.WriteString("if err==nil {switch value {case ")
			for i, v := range node.Enum {
				if i > 0 {
					g.out.WriteString(",")
				}
				fmt.Fprintf(&g.out, "%q", v)
			}
			g.out.WriteString(": default:err=fmt.Errorf(\"invalid enum value\")}};")
		}
		fmt.Fprintf(&g.out, "return %s(value),err\n", typ)
	case "integer":
		fmt.Fprintf(&g.out, "value,err:=readInteger(d,%d,%d);return %s(value),err\n", *node.Minimum, *node.Maximum, typ)
	case "boolean":
		g.out.WriteString("value,err:=readBoolean(d);")
		if node.Const != nil {
			fmt.Fprintf(&g.out, "if err==nil && value!=%t {err=fmt.Errorf(\"invalid boolean constant\")};", *node.Const)
		}
		fmt.Fprintf(&g.out, "return %s(value),err\n", typ)
	}
	g.out.WriteString("}\n\n")
}
