package contractgen

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

type PythonOptions struct{ SchemaPath string }

// GeneratePython emits standard-library-only boundary types and strict decoders.
func GeneratePython(schema *Schema, options PythonOptions) ([]byte, error) {
	if err := ValidateSchema(schema); err != nil {
		return nil, err
	}
	if !relativePath(options.SchemaPath) || strings.ContainsAny(options.SchemaPath, "\r\n") {
		return nil, fmt.Errorf("invalid Python schema provenance path")
	}
	nodes := map[string]*Schema{schema.Title: schema}
	for name, node := range schema.Definitions {
		nodes[name] = node
	}
	reserved := " False None True and as assert async await break class continue def del elif else except finally for from global if import in is lambda nonlocal not or pass raise return try while with yield match case dataclass fields is_dataclass json cast Literal object str int bool list bytes set ValueError Missing MISSING "
	functions := map[string]bool{}
	for name, node := range nodes {
		decoder := pythonSnake(name)
		if strings.Contains(reserved, " "+name+" ") || functions[decoder] {
			return nil, fmt.Errorf("Python name collision: %s", name)
		}
		functions[decoder] = true
		for field := range node.Properties {
			if strings.Contains(reserved, " "+field+" ") {
				return nil, fmt.Errorf("unsupported Python property name: %s", field)
			}
		}
	}
	var output bytes.Buffer
	fmt.Fprintf(&output, "# Generated by RimGovernor contractgen format %d; DO NOT EDIT.\n# Source: %s\n# SHA-256: %s\n", FormatVersion, options.SchemaPath, schema.SourceSHA256)
	output.WriteString(pythonRuntime)
	// References are acyclic (ValidateSchema); emit dependencies before aliases.
	seen := map[string]bool{}
	var emit func(string)
	emit = func(name string) {
		if seen[name] {
			return
		}
		seen[name] = true
		node := nodes[name]
		var dependencies func(*Schema)
		dependencies = func(child *Schema) {
			if child.Ref != "" {
				emit(strings.TrimPrefix(child.Ref, "#/$defs/"))
			}
			for _, field := range sortedKeys(child.Properties) {
				dependencies(child.Properties[field])
			}
			if child.Items != nil {
				dependencies(child.Items)
			}
			for _, branch := range child.OneOf {
				dependencies(branch)
			}
		}
		dependencies(node)
		if node.Type == "object" {
			fmt.Fprintf(&output, "\n\n@dataclass(frozen=True, kw_only=True)\nclass %s:\n", name)
			if len(node.Properties) == 0 {
				output.WriteString("    pass\n")
			}
			for _, field := range sortedKeys(node.Properties) {
				typeName := pythonType(node.Properties[field])
				if !pythonRequired(node, field) {
					typeName += " | Missing = MISSING"
				}
				fmt.Fprintf(&output, "    %s: %s\n", field, typeName)
			}
		} else {
			fmt.Fprintf(&output, "\n\n%s = %s\n", name, pythonType(node))
		}
	}
	for _, name := range sortedKeys(nodes) {
		emit(name)
	}
	for _, name := range sortedKeys(nodes) {
		node := nodes[name]
		fmt.Fprintf(&output, "\n\ndef _parse_%s(value: object, path: str) -> %s:\n", name, name)
		if len(node.OneOf) > 0 {
			var success, failure string
			for _, branch := range node.OneOf {
				branchName := strings.TrimPrefix(branch.Ref, "#/$defs/")
				if *nodes[branchName].Properties["success"].Const {
					success = branchName
				} else {
					failure = branchName
				}
			}
			fmt.Fprintf(&output, "    if _discriminator(value, path):\n        return _parse_%s(value, path)\n    return _parse_%s(value, path)\n", success, failure)
		} else if node.Type == "object" {
			fmt.Fprintf(&output, "    row = _object(value, path, %s, %s)\n    return %s(\n", pythonNames(sortedKeys(node.Properties)), pythonNames(node.Required), name)
			for _, field := range sortedKeys(node.Properties) {
				expression := pythonExpression(node.Properties[field], "row["+strconv.Quote(field)+"]", "path + "+strconv.Quote("."+field))
				if !pythonRequired(node, field) {
					expression = "(" + expression + " if " + strconv.Quote(field) + " in row else MISSING)"
				}
				fmt.Fprintf(&output, "        %s=%s,\n", field, expression)
			}
			output.WriteString("    )\n")
		} else {
			fmt.Fprintf(&output, "    return %s\n", pythonExpression(node, "value", "path"))
		}
		fmt.Fprintf(&output, "\n\ndef decode_%s(raw: str | bytes) -> %s:\n    return _parse_%s(_document(raw), %s)\n", pythonSnake(name), name, name, strconv.Quote(name))
	}
	return output.Bytes(), nil
}

func pythonRequired(node *Schema, field string) bool {
	for _, required := range node.Required {
		if required == field {
			return true
		}
	}
	return false
}

func pythonNames(names []string) string {
	parts := make([]string, len(names))
	for i, name := range names {
		parts[i] = strconv.Quote(name)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func pythonSnake(name string) string {
	var result strings.Builder
	for i, char := range name {
		if char >= 'A' && char <= 'Z' {
			if i > 0 && (name[i-1] >= 'a' && name[i-1] <= 'z' || i+1 < len(name) && name[i+1] >= 'a' && name[i+1] <= 'z') {
				result.WriteByte('_')
			}
			char += 'a' - 'A'
		}
		result.WriteRune(char)
	}
	return result.String()
}

func pythonType(node *Schema) string {
	if len(node.OneOf) > 0 {
		parts := make([]string, len(node.OneOf))
		for i, branch := range node.OneOf {
			parts[i] = pythonType(branch)
		}
		return strings.Join(parts, " | ")
	}
	if node.Nullable {
		return "int | None"
	}
	if node.Const != nil {
		return "Literal[" + pythonBool(*node.Const) + "]"
	}
	if node.Enum != nil {
		return "Literal" + pythonNames(node.Enum)
	}
	if node.Ref != "" {
		return strings.TrimPrefix(node.Ref, "#/$defs/")
	}
	switch node.Type {
	case "array":
		return "list[" + pythonType(node.Items) + "]"
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	default:
		return "str"
	}
}

func pythonExpression(node *Schema, value, path string) string {
	if node.Nullable {
		copy := *node
		copy.Nullable = false
		return "(None if " + value + " is None else " + pythonExpression(&copy, value, path) + ")"
	}
	if node.Enum != nil {
		copy := *node
		copy.Enum = nil
		return fmt.Sprintf("cast(%s, _enum(%s, %s, %s))", pythonType(node), pythonExpression(&copy, value, path), path, pythonNames(node.Enum))
	}
	if node.Const != nil {
		return fmt.Sprintf("cast(%s, _boolean_const(%s, %s, %s))", pythonType(node), value, path, pythonBool(*node.Const))
	}
	if node.Ref != "" {
		return "_parse_" + strings.TrimPrefix(node.Ref, "#/$defs/") + "(" + value + ", " + path + ")"
	}
	switch node.Type {
	case "string":
		blank := "False"
		if node.NonBlankDotNet != nil && *node.NonBlankDotNet {
			blank = "True"
		}
		return fmt.Sprintf("_string(%s, %s, %d, %s)", value, path, *node.MaxUTF16Length, blank)
	case "integer":
		return fmt.Sprintf("_integer(%s, %s, %d, %d)", value, path, *node.Minimum, *node.Maximum)
	case "boolean":
		return fmt.Sprintf("_boolean(%s, %s)", value, path)
	case "array":
		return fmt.Sprintf("[%s for item in _array(%s, %s, %d, %d)]", pythonExpression(node.Items, "item", path+" + '[]'"), value, path, *node.MinItems, *node.MaxItems)
	default:
		panic("validated schema contains an inline object")
	}
}

func pythonBool(value bool) string {
	if value {
		return "True"
	}
	return "False"
}

const pythonRuntime = `from __future__ import annotations

from dataclasses import dataclass, fields, is_dataclass
import json
from typing import cast, Literal


class Missing:
    """Absent optional field, distinct from an explicitly nullable JSON field."""


MISSING = Missing()
_DOTNET_SPACE = "\u0009\u000a\u000b\u000c\u000d\u0020\u0085\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000"


def _pairs(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError('duplicate decoded object key')
        result[key] = value
    return result


def _constant(value: str) -> object:
    raise ValueError('nonstandard JSON constant')


def _scalars(value: object) -> None:
    if isinstance(value, str):
        value.encode('utf-8', errors='strict')
    elif isinstance(value, list):
        for item in value:
            _scalars(item)
    elif isinstance(value, dict):
        for key, item in value.items():
            _scalars(key)
            _scalars(item)


def _document(raw: str | bytes) -> object:
    if isinstance(raw, bytes):
        raw = raw.decode('utf-8', errors='strict')
    if not isinstance(raw, str):
        raise ValueError('JSON input must be str or bytes')
    if len(raw.encode('utf-8', errors='strict')) > 1048576:
        raise ValueError('JSON exceeds 1 MiB')
    depth = 0
    quoted = escaped = False
    for char in raw:
        if quoted:
            if escaped:
                escaped = False
            elif char == '\\':
                escaped = True
            elif char == '"':
                quoted = False
        elif char == '"':
            quoted = True
        elif char in '[{':
            depth += 1
            if depth > 64:
                raise ValueError('JSON exceeds 64 nesting levels')
        elif char in ']}':
            depth -= 1
    value: object = json.loads(raw, object_pairs_hook=_pairs, parse_constant=_constant)
    _scalars(value)
    return value


def _object(value: object, path: str, allowed: list[str], required: list[str]) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(path + ': expected object')
    row = cast(dict[str, object], value)
    if set(row) - set(allowed) or set(required) - set(row):
        raise ValueError(path + ': unknown or missing field')
    return row


def _array(value: object, path: str, minimum: int, maximum: int) -> list[object]:
    if not isinstance(value, list) or not minimum <= len(value) <= maximum:
        raise ValueError(path + ': invalid array or length')
    return cast(list[object], value)


def _string(value: object, path: str, maximum: int, nonblank: bool) -> str:
    if not isinstance(value, str) or len(value.encode('utf-16-le')) // 2 > maximum:
        raise ValueError(path + ': invalid string or UTF-16 length')
    if nonblank and not value.strip(_DOTNET_SPACE):
        raise ValueError(path + ': blank string')
    return value


def _integer(value: object, path: str, minimum: int, maximum: int) -> int:
    if type(value) is not int or not minimum <= value <= maximum:
        raise ValueError(path + ': expected bounded integer token')
    return value


def _boolean(value: object, path: str) -> bool:
    if type(value) is not bool:
        raise ValueError(path + ': expected boolean')
    return value


def _boolean_const(value: object, path: str, expected: bool) -> bool:
    result = _boolean(value, path)
    if result is not expected:
        raise ValueError(path + ': incorrect boolean constant')
    return result


def _enum(value: str, path: str, choices: list[str]) -> str:
    if value not in choices:
        raise ValueError(path + ': unknown string enum value')
    return value


def _discriminator(value: object, path: str) -> bool:
    if not isinstance(value, dict) or 'success' not in value:
        raise ValueError(path + ': missing success discriminator')
    return _boolean(value['success'], path + '.success')


def to_wire(value: object) -> object:
    """Convert generated values to JSON-compatible values, omitting absent fields.

    This does not validate manually constructed dataclasses; decode the serialized
    output before using externally constructed values as a request.
    """
    if is_dataclass(value) and not isinstance(value, type):
        return {field.name: to_wire(getattr(value, field.name)) for field in fields(value)
                if not isinstance(getattr(value, field.name), Missing)}
    if isinstance(value, list):
        return [to_wire(item) for item in value]
    if value is None or type(value) in (str, int, bool):
        return value
    raise ValueError('unsupported generated wire value')
`
