import {useEffect,useRef,useState} from 'react';
import './Manager.css';
import './BridgeColony.css';
type Message={id:number;kind:string;text:string;at:number};
type State={sessionId:string;connected:boolean;mode:string;mood:string;cameraVersion:number;goals:{long:string;short:string};feed:Message[];status:{label:string};game:{paused:boolean;stale:boolean};counters:{tools:number;actions:number;model_calls:number};observation?:{pawns:{thing_id:string;name:string;job:string|null}[]}|null};
export default function BridgeColony(){
 const [s,setState]=useState<State|null>(null),[error,setError]=useState(''),[text,setText]=useState(''),[sending,setSending]=useState(false),[view,setView]=useState(location.hash.slice(1)||'colony'),[events,setEvents]=useState<Message[]>([]),[camera,setCamera]=useState('');
 const input=useRef<HTMLTextAreaElement>(null),chat=useRef<HTMLDivElement>(null),surface=useRef<HTMLElement>(null);
 useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await fetch('/api/state');if(!r.ok)throw Error(`Connection failed (${r.status})`);const data=await r.json();if(!stopped){setState(data);setError('');}}catch(e){if(!stopped)setError(String(e));}if(!stopped)timer=setTimeout(poll,1500);};poll();return()=>{stopped=true;clearTimeout(timer);};},[]);
 useEffect(()=>{const change=()=>setView(location.hash.slice(1)||'colony');window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{setCamera('');setEvents([]);},[s?.sessionId]);
 useEffect(()=>{if(!s?.cameraVersion)return;let active=true;const url=`/api/camera?v=${s.cameraVersion}`;const image=new Image();image.onload=()=>{if(active)setCamera(url);};image.src=url;return()=>{active=false;};},[s?.cameraVersion]);
 useEffect(()=>{chat.current?.scrollTo?.(0,chat.current.scrollHeight);},[s?.feed.length]);
 useEffect(()=>{if(view==='colony')return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await fetch('/api/diagnostics');if(!r.ok)throw Error('Activity unavailable');const data=await r.json();if(active)setEvents(data.events);}catch(e){if(active)setError(String(e));}if(active)timer=setTimeout(poll,3000);};poll();return()=>{active=false;clearTimeout(timer);};},[view,s?.sessionId]);
 async function post(path:string,body:unknown){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-RimBot':'1'},body:JSON.stringify(body)});if(!r.ok){const data=await r.json();throw Error(data.detail||`Request failed (${r.status})`);}}
 async function send(){if(!text.trim()||sending)return;setSending(true);try{await post('chat',{text});setText('');input.current?.focus();}catch(e){setError(String(e));}finally{setSending(false);}}
 return <div className="mgr-shell bridge-shell"><header className="mgr-top"><a href="#" className="mgr-brand"><b>R</b> RimBot <span>/ Colony control</span></a><div className="mgr-inline"><span className="mgr-muted">{s?.connected?'Colony connected':'Connecting…'}</span><div className="mgr-switch">{['manual','automate'].map(mode=><button key={mode} disabled={!s?.connected} aria-pressed={s?.mode===mode} onClick={()=>post('control',{mode}).catch(e=>setError(String(e)))}>{mode==='manual'?'Manual':'Automate'}</button>)}</div></div></header>
 <nav className="colony-nav" aria-label="Colony navigation">{[['colony','Colony'],['projects','Projects'],['activity','Activity']].map(([id,label])=><a key={id} href={id==='colony'?'#':'#'+id} aria-current={view===id?'page':undefined}>{label}</a>)}</nav>
 {error&&<div role="alert" className="mgr-refresh-error">{error}</div>}
 <main className="bridge-main">{view==='colony'?<><section className="bridge-stage mgr-card" ref={surface}><div className="mgr-card-title"><h2>Your colony</h2><div className="mgr-inline"><span>{s?.game.stale?'Connection interrupted':s?.game.paused?'Paused':'Playing'}</span><button onClick={()=>surface.current?.requestFullscreen().catch(e=>setError(String(e)))}>Expand</button></div></div><div className="bridge-image">{camera?<img src={camera} alt="Current RimWorld colony"/>:<p>Waiting for the game view…</p>}</div><div className="bridge-summary"><span className="mgr-eyebrow">NEXT UP</span><p>{s?.goals.short||'Ask for a plan, or turn on Automate.'}</p><small className="mgr-muted">Game snapshots refresh every few seconds.</small></div></section>
 <section className="mgr-card mgr-conversation bridge-chat"><div className="mgr-card-title"><h2>Colony manager</h2><span className="mgr-pill">{s?.mood==='thinking'?'Thinking':'Ready'}</span></div><div className={'mgr-thinking '+(s?.mood==='thinking'?'busy':'')} role="status"><i/><div><b>{s?.status.label||'Connecting'}</b></div></div><div className="mgr-chat" ref={chat}>{s?.feed.length?s.feed.map(m=><div className={'mgr-message '+(m.kind==='human'?'player':'assistant')} key={m.id}><div>{m.kind==='human'?'You':'Colony manager'}</div><p>{m.text}</p></div>):<div className="mgr-welcome"><h3>Where should we take this colony?</h3><p>Ask a question or give a direction. You can steer while the manager is working.</p></div>}</div><form className="mgr-composer" onSubmit={e=>{e.preventDefault();send();}}><textarea ref={input} aria-label="Message the colony manager" value={text} onChange={e=>setText(e.target.value)} rows={3} maxLength={4000} placeholder="Ask, plan, or change direction…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><div><span>Enter to send · Shift + Enter for a new line</span><button disabled={!text.trim()||sending} className="mgr-primary">Send ↗</button></div></form></section></>:view==='projects'?<section className="mgr-card bridge-detail"><p className="mgr-eyebrow">LOOKING AHEAD</p><h1>The colony plan</h1><h2>Long term</h2><p>{s?.goals.long||'No long-term plan yet.'}</p><h2>Current work</h2><p>{s?.goals.short||'No current plan yet.'}</p><h2>Orders sent to the game</h2><p className="mgr-muted">Orders are receipts, not proof of finished construction. Detailed project tracking is still being migrated to the new bridge.</p>{events.filter(e=>e.kind==='action').map(e=><p key={e.id}>{e.text}</p>)}</section>:<section className="mgr-card bridge-detail"><h1>Activity</h1><p className="mgr-muted">{s?.counters.tools||0} tool calls · {s?.counters.actions||0} orders · {s?.counters.model_calls||0} model calls</p>{events.filter(e=>!['human','tool_result'].includes(e.kind)).map(e=><article key={e.id}><p>{e.text}</p></article>)}<details><summary>Tool details</summary><pre>{JSON.stringify(events.filter(e=>e.kind==='tool_result'),null,2)}</pre></details></section>}</main></div>;
}
