import {useEffect,useRef,useState} from 'react';
import Camera from './Camera';
import Diagnostics from './Diagnostics';
import Projects from './Projects';
import SpatialPlan from './SpatialPlan';
import ColonyNav from './ColonyNav';
import ManagerActivity from './ManagerActivity';
import {useController,ControllerState} from './useController';
import './Manager.css';

const list=(value:any,key?:string):any[]=>Array.isArray(value)?value:Array.isArray(value?.[key||'items'])?value[key||'items']:[];
const textName=(p:any)=>p.colonist?.name||(typeof p.name==='string'?p.name:p.name?.nick||p.name?.first||p.label||`Pawn ${p.id}`);

export default function Manager({onInspect,view='colony'}:{onInspect:()=>void;view?:'colony'|'work'|'activity'}) {
  const {state:s,error,setError,act}=useController();
  const [direction,setDirection]=useState(''),[goal,setGoal]=useState(''),[tab,setTab]=useState('today');
  const [history,setHistory]=useState(false),[settings,setSettings]=useState(false),[sending,setSending]=useState(false);
  const [now,setNow]=useState(Date.now());
  const [diagnostics,setDiagnostics]=useState(false);
  const chat=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null);
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
  useEffect(()=>{if(chat.current)chat.current.scrollTop=chat.current.scrollHeight;},[s?.memory.chat.length]);
  const o=s?.observation||{}, m=s?.memory, pawns=list(o.pawns,'colonists'), work=m?.work.filter(w=>history||!['complete','dismissed'].includes(w.status))||[];
  const day=o.game?Math.floor(o.game.game_tick/60000)+1:null;
  async function send(text=direction){if(!text.trim()||sending)return;setSending(true);if(await act('steer',{text})){setDirection('');input.current?.focus();}setSending(false);}
  return <div className="mgr-shell">
    <header className="mgr-top"><a className="mgr-brand" href="#"><b>R</b> RimBot <span>/ Colony control</span></a><div className="mgr-inline"><span className={'mgr-connection '+(s?.connected?'yes':'')}>{s?.connected?'Colony connected':'Not connected'}</span><button onClick={onInspect}>Colony details ↗</button><button onClick={()=>setSettings(true)}>Settings</button><div className="mgr-switch" aria-label="Colony control"><button aria-pressed={s?.mode!=='automate'} onClick={()=>act('control',{mode:'manual'})}>Manual</button><button aria-pressed={s?.mode==='automate'} disabled={!s?.connected} onClick={()=>act('control',{mode:'automate'})}>Automate</button></div></div></header>
    <ColonyNav active={view}/><main className="mgr-main"><section className="mgr-heading"><div><p className="mgr-eyebrow">YOUR COLONY, YOUR CALL</p><h1>{view==='work'?'Work in progress':view==='activity'?'Colony activity':day?`Day ${day}. What’s next?`:'The next chapter.'}</h1><p>{s?.connected?`${o.weather?.weather||'Colony online'} · ${o.game?.is_paused?'Game paused':'Life goes on'}`:'Connect RimWorld. Give the colony a direction.'}</p></div><div className="mgr-metrics">{[[o.game?.colonist_count,'Colonists'],[o.weather?.temperature!=null?Math.round(o.weather.temperature)+'°C':null,'Outside'],[o.game?.colony_wealth!=null?Math.round(o.game.colony_wealth).toLocaleString():null,'Wealth']].map(([v,k])=><div key={k}><b>{v??'—'}</b><span>{k}</span></div>)}</div></section>
    {!s?.connected&&<div className="mgr-banner"><i/><div><strong>Waiting for RimWorld</strong><p>Enable Harmony and RIMAPI, disable the old RimBot mod, then load a colony. The Python controller stays running between games.</p><small>{s?.status.detail}</small></div></div>}
    {view==='colony'&&<div className="mgr-grid"><div className="mgr-column"><Camera connected={!!s?.connected}/>
    {pawns.length>0&&<div className="mgr-pawns">{pawns.map((p:any)=><button key={p.colonist?.id??p.id??p.pawn_id} onClick={onInspect} title="Open the dashboard’s pawn inspectors"><span>{textName(p).slice(0,1)}</span><div><b>{textName(p)}</b><small>{p.colonist_work_info?.current_job||p.current_job?.label||(typeof p.current_job==='string'?p.current_job:'')||'View colonist'}</small></div></button>)}</div>}
    <section className="mgr-card"><div className="mgr-card-title"><div><span className="mgr-eyebrow">LOOKING AHEAD</span><h2>The plan</h2></div><button disabled={!s?.connected||s.busy} onClick={()=>act('strategy')}>Rethink strategy</button></div><div className="mgr-tabs" role="tablist">{[['today','Today'],['week','This week'],['season','This season'],['year','Long term']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="mgr-plan">{m?.plans?<>{(m.plans[tab]||[]).map((p:string,i:number)=><div className="mgr-plan-line" key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{p}</p></div>)}{tab==='year'&&<p className="mgr-muted">{m.plans.horizon}</p>}</>:<p className="mgr-empty">No plan yet. Enable Automate or ask for a strategy.</p>}</div><div className="mgr-goals"><div className="mgr-eyebrow">PLAYER OBJECTIVES</div>{m?.goals.map(g=><div className="mgr-goal" key={g.id}><span>{g.text}</span><button aria-label={`Remove objective: ${g.text}`} onClick={()=>act('goals/'+g.id,undefined,'DELETE')}>×</button></div>)}<form onSubmit={async e=>{e.preventDefault();if(await act('goals',{text:goal}))setGoal('');}}><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Add an objective…" aria-label="New objective" maxLength={500}/><button aria-label="Add objective" disabled={!goal.trim()}>+</button></form></div></section>
    </div><div className="mgr-column"><section className="mgr-card mgr-conversation"><div className="mgr-card-title"><div><span className="mgr-eyebrow">AT THE HELM</span><h2>Colony manager</h2></div><span className="mgr-pill">{s?.mode==='automate'?'Automate':'Manual'}</span></div><div className={'mgr-thinking '+(s?.busy?'busy':'')} aria-live="polite"><i/><div><b>{s?.busy?`${s.status.role||'Manager'} · ${s.status.phase}`:s?.status.phase||'Standing by'}</b><p>{s?.busy?`${s.counters.tools} tools · ${s.counters.actions} orders · ${s.status.detail||'Reviewing the colony'}`:s?.status.detail||'Give the colony a direction.'}</p></div><span>{s?.started_at?Math.max(0,Math.floor(now/1000-s.started_at))+'s':''}</span></div>
    <div className="mgr-chat" ref={chat} aria-live="polite">{m?.chat.length?m.chat.map((message,i)=><div className={'mgr-message '+message.role} key={i}><div>{message.role==='player'?'You':'Colony manager'}</div><p>{message.text}</p></div>):<div className="mgr-welcome"><h3>What should we work toward?</h3><p>Set the direction. The manager coordinates the work and checks what actually gets done.</p><div className="mgr-inline"><button onClick={()=>send('Build a self-sufficient colony. Establish sustainable food and comfortable shelter, then develop research and production.')}>Become self-sufficient</button><button onClick={()=>send('Assess the colony and tell me what needs attention first.')}>What needs attention?</button></div></div>}</div>
    <form className="mgr-composer" onSubmit={e=>{e.preventDefault();send();}}><textarea ref={input} value={direction} onChange={e=>setDirection(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}} rows={2} maxLength={3000} placeholder="Give a direction, ask a question, change priorities…" aria-label="Direction for the colony manager"/><div><span>Enter to send · Shift + Enter for a new line</span><button className="mgr-primary" disabled={!direction.trim()||sending}>Send ↗</button></div></form></section>
    <SpatialPlan colony={s?.colony} layout={(m as any)?.spatial_layout}/>
    </div></div>}
    {view==='work'&&<div className="mgr-work-page"><Projects projects={m?.projects||[]} onCancel={id=>act('projects/'+id,undefined,'DELETE')}/><section className="mgr-card"><div className="mgr-card-title"><div><span className="mgr-eyebrow">FOLLOWING THROUGH</span><h2>Work <span className="mgr-muted">{work.length}</span></h2></div><label className="mgr-small"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/> Show finished</label></div><div className="mgr-work">{work.length?work.map(w=><div className="mgr-work-row" key={w.id}><span className={w.status==='complete'?'done':''}>{w.status==='complete'?'✓':'◷'}</span><div><b>{w.title}</b><p>{w.detail}</p><small>{w.role} · {w.status}</small></div><button title="Remove from tracking; game orders stay in place" aria-label={`Dismiss ${w.title}`} onClick={()=>act('work/'+w.id,undefined,'DELETE')}>×</button></div>):<p className="mgr-empty">No tracked work. Orders appear here with their observed progress.</p>}</div></section></div>}
    {view==='activity'&&<><ManagerActivity colony={s?.colony} busy={s?.busy} status={s?.status} assignments={m?.plans?.assignments}/>
    <section className="mgr-card"><div className="mgr-card-title"><button aria-expanded={diagnostics} onClick={()=>setDiagnostics(v=>!v)}>{diagnostics?'Hide diagnostics':'Diagnostics'}</button><a href="/api/history" download>Export full log</a></div>{diagnostics&&<Diagnostics/>}</section>
    </>}<footer className="mgr-footer"><span>Built on RIMAPI Dashboard · Local colony controller</span><span>{s?.capabilities||0} available capabilities · Events {s?.events_connected?'connected':'reconnecting'}</span></footer></main>
    {settings&&s&&<SettingsDialog state={s} onClose={()=>setSettings(false)} save={async settings=>{if(await act('settings',settings))setSettings(false);}}/>}
    {error&&<div role="alert" className="mgr-toast"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
  </div>;
}

function SettingsDialog({state,onClose,save}:{state:ControllerState;onClose:()=>void;save:(settings:any)=>Promise<void>}) {
  const ref=useRef<HTMLDialogElement>(null),[value,setValue]=useState({...state.settings});
  useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
  const field=(name:string,label:string,type='text')=><label>{label}<input type={type} value={value[name]??''} onChange={e=>setValue({...value,[name]:type==='number'?Number(e.target.value):e.target.value})} required={name!=='manager_model'}/></label>;
  return <dialog ref={ref} className="mgr-settings" onCancel={onClose}><form onSubmit={e=>{e.preventDefault();save(value);}}><div className="mgr-card-title"><h2>Connections & model</h2><button type="button" onClick={onClose} aria-label="Close settings">×</button></div><p className="mgr-muted">Connect the game and model running on this computer.</p>{field('rimapi_url','RIMAPI address','url')}{field('model_url','LM Studio address','url')}{field('model','Planning & administrator model')}{field('manager_model','Department model (blank uses planning model)')}{field('manager_parallelism','Concurrent department reviews (1–4)','number')}<div className="mgr-form-grid">{field('max_output_tokens','Output token allowance','number')}{field('context_chars','Context budget (characters)','number')}</div>{field('review_ticks','Routine review interval (game ticks)','number')}<label>Map<select value={value.map_id??''} onChange={e=>setValue({...value,map_id:e.target.value===''?null:Number(e.target.value)})}><option value="">Player home map</option>{list(state.observation.maps).map(m=><option key={m.id} value={m.id}>Map {m.id}{m.is_player_home?' · Home':''}</option>)}</select></label><label className="mgr-check"><input type="checkbox" checked={value.reasoning} onChange={e=>setValue({...value,reasoning:e.target.checked})}/> Reasoning for planning (Qwen on/off)</label><p className="mgr-small">Events also trigger reviews. Saving settings returns control to Manual.</p><button className="mgr-primary">Save connections</button></form></dialog>;
}

