// Code generated by contractgen format 1; DO NOT EDIT.
// Source: contracts/schemas/placement-previews-request.v1.schema.json
// SHA256: f2ef7527a8c9fd771cc3587383d8b5e9c77ab36126f43f6a1b308e8266ae8987
package placementpreview

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"unicode/utf8"
)

type PlacementPreviewArguments struct {
	Placements string `json:"placements"`
}

// DecodePlacementPreviewArguments rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePlacementPreviewArguments(data []byte) (PlacementPreviewArguments, error) {
	var zero PlacementPreviewArguments
	d, err := placementPreviewArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := placementPreviewArgumentsDecodeValue0(d)
	if err != nil {
		return zero, err
	}
	if err = placementPreviewArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PlacementBatch []PlacementCandidate

// DecodePlacementBatch rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePlacementBatch(data []byte) (PlacementBatch, error) {
	var zero PlacementBatch
	d, err := placementPreviewArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := placementPreviewArgumentsDecodeValue2(d)
	if err != nil {
		return zero, err
	}
	if err = placementPreviewArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PlacementCandidate struct {
	DefName  string `json:"defName"`
	Rotation string `json:"rotation"`
	Stuff    string `json:"stuff"`
	X        int32  `json:"x"`
	Z        int32  `json:"z"`
}

// DecodePlacementCandidate rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePlacementCandidate(data []byte) (PlacementCandidate, error) {
	var zero PlacementCandidate
	d, err := placementPreviewArgumentsNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := placementPreviewArgumentsDecodeValue4(d)
	if err != nil {
		return zero, err
	}
	if err = placementPreviewArgumentsEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

func placementPreviewArgumentsDecodeValue0(d *json.Decoder) (PlacementPreviewArguments, error) {
	var result PlacementPreviewArguments
	if err := placementPreviewArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "placements":
			value, err := placementPreviewArgumentsDecodeValue1(d)
			if err != nil {
				return result, fmt.Errorf("placements: %w", err)
			}
			result.Placements = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := placementPreviewArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["placements"] {
		return result, fmt.Errorf("missing required field: placements")
	}
	return result, nil
}

func placementPreviewArgumentsDecodeValue1(d *json.Decoder) (string, error) {
	value, err := placementPreviewArgumentsReadString(d, 32768, false)
	return string(value), err
}

func placementPreviewArgumentsDecodeValue2(d *json.Decoder) (PlacementBatch, error) {
	result := make(PlacementBatch, 0)
	if err := placementPreviewArgumentsExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 16 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := placementPreviewArgumentsDecodeValue3(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := placementPreviewArgumentsExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 1 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func placementPreviewArgumentsDecodeValue3(d *json.Decoder) (PlacementCandidate, error) {
	v, err := placementPreviewArgumentsDecodeValue4(d)
	return PlacementCandidate(v), err
}
func placementPreviewArgumentsDecodeValue4(d *json.Decoder) (PlacementCandidate, error) {
	var result PlacementCandidate
	if err := placementPreviewArgumentsExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "defName":
			value, err := placementPreviewArgumentsDecodeValue5(d)
			if err != nil {
				return result, fmt.Errorf("defName: %w", err)
			}
			result.DefName = value
		case "rotation":
			value, err := placementPreviewArgumentsDecodeValue6(d)
			if err != nil {
				return result, fmt.Errorf("rotation: %w", err)
			}
			result.Rotation = value
		case "stuff":
			value, err := placementPreviewArgumentsDecodeValue7(d)
			if err != nil {
				return result, fmt.Errorf("stuff: %w", err)
			}
			result.Stuff = value
		case "x":
			value, err := placementPreviewArgumentsDecodeValue8(d)
			if err != nil {
				return result, fmt.Errorf("x: %w", err)
			}
			result.X = value
		case "z":
			value, err := placementPreviewArgumentsDecodeValue9(d)
			if err != nil {
				return result, fmt.Errorf("z: %w", err)
			}
			result.Z = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := placementPreviewArgumentsExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["defName"] {
		return result, fmt.Errorf("missing required field: defName")
	}
	if !seen["rotation"] {
		return result, fmt.Errorf("missing required field: rotation")
	}
	if !seen["stuff"] {
		return result, fmt.Errorf("missing required field: stuff")
	}
	if !seen["x"] {
		return result, fmt.Errorf("missing required field: x")
	}
	if !seen["z"] {
		return result, fmt.Errorf("missing required field: z")
	}
	return result, nil
}

func placementPreviewArgumentsDecodeValue5(d *json.Decoder) (string, error) {
	value, err := placementPreviewArgumentsReadString(d, 200, true)
	return string(value), err
}

func placementPreviewArgumentsDecodeValue6(d *json.Decoder) (string, error) {
	value, err := placementPreviewArgumentsReadString(d, 200, true)
	return string(value), err
}

func placementPreviewArgumentsDecodeValue7(d *json.Decoder) (string, error) {
	value, err := placementPreviewArgumentsReadString(d, 200, false)
	return string(value), err
}

func placementPreviewArgumentsDecodeValue8(d *json.Decoder) (int32, error) {
	value, err := placementPreviewArgumentsReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func placementPreviewArgumentsDecodeValue9(d *json.Decoder) (int32, error) {
	value, err := placementPreviewArgumentsReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

// Decoder input is bounded independently of schema field limits. Readers are not
// accepted: callers retain ownership of transport limits and cancellation.
const placementPreviewArgumentsMaxContractBytes = 1 << 20

func placementPreviewArgumentsNewContractDecoder(data []byte) (*json.Decoder, error) {
	if len(data) > placementPreviewArgumentsMaxContractBytes {
		return nil, fmt.Errorf("contract JSON exceeds %d bytes", placementPreviewArgumentsMaxContractBytes)
	}
	if err := placementPreviewArgumentsValidJSONText(data); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decoder, nil
}

func placementPreviewArgumentsEndContract(decoder *json.Decoder) error {
	if _, err := decoder.Token(); err != io.EOF {
		return fmt.Errorf("trailing or malformed JSON data")
	}
	return nil
}

// encoding/json replaces invalid UTF-8 and unpaired surrogate escapes. Reject
// those before decoding so contracts cannot silently change caller-provided text.
func placementPreviewArgumentsValidJSONText(data []byte) error {
	if !utf8.Valid(data) {
		return fmt.Errorf("invalid UTF-8")
	}
	inString := false
	depth := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '"' {
			inString = !inString
			continue
		}
		if !inString {
			switch data[i] {
			case '{', '[':
				depth++
				if depth > 64 {
					return fmt.Errorf("JSON exceeds 64 containers")
				}
			case '}', ']':
				depth--
			}
		}
		if !inString || data[i] != '\\' {
			continue
		}
		i++
		if i >= len(data) {
			return fmt.Errorf("incomplete string escape")
		}
		if data[i] != 'u' {
			continue
		}
		if i+4 >= len(data) {
			return fmt.Errorf("incomplete Unicode escape")
		}
		unit, err := strconv.ParseUint(string(data[i+1:i+5]), 16, 16)
		if err != nil {
			return fmt.Errorf("invalid Unicode escape")
		}
		i += 4
		if unit >= 0xDC00 && unit <= 0xDFFF {
			return fmt.Errorf("unpaired low surrogate")
		}
		if unit < 0xD800 || unit > 0xDBFF {
			continue
		}
		if i+6 >= len(data) || data[i+1] != '\\' || data[i+2] != 'u' {
			return fmt.Errorf("unpaired high surrogate")
		}
		low, err := strconv.ParseUint(string(data[i+3:i+7]), 16, 16)
		if err != nil || low < 0xDC00 || low > 0xDFFF {
			return fmt.Errorf("unpaired high surrogate")
		}
		i += 6
	}
	return nil
}

func placementPreviewArgumentsReadString(decoder *json.Decoder, maximum int, nonblank bool) (string, error) {
	value, err := decoder.Token()
	if err != nil {
		return "", err
	}
	text, ok := value.(string)
	if !ok {
		return "", fmt.Errorf("expected non-null string")
	}
	units, hasContent := 0, false
	for _, r := range text {
		units++
		if r > 0xFFFF {
			units++
		}
		if !placementPreviewArgumentsDotNetWhitespace(r) {
			hasContent = true
		}
	}
	if units > maximum || nonblank && !hasContent {
		return "", fmt.Errorf("string violates UTF-16 length or nonblank constraint")
	}
	return text, nil
}

// Explicit Char.IsWhiteSpace set used by the net472 placement request contract.
func placementPreviewArgumentsDotNetWhitespace(r rune) bool {
	return r >= '\t' && r <= '\r' || r == ' ' || r == 0x85 || r == 0xA0 ||
		r == 0x1680 || r >= 0x2000 && r <= 0x200A || r == 0x2028 || r == 0x2029 ||
		r == 0x202F || r == 0x205F || r == 0x3000
}

func placementPreviewArgumentsReadInteger(decoder *json.Decoder, minimum, maximum int64) (int32, error) {
	value, err := decoder.Token()
	if err != nil {
		return 0, err
	}
	number, ok := value.(json.Number)
	if !ok {
		return 0, fmt.Errorf("expected non-null integer token")
	}
	parsed, err := strconv.ParseInt(string(number), 10, 32)
	if err != nil || parsed < minimum || parsed > maximum {
		return 0, fmt.Errorf("expected integer token within [%d,%d]", minimum, maximum)
	}
	return int32(parsed), nil
}

func placementPreviewArgumentsReadBoolean(decoder *json.Decoder) (bool, error) {
	value, err := decoder.Token()
	if err != nil {
		return false, err
	}
	result, ok := value.(bool)
	if !ok {
		return false, fmt.Errorf("expected non-null boolean")
	}
	return result, nil
}

func placementPreviewArgumentsExpectDelimiter(decoder *json.Decoder, want json.Delim) error {
	value, err := decoder.Token()
	if err != nil {
		return err
	}
	if value != want {
		return fmt.Errorf("expected %c", want)
	}
	return nil
}
