// Code generated by contractgen format 1; DO NOT EDIT.
// Source: contracts/schemas/placement-previews-response.v2.schema.json
// SHA256: 0fc3483d066537ecd2027603d33016a06fc9dad89a7603091fb1d41f1cdcb23a
package placementpreview

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"unicode/utf8"
)

type PreviewReply struct {
	PreviewBatch   *PreviewBatch   `json:"-"`
	PreviewFailure *PreviewFailure `json:"-"`
}

func (v PreviewReply) MarshalJSON() ([]byte, error) {
	var data []byte
	var err error
	count := 0
	if v.PreviewBatch != nil {
		count++
		data, err = json.Marshal(v.PreviewBatch)
		if err != nil {
			return nil, err
		}
		if _, err = DecodePreviewBatch(data); err != nil {
			return nil, err
		}
	}
	if v.PreviewFailure != nil {
		count++
		data, err = json.Marshal(v.PreviewFailure)
		if err != nil {
			return nil, err
		}
		if _, err = DecodePreviewFailure(data); err != nil {
			return nil, err
		}
	}
	if count != 1 {
		return nil, fmt.Errorf("exactly one variant branch required")
	}
	return data, nil
}

// DecodePreviewReply rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewReply(data []byte) (PreviewReply, error) {
	var zero PreviewReply
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue0(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewBatch struct {
	MapId   int32              `json:"mapId"`
	Results []PreviewCandidate `json:"results"`
	Success bool               `json:"success"`
	Tick    int32              `json:"tick"`
	Version int32              `json:"version"`
}

// DecodePreviewBatch rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewBatch(data []byte) (PreviewBatch, error) {
	var zero PreviewBatch
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue2(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewBlocker struct {
	Category              string `json:"category"`
	FrameWouldBeCancelled bool   `json:"frameWouldBeCancelled"`
	IsBlueprint           bool   `json:"isBlueprint"`
	IsFrame               bool   `json:"isFrame"`
	WouldBeWiped          bool   `json:"wouldBeWiped"`
}

// DecodePreviewBlocker rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewBlocker(data []byte) (PreviewBlocker, error) {
	var zero PreviewBlocker
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue34(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewCandidate struct {
	PreviewEvaluated *PreviewEvaluated `json:"-"`
	PreviewFailure   *PreviewFailure   `json:"-"`
}

func (v PreviewCandidate) MarshalJSON() ([]byte, error) {
	var data []byte
	var err error
	count := 0
	if v.PreviewEvaluated != nil {
		count++
		data, err = json.Marshal(v.PreviewEvaluated)
		if err != nil {
			return nil, err
		}
		if _, err = DecodePreviewEvaluated(data); err != nil {
			return nil, err
		}
	}
	if v.PreviewFailure != nil {
		count++
		data, err = json.Marshal(v.PreviewFailure)
		if err != nil {
			return nil, err
		}
		if _, err = DecodePreviewFailure(data); err != nil {
			return nil, err
		}
	}
	if count != 1 {
		return nil, fmt.Errorf("exactly one variant branch required")
	}
	return data, nil
}

// DecodePreviewCandidate rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewCandidate(data []byte) (PreviewCandidate, error) {
	var zero PreviewCandidate
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue6(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewCell struct {
	X int32 `json:"x"`
	Z int32 `json:"z"`
}

// DecodePreviewCell rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewCell(data []byte) (PreviewCell, error) {
	var zero PreviewCell
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue42(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewCost struct {
	Count   int32  `json:"count"`
	DefName string `json:"defName"`
}

// DecodePreviewCost rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewCost(data []byte) (PreviewCost, error) {
	var zero PreviewCost
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue13(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewEvaluated struct {
	BuildableByPlayer bool              `json:"buildableByPlayer"`
	CanPlace          bool              `json:"canPlace"`
	CostList          []PreviewCost     `json:"costList"`
	IsDoor            bool              `json:"isDoor"`
	MadeFromStuff     bool              `json:"madeFromStuff"`
	Materials         PreviewMaterials  `json:"materials"`
	Passability       string            `json:"passability"`
	ResearchFinished  bool              `json:"researchFinished"`
	Rotations         []PreviewRotation `json:"rotations"`
	Success           bool              `json:"success"`
}

// DecodePreviewEvaluated rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewEvaluated(data []byte) (PreviewEvaluated, error) {
	var zero PreviewEvaluated
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue8(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewFailure struct {
	Error   string `json:"error"`
	Success bool   `json:"success"`
}

// DecodePreviewFailure rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewFailure(data []byte) (PreviewFailure, error) {
	var zero PreviewFailure
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue49(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewMaterialStock struct {
	Available *int32 `json:"available"`
	DefName   string `json:"defName"`
}

// DecodePreviewMaterialStock rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewMaterialStock(data []byte) (PreviewMaterialStock, error) {
	var zero PreviewMaterialStock
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue22(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewMaterials struct {
	Rows       []PreviewMaterialStock `json:"rows"`
	Unreadable bool                   `json:"unreadable"`
}

// DecodePreviewMaterials rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewMaterials(data []byte) (PreviewMaterials, error) {
	var zero PreviewMaterials
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue19(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

type PreviewRotation struct {
	Accepted       bool             `json:"accepted"`
	BlockingThings []PreviewBlocker `json:"blockingThings"`
	OccupiedCells  []PreviewCell    `json:"occupiedCells"`
	Reason         string           `json:"reason"`
	Rotation       string           `json:"rotation"`
}

// DecodePreviewRotation rejects missing/null/unknown/duplicate fields and malformed values.
func DecodePreviewRotation(data []byte) (PreviewRotation, error) {
	var zero PreviewRotation
	d, err := previewReplyNewContractDecoder(data)
	if err != nil {
		return zero, err
	}
	value, err := previewReplyDecodeValue30(d)
	if err != nil {
		return zero, err
	}
	if err = previewReplyEndContract(d); err != nil {
		return zero, err
	}
	return value, nil
}

func previewReplyDecodeValue0(d *json.Decoder) (PreviewReply, error) {
	var zero PreviewReply
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return zero, err
	}
	if v, err := DecodePreviewBatch(raw); err == nil {
		return PreviewReply{PreviewBatch: &v}, nil
	}
	if v, err := DecodePreviewFailure(raw); err == nil {
		return PreviewReply{PreviewFailure: &v}, nil
	}
	return zero, fmt.Errorf("no matching success variant")
}
func previewReplyDecodeValue1(d *json.Decoder) (PreviewBatch, error) {
	v, err := previewReplyDecodeValue2(d)
	return PreviewBatch(v), err
}
func previewReplyDecodeValue2(d *json.Decoder) (PreviewBatch, error) {
	var result PreviewBatch
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "mapId":
			value, err := previewReplyDecodeValue3(d)
			if err != nil {
				return result, fmt.Errorf("mapId: %w", err)
			}
			result.MapId = value
		case "results":
			value, err := previewReplyDecodeValue4(d)
			if err != nil {
				return result, fmt.Errorf("results: %w", err)
			}
			result.Results = value
		case "success":
			value, err := previewReplyDecodeValue52(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		case "tick":
			value, err := previewReplyDecodeValue53(d)
			if err != nil {
				return result, fmt.Errorf("tick: %w", err)
			}
			result.Tick = value
		case "version":
			value, err := previewReplyDecodeValue54(d)
			if err != nil {
				return result, fmt.Errorf("version: %w", err)
			}
			result.Version = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["mapId"] {
		return result, fmt.Errorf("missing required field: mapId")
	}
	if !seen["results"] {
		return result, fmt.Errorf("missing required field: results")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	if !seen["tick"] {
		return result, fmt.Errorf("missing required field: tick")
	}
	if !seen["version"] {
		return result, fmt.Errorf("missing required field: version")
	}
	return result, nil
}

func previewReplyDecodeValue3(d *json.Decoder) (int32, error) {
	value, err := previewReplyReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func previewReplyDecodeValue4(d *json.Decoder) ([]PreviewCandidate, error) {
	result := make([]PreviewCandidate, 0)
	if err := previewReplyExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 16 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := previewReplyDecodeValue5(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := previewReplyExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 1 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func previewReplyDecodeValue5(d *json.Decoder) (PreviewCandidate, error) {
	v, err := previewReplyDecodeValue6(d)
	return PreviewCandidate(v), err
}
func previewReplyDecodeValue6(d *json.Decoder) (PreviewCandidate, error) {
	var zero PreviewCandidate
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return zero, err
	}
	if v, err := DecodePreviewEvaluated(raw); err == nil {
		return PreviewCandidate{PreviewEvaluated: &v}, nil
	}
	if v, err := DecodePreviewFailure(raw); err == nil {
		return PreviewCandidate{PreviewFailure: &v}, nil
	}
	return zero, fmt.Errorf("no matching success variant")
}
func previewReplyDecodeValue7(d *json.Decoder) (PreviewEvaluated, error) {
	v, err := previewReplyDecodeValue8(d)
	return PreviewEvaluated(v), err
}
func previewReplyDecodeValue8(d *json.Decoder) (PreviewEvaluated, error) {
	var result PreviewEvaluated
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "buildableByPlayer":
			value, err := previewReplyDecodeValue9(d)
			if err != nil {
				return result, fmt.Errorf("buildableByPlayer: %w", err)
			}
			result.BuildableByPlayer = value
		case "canPlace":
			value, err := previewReplyDecodeValue10(d)
			if err != nil {
				return result, fmt.Errorf("canPlace: %w", err)
			}
			result.CanPlace = value
		case "costList":
			value, err := previewReplyDecodeValue11(d)
			if err != nil {
				return result, fmt.Errorf("costList: %w", err)
			}
			result.CostList = value
		case "isDoor":
			value, err := previewReplyDecodeValue16(d)
			if err != nil {
				return result, fmt.Errorf("isDoor: %w", err)
			}
			result.IsDoor = value
		case "madeFromStuff":
			value, err := previewReplyDecodeValue17(d)
			if err != nil {
				return result, fmt.Errorf("madeFromStuff: %w", err)
			}
			result.MadeFromStuff = value
		case "materials":
			value, err := previewReplyDecodeValue18(d)
			if err != nil {
				return result, fmt.Errorf("materials: %w", err)
			}
			result.Materials = value
		case "passability":
			value, err := previewReplyDecodeValue26(d)
			if err != nil {
				return result, fmt.Errorf("passability: %w", err)
			}
			result.Passability = value
		case "researchFinished":
			value, err := previewReplyDecodeValue27(d)
			if err != nil {
				return result, fmt.Errorf("researchFinished: %w", err)
			}
			result.ResearchFinished = value
		case "rotations":
			value, err := previewReplyDecodeValue28(d)
			if err != nil {
				return result, fmt.Errorf("rotations: %w", err)
			}
			result.Rotations = value
		case "success":
			value, err := previewReplyDecodeValue47(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["buildableByPlayer"] {
		return result, fmt.Errorf("missing required field: buildableByPlayer")
	}
	if !seen["canPlace"] {
		return result, fmt.Errorf("missing required field: canPlace")
	}
	if !seen["costList"] {
		return result, fmt.Errorf("missing required field: costList")
	}
	if !seen["isDoor"] {
		return result, fmt.Errorf("missing required field: isDoor")
	}
	if !seen["madeFromStuff"] {
		return result, fmt.Errorf("missing required field: madeFromStuff")
	}
	if !seen["materials"] {
		return result, fmt.Errorf("missing required field: materials")
	}
	if !seen["passability"] {
		return result, fmt.Errorf("missing required field: passability")
	}
	if !seen["researchFinished"] {
		return result, fmt.Errorf("missing required field: researchFinished")
	}
	if !seen["rotations"] {
		return result, fmt.Errorf("missing required field: rotations")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func previewReplyDecodeValue9(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue10(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue11(d *json.Decoder) ([]PreviewCost, error) {
	result := make([]PreviewCost, 0)
	if err := previewReplyExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 256 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := previewReplyDecodeValue12(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := previewReplyExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func previewReplyDecodeValue12(d *json.Decoder) (PreviewCost, error) {
	v, err := previewReplyDecodeValue13(d)
	return PreviewCost(v), err
}
func previewReplyDecodeValue13(d *json.Decoder) (PreviewCost, error) {
	var result PreviewCost
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "count":
			value, err := previewReplyDecodeValue14(d)
			if err != nil {
				return result, fmt.Errorf("count: %w", err)
			}
			result.Count = value
		case "defName":
			value, err := previewReplyDecodeValue15(d)
			if err != nil {
				return result, fmt.Errorf("defName: %w", err)
			}
			result.DefName = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["count"] {
		return result, fmt.Errorf("missing required field: count")
	}
	if !seen["defName"] {
		return result, fmt.Errorf("missing required field: defName")
	}
	return result, nil
}

func previewReplyDecodeValue14(d *json.Decoder) (int32, error) {
	value, err := previewReplyReadInteger(d, 0, 2147483647)
	return int32(value), err
}

func previewReplyDecodeValue15(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 200, false)
	return string(value), err
}

func previewReplyDecodeValue16(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue17(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue18(d *json.Decoder) (PreviewMaterials, error) {
	v, err := previewReplyDecodeValue19(d)
	return PreviewMaterials(v), err
}
func previewReplyDecodeValue19(d *json.Decoder) (PreviewMaterials, error) {
	var result PreviewMaterials
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "rows":
			value, err := previewReplyDecodeValue20(d)
			if err != nil {
				return result, fmt.Errorf("rows: %w", err)
			}
			result.Rows = value
		case "unreadable":
			value, err := previewReplyDecodeValue25(d)
			if err != nil {
				return result, fmt.Errorf("unreadable: %w", err)
			}
			result.Unreadable = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["rows"] {
		return result, fmt.Errorf("missing required field: rows")
	}
	if !seen["unreadable"] {
		return result, fmt.Errorf("missing required field: unreadable")
	}
	return result, nil
}

func previewReplyDecodeValue20(d *json.Decoder) ([]PreviewMaterialStock, error) {
	result := make([]PreviewMaterialStock, 0)
	if err := previewReplyExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 256 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := previewReplyDecodeValue21(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := previewReplyExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func previewReplyDecodeValue21(d *json.Decoder) (PreviewMaterialStock, error) {
	v, err := previewReplyDecodeValue22(d)
	return PreviewMaterialStock(v), err
}
func previewReplyDecodeValue22(d *json.Decoder) (PreviewMaterialStock, error) {
	var result PreviewMaterialStock
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "available":
			value, err := previewReplyDecodeValue23(d)
			if err != nil {
				return result, fmt.Errorf("available: %w", err)
			}
			result.Available = value
		case "defName":
			value, err := previewReplyDecodeValue24(d)
			if err != nil {
				return result, fmt.Errorf("defName: %w", err)
			}
			result.DefName = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["available"] {
		return result, fmt.Errorf("missing required field: available")
	}
	if !seen["defName"] {
		return result, fmt.Errorf("missing required field: defName")
	}
	return result, nil
}

func previewReplyDecodeValue23(d *json.Decoder) (*int32, error) {
	var raw json.RawMessage
	if err := d.Decode(&raw); err != nil {
		return nil, err
	}
	if bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return nil, nil
	}
	nested, err := previewReplyNewContractDecoder(raw)
	if err != nil {
		return nil, err
	}
	v, err := previewReplyReadInteger(nested, 0, 2147483647)
	if err != nil {
		return nil, err
	}
	return (*int32)(&v), nil
}
func previewReplyDecodeValue24(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 200, false)
	return string(value), err
}

func previewReplyDecodeValue25(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue26(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 200, false)
	if err == nil {
		switch value {
		case "Standable", "PassThroughOnly", "Impassable":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func previewReplyDecodeValue27(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue28(d *json.Decoder) ([]PreviewRotation, error) {
	result := make([]PreviewRotation, 0)
	if err := previewReplyExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 4 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := previewReplyDecodeValue29(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := previewReplyExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 1 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func previewReplyDecodeValue29(d *json.Decoder) (PreviewRotation, error) {
	v, err := previewReplyDecodeValue30(d)
	return PreviewRotation(v), err
}
func previewReplyDecodeValue30(d *json.Decoder) (PreviewRotation, error) {
	var result PreviewRotation
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "accepted":
			value, err := previewReplyDecodeValue31(d)
			if err != nil {
				return result, fmt.Errorf("accepted: %w", err)
			}
			result.Accepted = value
		case "blockingThings":
			value, err := previewReplyDecodeValue32(d)
			if err != nil {
				return result, fmt.Errorf("blockingThings: %w", err)
			}
			result.BlockingThings = value
		case "occupiedCells":
			value, err := previewReplyDecodeValue40(d)
			if err != nil {
				return result, fmt.Errorf("occupiedCells: %w", err)
			}
			result.OccupiedCells = value
		case "reason":
			value, err := previewReplyDecodeValue45(d)
			if err != nil {
				return result, fmt.Errorf("reason: %w", err)
			}
			result.Reason = value
		case "rotation":
			value, err := previewReplyDecodeValue46(d)
			if err != nil {
				return result, fmt.Errorf("rotation: %w", err)
			}
			result.Rotation = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["accepted"] {
		return result, fmt.Errorf("missing required field: accepted")
	}
	if !seen["blockingThings"] {
		return result, fmt.Errorf("missing required field: blockingThings")
	}
	if !seen["occupiedCells"] {
		return result, fmt.Errorf("missing required field: occupiedCells")
	}
	if !seen["reason"] {
		return result, fmt.Errorf("missing required field: reason")
	}
	if !seen["rotation"] {
		return result, fmt.Errorf("missing required field: rotation")
	}
	return result, nil
}

func previewReplyDecodeValue31(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue32(d *json.Decoder) ([]PreviewBlocker, error) {
	result := make([]PreviewBlocker, 0)
	if err := previewReplyExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 4096 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := previewReplyDecodeValue33(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := previewReplyExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 0 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func previewReplyDecodeValue33(d *json.Decoder) (PreviewBlocker, error) {
	v, err := previewReplyDecodeValue34(d)
	return PreviewBlocker(v), err
}
func previewReplyDecodeValue34(d *json.Decoder) (PreviewBlocker, error) {
	var result PreviewBlocker
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "category":
			value, err := previewReplyDecodeValue35(d)
			if err != nil {
				return result, fmt.Errorf("category: %w", err)
			}
			result.Category = value
		case "frameWouldBeCancelled":
			value, err := previewReplyDecodeValue36(d)
			if err != nil {
				return result, fmt.Errorf("frameWouldBeCancelled: %w", err)
			}
			result.FrameWouldBeCancelled = value
		case "isBlueprint":
			value, err := previewReplyDecodeValue37(d)
			if err != nil {
				return result, fmt.Errorf("isBlueprint: %w", err)
			}
			result.IsBlueprint = value
		case "isFrame":
			value, err := previewReplyDecodeValue38(d)
			if err != nil {
				return result, fmt.Errorf("isFrame: %w", err)
			}
			result.IsFrame = value
		case "wouldBeWiped":
			value, err := previewReplyDecodeValue39(d)
			if err != nil {
				return result, fmt.Errorf("wouldBeWiped: %w", err)
			}
			result.WouldBeWiped = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["category"] {
		return result, fmt.Errorf("missing required field: category")
	}
	if !seen["frameWouldBeCancelled"] {
		return result, fmt.Errorf("missing required field: frameWouldBeCancelled")
	}
	if !seen["isBlueprint"] {
		return result, fmt.Errorf("missing required field: isBlueprint")
	}
	if !seen["isFrame"] {
		return result, fmt.Errorf("missing required field: isFrame")
	}
	if !seen["wouldBeWiped"] {
		return result, fmt.Errorf("missing required field: wouldBeWiped")
	}
	return result, nil
}

func previewReplyDecodeValue35(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 200, false)
	return string(value), err
}

func previewReplyDecodeValue36(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue37(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue38(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue39(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	return bool(value), err
}

func previewReplyDecodeValue40(d *json.Decoder) ([]PreviewCell, error) {
	result := make([]PreviewCell, 0)
	if err := previewReplyExpectDelimiter(d, '['); err != nil {
		return nil, err
	}
	for d.More() {
		if len(result) >= 4096 {
			return nil, fmt.Errorf("too many array items")
		}
		value, err := previewReplyDecodeValue41(d)
		if err != nil {
			return nil, err
		}
		result = append(result, value)
	}
	if err := previewReplyExpectDelimiter(d, ']'); err != nil {
		return nil, err
	}
	if len(result) < 1 {
		return nil, fmt.Errorf("too few array items")
	}
	return result, nil
}

func previewReplyDecodeValue41(d *json.Decoder) (PreviewCell, error) {
	v, err := previewReplyDecodeValue42(d)
	return PreviewCell(v), err
}
func previewReplyDecodeValue42(d *json.Decoder) (PreviewCell, error) {
	var result PreviewCell
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "x":
			value, err := previewReplyDecodeValue43(d)
			if err != nil {
				return result, fmt.Errorf("x: %w", err)
			}
			result.X = value
		case "z":
			value, err := previewReplyDecodeValue44(d)
			if err != nil {
				return result, fmt.Errorf("z: %w", err)
			}
			result.Z = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["x"] {
		return result, fmt.Errorf("missing required field: x")
	}
	if !seen["z"] {
		return result, fmt.Errorf("missing required field: z")
	}
	return result, nil
}

func previewReplyDecodeValue43(d *json.Decoder) (int32, error) {
	value, err := previewReplyReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func previewReplyDecodeValue44(d *json.Decoder) (int32, error) {
	value, err := previewReplyReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func previewReplyDecodeValue45(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 4096, false)
	return string(value), err
}

func previewReplyDecodeValue46(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 200, false)
	if err == nil {
		switch value {
		case "north", "east", "south", "west":
		default:
			err = fmt.Errorf("invalid enum value")
		}
	}
	return string(value), err
}

func previewReplyDecodeValue47(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	if err == nil && value != true {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func previewReplyDecodeValue48(d *json.Decoder) (PreviewFailure, error) {
	v, err := previewReplyDecodeValue49(d)
	return PreviewFailure(v), err
}
func previewReplyDecodeValue49(d *json.Decoder) (PreviewFailure, error) {
	var result PreviewFailure
	if err := previewReplyExpectDelimiter(d, '{'); err != nil {
		return result, err
	}
	seen := map[string]bool{}
	for d.More() {
		key, err := d.Token()
		if err != nil {
			return result, err
		}
		name, ok := key.(string)
		if !ok || seen[name] {
			return result, fmt.Errorf("duplicate or invalid object field")
		}
		seen[name] = true
		switch name {
		case "error":
			value, err := previewReplyDecodeValue50(d)
			if err != nil {
				return result, fmt.Errorf("error: %w", err)
			}
			result.Error = value
		case "success":
			value, err := previewReplyDecodeValue51(d)
			if err != nil {
				return result, fmt.Errorf("success: %w", err)
			}
			result.Success = value
		default:
			return result, fmt.Errorf("unknown object field")
		}
	}
	if err := previewReplyExpectDelimiter(d, '}'); err != nil {
		return result, err
	}
	if !seen["error"] {
		return result, fmt.Errorf("missing required field: error")
	}
	if !seen["success"] {
		return result, fmt.Errorf("missing required field: success")
	}
	return result, nil
}

func previewReplyDecodeValue50(d *json.Decoder) (string, error) {
	value, err := previewReplyReadString(d, 4096, false)
	return string(value), err
}

func previewReplyDecodeValue51(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	if err == nil && value != false {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func previewReplyDecodeValue52(d *json.Decoder) (bool, error) {
	value, err := previewReplyReadBoolean(d)
	if err == nil && value != true {
		err = fmt.Errorf("invalid boolean constant")
	}
	return bool(value), err
}

func previewReplyDecodeValue53(d *json.Decoder) (int32, error) {
	value, err := previewReplyReadInteger(d, -2147483648, 2147483647)
	return int32(value), err
}

func previewReplyDecodeValue54(d *json.Decoder) (int32, error) {
	value, err := previewReplyReadInteger(d, 2, 2)
	return int32(value), err
}

func previewReplyDecodeValue55(d *json.Decoder) (PreviewFailure, error) {
	v, err := previewReplyDecodeValue49(d)
	return PreviewFailure(v), err
}

// Decoder input is bounded independently of schema field limits. Readers are not
// accepted: callers retain ownership of transport limits and cancellation.
const previewReplyMaxContractBytes = 1 << 20

func previewReplyNewContractDecoder(data []byte) (*json.Decoder, error) {
	if len(data) > previewReplyMaxContractBytes {
		return nil, fmt.Errorf("contract JSON exceeds %d bytes", previewReplyMaxContractBytes)
	}
	if err := previewReplyValidJSONText(data); err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decoder, nil
}

func previewReplyEndContract(decoder *json.Decoder) error {
	if _, err := decoder.Token(); err != io.EOF {
		return fmt.Errorf("trailing or malformed JSON data")
	}
	return nil
}

// encoding/json replaces invalid UTF-8 and unpaired surrogate escapes. Reject
// those before decoding so contracts cannot silently change caller-provided text.
func previewReplyValidJSONText(data []byte) error {
	if !utf8.Valid(data) {
		return fmt.Errorf("invalid UTF-8")
	}
	inString := false
	depth := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '"' {
			inString = !inString
			continue
		}
		if !inString {
			switch data[i] {
			case '{', '[':
				depth++
				if depth > 64 {
					return fmt.Errorf("JSON exceeds 64 containers")
				}
			case '}', ']':
				depth--
			}
		}
		if !inString || data[i] != '\\' {
			continue
		}
		i++
		if i >= len(data) {
			return fmt.Errorf("incomplete string escape")
		}
		if data[i] != 'u' {
			continue
		}
		if i+4 >= len(data) {
			return fmt.Errorf("incomplete Unicode escape")
		}
		unit, err := strconv.ParseUint(string(data[i+1:i+5]), 16, 16)
		if err != nil {
			return fmt.Errorf("invalid Unicode escape")
		}
		i += 4
		if unit >= 0xDC00 && unit <= 0xDFFF {
			return fmt.Errorf("unpaired low surrogate")
		}
		if unit < 0xD800 || unit > 0xDBFF {
			continue
		}
		if i+6 >= len(data) || data[i+1] != '\\' || data[i+2] != 'u' {
			return fmt.Errorf("unpaired high surrogate")
		}
		low, err := strconv.ParseUint(string(data[i+3:i+7]), 16, 16)
		if err != nil || low < 0xDC00 || low > 0xDFFF {
			return fmt.Errorf("unpaired high surrogate")
		}
		i += 6
	}
	return nil
}

func previewReplyReadString(decoder *json.Decoder, maximum int, nonblank bool) (string, error) {
	value, err := decoder.Token()
	if err != nil {
		return "", err
	}
	text, ok := value.(string)
	if !ok {
		return "", fmt.Errorf("expected non-null string")
	}
	units, hasContent := 0, false
	for _, r := range text {
		units++
		if r > 0xFFFF {
			units++
		}
		if !previewReplyDotNetWhitespace(r) {
			hasContent = true
		}
	}
	if units > maximum || nonblank && !hasContent {
		return "", fmt.Errorf("string violates UTF-16 length or nonblank constraint")
	}
	return text, nil
}

// Explicit Char.IsWhiteSpace set used by the net472 placement request contract.
func previewReplyDotNetWhitespace(r rune) bool {
	return r >= '\t' && r <= '\r' || r == ' ' || r == 0x85 || r == 0xA0 ||
		r == 0x1680 || r >= 0x2000 && r <= 0x200A || r == 0x2028 || r == 0x2029 ||
		r == 0x202F || r == 0x205F || r == 0x3000
}

func previewReplyReadInteger(decoder *json.Decoder, minimum, maximum int64) (int32, error) {
	value, err := decoder.Token()
	if err != nil {
		return 0, err
	}
	number, ok := value.(json.Number)
	if !ok {
		return 0, fmt.Errorf("expected non-null integer token")
	}
	parsed, err := strconv.ParseInt(string(number), 10, 32)
	if err != nil || parsed < minimum || parsed > maximum {
		return 0, fmt.Errorf("expected integer token within [%d,%d]", minimum, maximum)
	}
	return int32(parsed), nil
}

func previewReplyReadBoolean(decoder *json.Decoder) (bool, error) {
	value, err := decoder.Token()
	if err != nil {
		return false, err
	}
	result, ok := value.(bool)
	if !ok {
		return false, fmt.Errorf("expected non-null boolean")
	}
	return result, nil
}

func previewReplyExpectDelimiter(decoder *json.Decoder, want json.Delim) error {
	value, err := decoder.Token()
	if err != nil {
		return err
	}
	if value != want {
		return fmt.Errorf("expected %c", want)
	}
	return nil
}
